- README.md
Users should go to the react-native getting started page in step one so they make sure they download the right version
> README: remove first step in Android setup to remove confusion

- components/QRCodeScanner.tsx
This change improves QR code scanning success rate on smaller Android phones by removing the limited scan area and using the whole camera image to scan.
Needs to be tested across other phones and iOS.
A styled overlay can be added later to imply some kind of scanning frame.
> Remove barcode frame from scanner

- views/LNDConnectConfigQRScanner.tsx
- views/Send.tsx
Allow users to prefix their pastes on the Send view with bitcoin: and lightning:. Also handles amounts passed in to the invoice
> Send view prefixes

- views/Wallet/MainPane.tsx
The idea is to make `AddressQRCodeScanner` a scanner for both invoices and lnurl things, so even if you're in the Pay screen and click scan you'll be able to scan an lnurl. So why not have a scanner button in the main app pane?
This is useful because after lnurl-withdraw we can introduce lnurl-pay, lnurl-auth and lnurl-channel reusing the same basic lnurl interface and scanning everything from the same place, without having to make a custom scanner for each and add buttons whoknowswhere for all these kinds of lnurls.
Even if you're not interested in adding all the bizarre lnurl types, I still think having the scanner in the front of the app is a good idea.
I also like the idea of swiping to the right to scan, instead of clicking. Is that an addition I should investigate?
> add scan button to MainPane.

- stores/InvoicesStore.ts
- stores/SettingsStore.ts
- views/Settings.tsx
- views/Settings/AddEditNode.tsx
- views/Settings/Nodes.tsx
It's annoying to have to go into the node configuration to make it the active node. Now on the Settings page, clicking the node entry will make it active and take you back to the Wallet view. To change the configuration of the node you will now tap the settings gear to its right.
> Improved Node Switching Workflow

- utils/FeeUtils.test.ts
- utils/FeeUtils.ts
make sure small values denominated in bitcoin are never collapsed to exponential notation
> Fix toFixed utility function

- views/Settings/Nodes.tsx
users were losing fiat, lurker mode, and passphrase settings upon switching between nodes
> Bug fix: retain settings on node change

- android/app/src/main/AndroidManifest.xml
- ios/zeus/Info.plist
- utils/handleAnything.ts
- views/Settings/AddEditNode.tsx
This PR adds support for reading lndconnect connection strings off the clipboard on the Node Configuration view and for adding linking that will directly open and process those strings when encountered on the web or in a different app.
This should make the workflow from Nayuta Core, when used on the same device, much smoother!
> Node Configuration: lndconnect clipboard import and linking

- views/Settings/AddEditNode.tsx
When saving your first account, Mobx would hit an error when you attempted to read nodes[0] when settings was undefined
> Bug fix: Mobx index issue

- views/Settings/AddEditNode.tsx
Modal was not closing all the time
> Fix cert modal

- views/SendingLightning.tsx
The issue is the same old "text must be rendered inside <Text> components".
lntxbot returns empty strings for some fields that other lndHub servers return null, that causes glitches in some condition checks.
Reported by Hamish MacEwan.
> fix: handle lntxbot lndhub empty strings.

- components/QRCodeScanner.tsx
Currently we are catching _every possible error that may happen on `handleQRScanned`_ and handling it by just sending telling the user to scan again. This is wrong and unnecessary. At the point we call `handleQRScanned` the scan part has already ended, so it should be done outside of the `catch {}` block.
Now specific errors related to `handleQRScanned` should be dealt with separately.
This PR saves users from the burden of having to scan the same QR twice before seeing an inevitable crash.
Reported by Hamish.
I have tested this PR with the following types of nodes (please specify …
> Don't prompt a second QR scan when an error happens on handleQRScanned

- views/Settings/AddEditNode.tsx
Fixes #357.
I had the node saved before the locale changes were made and didn't notice my rebase introduced this issue.
> fix vanishing eclair password.

- backends/LND.ts
- utils/AddressUtils.test.ts
- utils/AddressUtils.ts
This PR fixes two issues:
* Add node QR code scans were failing with LndHub URLs from the new LNbits LndHub extension.
* lnbits LndHub extension was showing an URL with an ending slash. Although this could be fixed on the LNbits side it is a good measure to always remove the ending slash before adding our route path that will contain an starting slash. …
> Fix issues with LNbits LndHub support

- backends/Eclair.ts
Invoices were not showing up on Eclair because the `from` filter was formatted as a float but needed to be an int.
> fix eclair getInvoices "from" filter.

- backends/Eclair.ts
Relates to issue: https://t.me/zeusLN/15514
When I was testing Eclair on regtest I had so many satoshis I didn't notice Zeus was showing 1000x more than I should.
> Eclair balances in sats instead of millisats.

- views/Settings/AddEditNode.tsx
Relates to issue: **ZEUS-373**
Locale setting was resetting to English when changing/saving node configs.
> Bug fix: Locale gets reset on node config changes

- backends/Eclair.ts
- models/Invoice.ts
We weren't returning timestamps in our mapping function causing the display to be Dec 31 1969 for each invoice
> Eclair: Fix timestamps

- backends/Eclair.ts
- views/NodeInfo.tsx
- views/Wallet/MainPane.tsx
The button to go to the my node info view was not rendering + other fixes on that view
> Eclair: Fix my node info view

- backends/Eclair.ts
Relates to issue: **ZEUS-0405**
Eclair reports timestamps in msec instead of seconds.
- [X ] Bug fix
- [X ] No, I’m a fool
> Fix timestamps for Eclair

- backends/Eclair.ts
- backends/LND.ts
- backends/LndHub.ts
- backends/Spark.ts
- utils/LndConnectUtils.test.ts
- utils/LndConnectUtils.ts
- utils/RESTUtils.ts
All backends whether using Tor or not will now be configured similarly. Protocols must be specified in the host field. LNDConnect import now also appends https:// to the host field.
> Tor: HTTPS fix

- stores/SettingsStore.ts
When connecting to BTCPay server via QR, the host value would not get imported properly. This is due to a change made in v0.5.0 that allows users to connect over an unencrypted http connection if they so please. Shouts to Chaz for the report.
> Bug fix: fix BTCPay node import QR scans

- stores/FiatStore.ts
- stores/UnitsStore.ts
- views/Receive.tsx
Fiat conversion rate was broken on the receive view, when viewing sats amount when user is entering in fiat. Also added a rates display.
> Receive: Fix fiat conversion

- backends/LND.ts
v0.5.0 required users to enter in https:// or http:// before their host name in node settings. This PR removes that requirement and allows entry from either of the three formats.
> Fix host bug

- backends/LND.ts
- stores/SettingsStore.ts
- utils/AddressUtils.test.ts
- utils/AddressUtils.ts
- utils/LndConnectUtils.ts
- utils/handleAnything.ts
- views/SendingLightning.tsx
- views/Settings/AddEditNode.tsx
Relates to issue: [**ZEUS-452**](https://github.com/ZeusLN/zeus/issues/452)
BlueWallet QR code from Umbrel was incompatible with Zeus. Furthermore, connecting to an LNDHub instance over Tor wasn't possible unless you already had an existing account.
This PR also makes sure people connecting to .onion hosts can untoggle the `Enable Tor` button so they can continue to use Orbot if they so please.
* verify that `package.json` and `package-lock.json` have been …
> LNDHub: Tor support (Umbrel)

- utils/TorUtils.ts
> Bump Tor bootstrap timeout from 25 to 35s

- views/OpenChannel.tsx
Relates to issue: [**ZEUS-460**](https://github.com/ZeusLN/zeus/issues/460)
Fee options when opening channel for c-lightning-REST are `urgent`, `normal`, and `slow`. We must make this clear to the user. Future iterations will use a GUI component, such as radio buttons.
https://github.com/Ride-The-Lightning/c-lightning-REST/blob/master/docs/channelmgmt.md …
> c-lightning-REST: OpenChannel: make feerate options clear

- images/SVG/Channels.svg
Icon had grey fill fixed - modified to use the color assigned to it.
> Fix fill on Channels icon

- views/LnurlAuth.tsx
Relates to issue: **ZEUS-0550**
Fixes https://github.com/ZeusLN/zeus/issues/550
elliptic requires additional parameter `{canonical: true}` to ensure strict DER for the signed message required for lnurl-auth. If this is not set, in some cases the secp256k1 library would give `invalid signature` error.
> lnurl-auth signedmsg should be strict DER

- components/Amount.tsx
- components/text/Body.tsx
- utils/ThemeUtils.ts
- views/Activity/Activity.tsx
Relates to issue: Follow up to #509 
`Amount` component can now take a "color" prop in addition to the debit / credit options. Testing this out by putting it in the `Activity` view.
I changed up the underlying `AmountDisplay` component to just take a color and removed the debit / credit options from `Body` and just added a color prop to keep it more logic agnostic.
I'm also using the semantic "warning" / "success" color names instead of "red" / "green" because that seems to offer the most flexibility to future theme authors.
Speaking of colors, we don't have all of these colors for the non-Dark themes. What's a good solution to that? I also had an idea to create an enum for all the keys in the theme which we could to typecheck anyone using this `Amount` or `Body` component to make sure …
> Add color prop to Amount and use in Activity view

- components/Amount.tsx
- components/WalletHeader.tsx
- images/SVG/Clock.svg
- images/SVG/Node On.svg
- images/SVG/Wallet.svg
- views/UTXOs/UTXO.tsx
- views/Wallet/MainPane.tsx
- views/Wallet/Wallet.tsx
closes #560 
Sorry for the oversight on pending label before. I added the pending icon from the Figma... there doesn't really seem to be room for text like before.
Since I was playing with SVGs I took the chance to fix the wallet and node icons (they weren't filled quite right).
I didn't touch UTXO.tsx I guess it just got caught in in the prettier hype.
> add pending to Amount component and fix some SVGs

- stores/InvoicesStore.ts
- stores/SettingsStore.ts
- views/Receive.tsx
Relates to issue: [**ZEUS-596**](https://github.com/ZeusLN/zeus/issues/596)
It's bad practice to reuse on-chain addresses. Let's not facilitate this bad behavior.
> Don't save onchain addresses

- backends/CLightningREST.ts
- models/Payment.ts
- stores/PaymentsStore.ts
- views/Payment.tsx
Relates to issue: [**ZEUS-597**](https://github.com/ZeusLN/zeus/issues/597)
C-Lightning-REST was using a the endpoint that lists all individual routes as payments, causing user confusion.
> C-Lightning-REST: fix display of payments

- views/Send.tsx
Relates to issue: [**ZEUS-600**](https://github.com/ZeusLN/zeus/issues/600)
Keysend payments were always sending the amount specified denominated in sats
> ZEUS-600: Fix fiat conversion for keysend payments

- backends/LND.ts
LND has recently tightened up their API so you cannot include any extra fields. This was causing Open Channel operations to fail for LND users.
> LND: Fix Open Channel operation

- views/Settings/Nodes.tsx
We were previously displaying the implementation of the `Active` node for all saved nodes.
> Nodes: Fix implementation display

- components/Amount.tsx
- stores/FiatStore.ts
- stores/SettingsStore.ts
- stores/UnitsStore.ts
- views/Receive.tsx
- views/Send.tsx
- Nigerian Naira (NGN) 🇳🇬
- Argentine Peso (ARS) 🇦🇷
- Israeli New Shekel (ILS) 🇮🇱
> Fiat rate enhancements

- views/LnurlAuth.tsx
While refactoring things for Verify Message support, we added Base64 encoding for messages in LND in the backend definitions. This removes the need to Base64 encode in the LNURL-auth process.
Commit: https://github.com/ZeusLN/zeus/commit/97edc4bfbf1806d51b0f79777d3220f239b2e84d
Verify Message PR: https://github.com/ZeusLN/zeus/pull/649
* verify that dependencies are installed for both …
> LNURL-auth: don't base64 enc messages for LND twice

- backends/LND.ts
- components/FeeBreakdown.tsx
- components/SetFeesForm.tsx
- locales/en.json
- stores/FeeStore.ts
Relates to issue: [**ZEUS-705**](https://github.com/ZeusLN/zeus/issues/705)
- Lets LND users set Min and Max HTLC channel rates
- Properly display min HTLC in sats instead of msats
- Add `LoadingIndicator` and `SuccessErrorMessage` components to `SetFeesForm`
> LND: let users set Min and Max HTLC channel rates

- components/NodeIdenticon.tsx
Previously, node identicons would switch when using Lurker Mode
> Lurker Mode: made sure node identicons stay the same

- components/DropdownSetting.tsx
- components/TextInput.tsx
Text forms without placeholders on iOS were looking funky. Also rounded the corners on the `DropdownSetting` component on iOS
> Update TextInput padding

- views/Send.tsx
> Send: fix padding of transction type label

- views/Settings/AddEditNode.tsx
After the RN upgrade, color seems to vary from system to system so let's define it clearly
> Enforce modal warning text color

- android/app/src/main/AndroidManifest.xml
Consequence of updating the Android SDK during the React Native upgrade. See https://stackoverflow.com/a/67111267
> Fix support for web URLs on Android

- components/CollapsedQR.tsx
- components/CopyButton.tsx
- stores/TransactionsStore.ts
- utils/handleAnything.ts
- views/NodeQRScanner.tsx
- views/PaymentRequest.tsx
- views/SendingLightning.tsx
This PR allows users to specify amounts for zero amount invoices. We previously had functionality to set custom amounts for LND users when overpaying was allowed, but now let's just support zero amount invoices.
This PR also allows success screens to scroll when dealing with LNURL data.
> Zero amount invoices

- components/Button.tsx
- components/QRCodeScanner.tsx
Relates to issue: [**ZEUS-791**](https://github.com/ZeusLN/zeus/issues/791)
For use on the QR code scanner Cancel button.
> Button: add noUppercase prop

- stores/TransactionsStore.ts
Our Tor calls are not equipped to handle in-flight updates, so be sure to explicitly request we don't receive them.
> Tor: properly handle SendPaymentV2 call

- components/text/Body.tsx
- views/Wallet/MainPane.tsx
Main Pane should now take the main background style instead of the secondary color used for balance sliders.
This also makes jumbo amounts bold and fixes some spacing within the main pane.
> Update style of Main Pane

- utils/handleAnything.ts
- views/BTCPayConfigQRScanner.tsx
- views/NodeQRScanner.tsx
- views/Settings/AddEditNode.tsx
Relates to issue: [**ZEUS-819**](https://github.com/ZeusLN/zeus/issues/819)
> ZEUS-819: Flip the use tor switch on automatically when scanning tor url

- components/DropdownSetting.tsx
It was previously only styled properly for the default dark theme
> iOS: DropdownSetting: set bg color appropriately across themes

- README.md
An updated version of the RaspiBolt Zeus guide is now part of the main guide! (it was part of the bonus section before,). And the overall guide has also now its own domain name.
This PR updates the link path of the RaspiBolt entry in the `README.md`
PS: in the comment just above the list of installation guide, it is stated 
> On Android Zeus has support for connecting to you node entirely over the Tor network.
Is the "On Android" still relevant these days? or can Zeus be used over Tor on iOS as well?
> Update the link path for the RaspiBolt installation guide

- locales/en.json
- views/Send.tsx
Relates to issue: **[ZEUS-832](https://github.com/ZeusLN/zeus/issues/832)**
Previously, for LND 0.13 and 0.14 nodes, the keysend page would default to sending an amp payment. This could potentially cause issues, because amp payments will fail unless they're being sent to another LND 0.13 / 0.14 node with accept-amp turned on.
This change introduces an amp toggle for keysends. The toggle will only appear if the node supports amp (meaning it's an LND 0.13 / 0.14 node).
Screenshot when toggle is disabling amp payment:
Screenshot when toggle is enabling amp payment:
> Adding amp toggle for keysends

- stores/ChannelsStore.ts
- views/Channels/ChannelsPane.tsx
Relates to #874
Sequence of events causing this issue:
Open wallet > go to channels page > settings > back
When back is selected, `getChannels` method is called from several places (`getChannels` getting called multiple times is a more complicated issue that I'll log, but it's not actually causing the count to be wrong)
In the beginning of the `getChannels` method, `channels` is set to empty, so `channels.length` is set to zero. At the same time, `ChannelsPane` gets the number of channels from `this.props.ChannelsStore.channels.length`, so that's why it's displaying zero.
With this fix, we display `channels.length` after the call to `getChannels`, so we don't end up setting it to zero.
> Fix channels count in header

- locales/en.json
- views/Settings/AddEditNode.tsx
Relates to issue: **[226](https://github.com/ZeusLN/zeus/issues/226)**
Added copy node config button below delete node config. Brings user to a new Node Configuration page with all of the same properties, except for ' copy' added to the end of the Nickname. 
> Added copy node config button

- android/app/src/main/AndroidManifest.xml
- ios/zeus/AppDelegate.m
- ios/zeus/Info.plist
- utils/AddressUtils.ts
- utils/LinkingUtils.ts
- views/Wallet/Wallet.tsx
Relates to issue #888 
Adding the following for deep links:
1. Adding 'zeusln' scheme for deep links because iOS opens up the last installed wallet with the scheme 'lightning'.
2. There was a bug on iOS where deep links were not being handled, and it was only happening when Zeus was already running in the background. If Zeus is completely closed, an LNURL deep link works fine - it will open up the app and bring up the Send page. However, if Zeus was running in the background, the deep link would just open up the app to the Wallet page and do nothing. This is happening because iOS Zeus was not configured for deep links as specified [here](https://reactnative.dev/docs/linking). Also, once it was configured correctly, there was a bug where `handleOpenURL` calls `handleDeepLink`, but does not …
> Adding zeusln deep link and fixing iOS deep link handling

- stores/FeeStore.ts
- stores/SettingsStore.ts
Updates the default settings so that `Read Clipboard` and `Fetch rates from Mempool.space` are on by default. This update will preserve settings on existing installations.
> Update default settings

- backends/CLightningREST.ts
- components/Touchable.tsx
- models/OpenChannelRequest.ts
- views/Lockscreen.tsx
- views/OpenChannel.tsx
- views/Settings/AddEditNode.tsx
- views/Settings/Security.tsx
- views/Settings/SetDuressPin.tsx
- views/Settings/SetPin.tsx
Relates to issue: [**ZEUS-887**](https://github.com/ZeusLN/zeus/issues/887)
> c-lightning-REST: all channels were unannounced

- locales/en.json
- views/Wallet/Wallet.tsx
Previously you were able to:
If pin or password was set:
- Get to settings at start-up by tapping the settings button on the connecting screen
If pin was set:
- From the pinpad login view, get to settings by navigating back to the connecting screen and tapping the settings button
This PR:
- Ensures you cannot navigate back to the connecting screen from the pinpad login
- Creates a new 'Zeus is starting up' view without a Settings button, during which settings are loaded …
> Tighten up login process

- stores/BalanceStore.ts
Error in https://github.com/ZeusLN/zeus/pull/913/commits/7e30d265583f5e53366a61fcc468814d792c5abb sets the confirmed balance as the unconfirmed balance and does not return the confirmed balance at all.
https://github.com/ZeusLN/zeus/pull/913/files#diff-1b1ab925e436632e85604044e7813783665a20ad5664918a067c7d20dfafab92R89
> Unconfirmed balance hot fix

- components/Pin.tsx
- locales/en.json
- stores/SettingsStore.ts
- views/Lockscreen.tsx
- views/Settings/AddEditNode.tsx
- views/Settings/Currency.tsx
- views/Settings/Language.tsx
- views/Settings/Nodes.tsx
- views/Settings/Privacy.tsx
- views/Settings/Security.tsx
- views/Settings/SetDuressPin.tsx
- views/Settings/SetPin.tsx
- views/Settings/Theme.tsx
Adds toggle in Security settings to choose whether pin numbers should be scrambled.
Because all current users' pins are scrambled, made it so that default state is `scrambledPin = true`
Also changed the Security Settings view to use a class instead of a function in order to remain consistent with the rest of the views, and also to make it easier to inject `SettingsStore`. Without injecting `SettingsStore` I was running into bugs. …
> add scramble pin toggle

- components/FeeBreakdown.tsx
- models/Channel.ts
- views/Channels/Channel.tsx
Relates to issue: [**ZEUS-954**](https://github.com/ZeusLN/zeus/issues/954)
We should leverage the `initiator` bool value on the `ListChannels` call for this. First node returned from a chan policy call is not necessarily the initiator - nodes are returned lexicographically by pubkey. 
> ZEUS-954: [LND] Channel view: Initiating node label incorrect

- stores/ChannelsStore.ts
- views/OpenChannel.tsx
Screenshot of bug below. Changed so that we only set `spend_unconfirmed` true when `min_confs` is zero. Also changed the open channel screen to allow `min_confs` to be set to zero.
> Fix SpendUnconfirmed true with MinConfs > 0 bug

- stores/ActivityStore.ts
LNDHub doesn't support on-chain payments, so make sure it doesn't call the Transactions call when fetching activity.
> LNDHub: transactions call fix

- ios/zeus/Info.plist
This was already done in android but not for iOS
> Add missing `BITCOIN:` url scheme for iOS

- views/Wallet/MainPane.tsx
During the refactoring process for v0.6.0, we inadvertently caused a bug that caused the Tor icon to not display.
> Main pane: fix display of Tor onion

- views/Wallet/Wallet.tsx
Linking was only working when the app was closed. Users would lose the eventListener for linking events once they navigated away from the Home view.
> Linking fixes

- backends/LND.ts
Some locales use commas in place of decimals and this is reflected on systems' numeric keyboards. This PR handles those commas before passing them to the LND API.
> LND: handle commas when setting channel fees

- backends/CLightningREST.ts
- backends/Spark.ts
CLN interfaces were incorrectly setting expiry using time in seconds instead of UNIX timestamp (time since epoch)
> CLN: createInvoice: expiry fix

- utils/AddressUtils.test.ts
- utils/AddressUtils.ts
It seems that BlueWallet is connecting to `lndhub.io` by default and by looking at https://lndhub.io and https://lndhub.herokuapp.com it seems these two are using the same backend
Commit 5db5082 fixes a typo in variable name introduced by a464ab3
> Add lndhub.io as the first custodial lndhub

- README.md
The old link https://raspibolt.org/mobile-app.html returns 404. The PR fix the link.
> Fix link to 'Zeus over Tor guide for RaspiBolt'

- android/app/src/main/AndroidManifest.xml
Relates to issue: [**ZEUS-1046**](https://github.com/ZeusLN/zeus/issues/1046)
Existing config leads to Google Play prevented users without NFC from being able to download the app
> AndroidManifest.xml: Don't make NFC a requirement

- utils/UrlUtils.ts
Relates to issue: [**ZEUS-1051**](https://github.com/ZeusLN/zeus/issues/1051)
> Bug fix: Custom block explorer url force prefixed with https:/

- components/LayerBalances/LightningSwipeableRow.tsx
- components/LayerBalances/OnchainSwipeableRow.tsx
Relates to issue: None
Fix animation transition for middle action in both OnchainSwippeableRow and LightningSwippeableRow.
In fact, the middle button (if supported) had a different animation width compared to other, resulting in strange result.
Before:
[Before](https://user-images.githubusercontent.com/35492518/177412569-d08b90f0-1b4f-49df-b212-7be05d01b969.webm)
After:
[After](https://user-images.githubusercontent.com/35492518/177412595-447b74df-a793-4977-9e88-df37f2a4b7ca.webm)
Tested with Nexus 5 (emulated)
I have tested this PR with the following types of nodes (please specify node …
> Fix animation transition for middle action in SwippeableRow

- ios/zeus/AppDelegate.m
Wasn't able to build the app without this change, followed the instructions [here](https://github.com/facebook/react-native/issues/33451).
> Remove jsBundleURLForBundleRoot fallbackResource

- components/PinPad.tsx
- views/Lockscreen.tsx
- views/Settings/SetPin.tsx
Before screenshots on smaller screen (iPhone SE):
After screenshots on smaller screen (iPhone SE):
After screenshots on modern phone (iPhone 11 Pro):
> Style pinpad to avoid overlap on smaller screens

- ios/Podfile.lock
- views/Settings/Gods.tsx
- views/Settings/Mortals.tsx
- views/Settings/Olympians.tsx
Before (iPod Touch):
After (iPod Touch):
After (iPhone 11 Pro Max):
> Sponsors: fix display on iPod Touch

- README.md
This adds guidance to the docs to get around a conflicting peer dependency error when building from source
> README: npm i: add workaround to docs

- README.md
When adding a new node in dev, the `Host` field must be `10.0.2.2` or the node will fail to connect. Added a note about this in the README
> Add Android dev instruction

- components/SetFeesForm.tsx
Relates to issue: [**ZEUS-1072**](https://github.com/ZeusLN/zeus/issues/1072)
Timelock Delta is not changable via CLN's set fees API.
> SetFeesForm: only display Timelock Delta field for LND

- android/build.gradle
This PR fixes build issues on Android. Can't quite pinpoint it but believe a newer version of Kotlin was causing Gradle to behave differently. This could also be causing a reproducible build issue as seen in https://github.com/ZeusLN/zeus/issues/1117
This also applies a fix that uses a uniform version of React Native throughout the app.
* verify that dependencies are installed for both iOS …
> android/build.gradle: lock in Kotlin and RN versions

- locales/en.json
- stores/TransactionsStore.ts
- utils/FeeUtils.test.ts
- utils/FeeUtils.ts
- views/PaymentRequest.tsx
- views/SendingLightning.tsx
Builds directly on top of the branch in https://github.com/ZeusLN/zeus/pull/1101
Addresses issue #1106 with a piecemeal approach. Currently this build is stable and tested but is missing a few of the additional improvements that will be added in a separate PR. That PR will build directly on top of this branch as a base in case we want to merge this one as-is.
> - [x] make the field completely optional, ~leave it blank by default~, and attempt the payment with some dynamic fee limit that doesn't exceed X% of the payment amount (X = 100% for 1-1000 sats, X=5% if >1000 sats)
> - [ ] allow users to enter either a fixed sat limit OR a percentage of the payment
> - [x] leave a default value of 100 sat limit but use fee estimation to detect whether the fee will likely exceed 100 sats, and show …
> Fee Limit UX Improvements

- locales/en.json
- utils/ErrorUtils.test.ts
- utils/ErrorUtils.ts
Fixed problem in ErrorUtils when tor bootstrapping failed. Error message wasn't correctly mapping to user friendly message. Updated to include a new case for the *actual* message thrown. Left original message in there just to be sure no other cases use the original string.
- [ X] Bug fix
- [ X] I’ve run `npm run tsc` and made sure my code compiles correctly
- [ X] I’ve run `npm run lint` and made sure my code didn’t contain any problematic patterns
- [X ] I’ve run `npm run prettier` and made sure my code is formatted correctly
- [ X] I’ve run `npm run test` and made sure all of the tests pass
- [ X] Yes
I have tested this PR on the following platforms …
> fixed issue with error string mismatch in ErrorUtils

- views/Receive.tsx
- views/Wallet/DefaultPane.tsx
This PR adds a new button to the `DefaultPane` view. This icon, marked with a pencil will take you to the `Receive` view with the amount populated so you can change settings and add a memo. The Receive button on the `DefaultPane` view will now automatically generate an invoice for you when pressed. This takes one click away from invoice generation.
H/T @godsayshodl for the suggestion
* …
> DefaultPane: add ability to quickly generate invoice without memo

- components/PinPad.tsx
- components/TextInput.tsx
- views/Lockscreen.tsx
- views/Wallet/Wallet.tsx
This PR fixes numerous theme-specific styling issues:
- Pin pad buttons not showing up on light themes
- Dark theme styling appearing for `TextInput` components
- Style clashes on `Lockscreen` view
- `Wallet` Loading screen style reflects selected theme on node switching
> Theme color fixes

- views/Receive.tsx
Previously, the newly added `autoGenerateInvoice` function on the `Receive` view would always generate zero-amount invoices.
> views/Receive: autoGenerateInvoice: fix amount

- models/Payment.ts
- views/Payment.tsx
With this PR, the memo will now display on payment requests you havepaid
> Payment: display memos from payment requests you've paid

- backends/LNC/credentialStore.ts
This bug was causing some users to have their credentials overwritten and LNC connections lost. This change will make sure entries are written to storage is there is a local and remote key.
> LNC: credentialStore patch

- backends/LND.ts
- stores/SettingsStore.ts
- utils/RESTUtils.ts
Previously, account creation on LNDHub would fail if the currently selected node was not LND or LNDHub. This allows you to create an LNDHub account no matter what node you're currently using.
> LNDHub: account creation fix

- backends/LND.ts
- backends/LightningNodeConnect.ts
- stores/InvoicesStore.ts
This PR adds the ability for LND (REST + LNC) users to add msat invoices
> LND: add ability to create msat invoices

- backends/LightningNodeConnect.ts
- utils/RESTUtils.ts
- views/Settings/Nodes.tsx
Previously when using LNC you would hit a connection issue when switching away from your LNC connection to another node and then switching back.
This PR ensures that disconnect is called when switching away from an LNC connection.
> LNC: ensure that disconnect is called when switching nodes

- backends/LNC/credentialStore.ts
- backends/LightningNodeConnect.ts
- stores/SettingsStore.ts
There is a race condition between LNC's credential store load call and the initial connect call to your node. This would often result in iOS users unable to reconnect to their nodes using the local and remote keys
> LNC: race condition fix

- utils/handleAnything.ts
- views/LnurlPay/LnurlPay.tsx
- views/Send.tsx
At present the new default view keypad only passes amounts to send when paying to an onchain address or bolt11 invoice. This PR adds support to pass that amount to lnurl-pay payments (including payment to lightning addresses)
> Default View: Keypad: pass amount to lnurl-pay payment prompts

- backends/CLightningREST.ts
Relates to issue: **ZEUS-1112**
Fixed problem with full timestamp being set as expiry when it should just be number of seconds.
https://github.com/ZeusLN/zeus/issues/1112
> fixed issue with expiry in C-Lightning-REST being unix timestamp

- views/Receive.tsx
This ensure that the close invoice / invoice settings button does not show up in the header when a watched invoice is paid.
> Receive: hide settings/close button on invoice paid

- views/Settings/AddEditNode.tsx
Previously, node configs scanned from the general scan (on the home or default views) run through 'handleAnything` weren't properly setting indexes. This would cause the nodes to be improperly saved, or to take over the first saved node config in the nodes list.
This change gives context to the `AddEditNode` view of what the index should be when not coming in from the `Nodes` view. 
* verify that dependencies are installed for …
> AddEditNode: Bug fix: properly add connections from general scan

- components/Amount.tsx
- stores/SettingsStore.ts
This PR adds the ability to temporarily disable Lurker mode with a long press on amounts.
> Lurker mode: toggle off with long press on amounts

- views/Settings/Nodes.tsx
Bug where selected language is lost when switching between multiple node configurations
> fixed bug with locale being forgotten when switching between nodes

- components/Channels/ChannelItem.tsx
Lurker mode on the channels pane view now conceals channel counter-party aliases, sizes, and ratios.
> Channels: fix lurker mode display

- components/Amount.tsx
This PR adds a timer for the reveal functionality (hold on `Amount`) when in Lurker mode. Previously you had to keep holding to reveal the sensitive balance, which wouldn't be ideal as your thumb was often obfuscating the view of the value. Now there is a 3 second timer that gets triggered after revealing the value.
> Lurker mode: add timer for reveal toggle

- components/Conversion.tsx
- views/Wallet/MainPane.tsx
Early report from a Carman on the v0.7.0-beta1 release showed that the text color of the `Conversion` component while using iOS was incorrect. Furthermore, the display was a bit wonky when dealing with pending balances.
This PR
- Fixes color issues
- Condenses the `Conversion` components to a single line when dealing with a pending amount on the balance pane …
> Balance pane: fix display of Conversion component

- android/app/src/debug/AndroidManifest.xml
- android/app/src/main/AndroidManifest.xml
- components/KeyValue.tsx
This adds the ability for a value to by copied to the clipboard from a `KeyValue` component
> KeyValue: add ability to copy values to clipboard

- README.md
WIP here: https://github.com/ZeusLN/zeus/pull/1132
> README: update Spark -> Sparko, while we update compatibility

- models/Payment.ts
Relates to issue: [**ZEUS-1225**](https://github.com/ZeusLN/zeus/issues/1225)
CLN-REST was crashing when trying to pull up a made LN payment because `getMemo` was incorrectly passing in the payment request to be decoded.
> models/Payment: update getMemo call to decode computed payment request

- views/Settings/AddEditNode.tsx
Relates to issue: [**ZEUS-1214**](https://github.com/ZeusLN/zeus/issues/1214)
In this instance, the user would have a single node saved (LNC), go back to add a nickname to it, and lose their LNC session connection. This was because we would automatically set the node to be in reconnecting mode, and attempt to connect with LNC, without first disconnecting. …
> LNC: gracefully handle changes to nickname (reconnect flow)

- backends/LightningNodeConnect.ts
Relates to issue: [**ZEUS-1216**](https://github.com/ZeusLN/zeus/issues/1216)
Sign and verify messages calls were failing for LNC users as we were using the the updated endpoints on the `Signer` RPC service. REST uses the V1 calls on the `Lightning` RPC service, so let's switch to using that for now to remain consistent. Will evaluate need to more to new calls moving forward.
* verify that …
> LNC: use v1 endpoints for SignMessage + VerifyMessage

- utils/handleAnything.ts
- views/Send.tsx
There was an issue reading Bolt Cards / LUD-17 LNURL NFC where the first 2 characters from the URL were stripped.
This change should allow this format to work while still maintaining previously supported formats.
_Note: My NFC cards that I had on hand only supported a maximum of 140 bytes so I wasn't able to test with a bech32 encoded LNURL_ 
* verify that dependencies are installed for …
> Fixed issue with NFC reading LUD-17 cards

- android/app/build.gradle
- android/app/src/main/java/com/zeus/MainApplication.java
- android/settings.gradle
- ios/Podfile.lock
- ios/zeus.xcodeproj/project.pbxproj
- package.json
- stores/LnurlPayStore.ts
- stores/SettingsStore.ts
- views/Lockscreen.tsx
- views/Settings/Currency.tsx
- views/Settings/Language.tsx
- views/Settings/Nodes.tsx
- views/Settings/Privacy.tsx
- views/Settings/Security.tsx
- views/Settings/SetDuressPassword.tsx
- views/Settings/SetDuressPin.tsx
- views/Settings/SetPassword.tsx
- views/Settings/SetPin.tsx
- views/Settings/Theme.tsx
- yarn.lock
> storage: migrate to RN Encrypted Storage and add updateSettings func

- assets/images/SVG/Caret Down.svg
- components/DropdownSetting.tsx
- ios/zeus.xcodeproj/project.pbxproj
Some users cannot distinguish the node interface field on the node config page as a dropdown, so we've improved the styling of it on Android and iOS:
Android
iOS
> components/DropdownSetting: enhance styling

- locales/en.json
- views/IntroSplash.tsx
> views/IntroSplash: add Scan Node Config button

- views/PaymentRequest.tsx
This PR adds some enhancements to the new fee fields on the `PaymentRequest` view:
- Take custom amount (0-amt invoice) values into account when calculating amount for max fee percentage
- Updated styling
> views/PaymentRequest: new fee fields enhancements

- stores/InvoicesStore.ts
- views/Receive.tsx
Previously, all zero-amt invoices would return that the user received 0 sats upon payment. This PR ensures that the proper amount is displayed.
> Zero-amt invoices: fix amount received in payment notification

- locales/en.json
- views/Receive.tsx
Updated Receive screen to include NFC support. If an amount has been entered payment for  this amount will automatically be requested on scanning. If no amount has been entered the create invoice screen will be displayed.
> Receive via NFC

- backends/CLightningREST.ts
- backends/Eclair.ts
- backends/LND.ts
- backends/LightningNodeConnect.ts
- backends/LndHub.ts
- backends/Spark.ts
- utils/BackendUtils.ts
- utils/handleAnything.ts
- views/LnurlAuth.tsx
Relates to issue: **ZEUS-1045**
Added support for LNURL-auth for LNDHub backend with signature being `lndhub://user:pass` rather than typical message signing.
Also made a slight adjustment on the LnurlAuth view to center the domain inline with all other components.
> LNURL-auth support for LNDHub

- views/Receive.tsx
Previously, we were converting all onchain addresses to all caps to save on space in QRs. This PR assesses whether the address is case sensitive, and leaves it in its original format if it is (see Nested Segwit)
> Unified QRs: present case-sensitive onchain addresses in original format

- views/Settings/NodeConfiguration.tsx
When entering the node hostname, iOS was automatically capitalizing the first letter. For example, it wasn't possible to type "hostname" because it was switching to "Hostname".
> Prevent auto-capitalization of hostname on iOS

- stores/FeeStore.ts
Relates to issue: **ZEUS-1260**
Simple change in getForwardingHistory so it won't allow the same call to run while it is still loading previous request
> Bug fix: ZEUS-1260: routing fee totals being multiplied

- components/WalletHeader.tsx
- stores/FeeStore.ts
- utils/handleAnything.ts
- views/Send.tsx
Fixing issue where paste from clipboard would appear when regular URLs (or any other invalid data) was in the clipboard.
> Clipboard: handleAnything cleanup

- README.md
- build.sh
This PR:
- Updates `reactnativecommunity/react-native-android` from v5.4 to v7.0, which
Updates Node from v14 to v16
Updates Android NDK from v21.4.7075529 to v23.1.7779620
Updates cmake from v3.18.1 to v3.22.1
- Pins Docker image by SHA256 hash
- Replaces MD5 hashes with SHA256 hashes
> Reproducible builds: update Docker image, use SHA256 hashes

- views/LnurlPay/LnurlPay.tsx
Updated Confirm button colors on LNURL pay screen to match selected theme's colors. No more orange Confirm button for every theme!
Note: I tested this on all themes and looks good. Also fixes an issue on the Orange theme where the button couldn't be seen due to the default color of the button being the same as the background. …
> LNURL-pay: confirm button: use theme colors

- backends/CLightningREST.ts
- backends/Eclair.ts
- backends/LND.ts
- backends/LightningNodeConnect.ts
- backends/LndHub.ts
- backends/Spark.ts
- components/Channels/ChannelItem.tsx
- components/Channels/Tag.tsx
- models/ChannelClose.ts
- stores/ChannelsStore.ts
- utils/BackendUtils.ts
- views/Channels/ChannelsPane.tsx
Timer for force closed channels. Added supportsPendingChannels check to backends. Updated so pending/closed channel views only show for LND (REST/LNC) for now.
Note: this PR makes use of moment package however I haven't modified packages.json here as i think the package is already in use upstream. …
> Channels: force close channel timer display

- views/Settings/Security.tsx
show "require login after..." setting when FaceID enabled. Currently this will only show if pin/pass is also set.
> Security: Biometrics: show "require login after..." setting when FaceID enabled

- ios/Podfile.lock
- package.json
- yarn.lock
Change to resolve iOS build issue with react-native-qrcode-local-image used when selecting an image from photo library
> deps: use BlueWallet fork of react-native-qrcode-local-image

- locales/en.json
- stores/ChannelsStore.ts
- views/Channels/ChannelsPane.tsx
- views/Settings/Nodes.tsx
After viewing a closed channel and then going back to the list of channels the channel list is refreshed and sent back to the open channel view. This change maintains the current channel list view.
> Channels: maintain channelsType state between renders

- backends/LndHub.ts
Relates to issue: [**ZEUS-1145**](https://github.com/ZeusLN/zeus/issues/1145)
The `/getuserinvoices` endpoint on LNbits can't handle the `limit` url param and causes the call to fail. We had it set as `/getuserinvoices?limit=200`
> ZEUS-1145: LNBits: received payments aren't displayed in Activity view

- backends/LightningNodeConnect.ts
- package.json
- utils/BackendUtils.ts
- views/Wallet/Wallet.tsx
- yarn.lock
Lightning Terminal recently added support for custodial accounts via LNC. This PR adds perm checks for LNC connections to ensure that the proper features are displayed to the user.
*NOTE*: There are some caveats here that need to be addressed in Lightning Terminal:
The following checks for perms using the `hasPermissions` call throws true on the follow endpoints even though they should be throwing false:
- `lnrpc.Lightning.ListChannels`
- `walletrpc.WalletKit.ListAccounts`
- `lnrpc.Lightning.ForwardingHistory`
For now:
- In place of `lnrpc.Lightning.ListChannels`, `lnrpc.Lightning.OpenChannel` is used
- In place of `walletrpc.WalletKit.ListAccounts`, `walletrpc.WalletKit.ImportAccount` is used
There is no good workaround for `lnrpc.Lightning.ForwardingHistory`, as …
> LNC: add perm checks for custodial accounts

- views/Wallet/Wallet.tsx
Relates to issue: [**ZEUS-1336**](https://github.com/ZeusLN/zeus/issues/1336)
Previously, people would have issues tipping or zapping when LNC was selected as the default node as we would handle the initial deep link URL before fulling loading the node (in case of LNC, ensuring the `connect` call has completed and everything has initialized).
This change ensures that the initial URL is only handled after everything is initialized. …
> ZEUS-1336: Initial load: only handle initial URL after node is fully initiated

- stores/FeeStore.ts
- views/Routing/Routing.tsx
- views/Wallet/Wallet.tsx
This PR:
- Ensure forwarding history loads on initial load on the `Routing` view (regression here: https://github.com/ZeusLN/zeus/pull/1281)
- Remove all unnecessary forwarding history calls on the main `Wallet` view
> Routing: Forwarding history fixes

- stores/InvoicesStore.ts
LNURL-w functionality was broken when integrating BIP-21 / Unified invoices.
> stores/InvoicesStore: patch LNURL-w

- stores/ChannelsStore.ts
This caused `Sparko` interfaces to not be able to load.
> stores/ChannelsStore: only make calls to pending and closed channels if supported

- views/Settings/Privacy.tsx
This PR fixes a bug where the custom block explorer text field could only enter one character in at a time. The field saves to storage with each input. The page logic was causing the `LoadingIndicator` to flash in place of the page form on write to local storage.
> Settings/Privacy: fix input of custom block explorer

- views/Send.tsx
Auto-capitalization on the default `Send` view causes people manually entering in lightning addresses to get errors
> views/Send: disable auto capitalization on destination field

- components/WalletHeader.tsx
- views/Wallet/BalancePane.tsx
Relates to issue: [**ZEUS-1355**](https://github.com/ZeusLN/zeus/issues/1355)
This PR moves the Tor icon out from under the balances and conversion rate in the `BalancePane` and into the `WalletHeader`
> Tor icon: move out of BalancePane and into WalletHeader

- components/CollapsedQR.tsx
- views/Receive.tsx
Relates to issue: [**ZEUS-1359**](https://github.com/ZeusLN/zeus/issues/1359)
This simplifies the format of invoice values copied to clipboard on the `Receive` view. If an invoice does not have extra parameters like an amount or a memo, the clipboard value will be lowercased and not include the `bitcoin:` or `lightning:` prefix. QR codes all maintain their formatting as implemented with BIP-21/Unified addresses + capitalization for space saving purposes.
This is made possible with a new prop added to `CollapsedQR` called `copyValue` that allows the QR display value to different from the clipboard value.
I have tested this PR on the following platforms (please specify OS version and …
> Invoices: simplify copy format

- components/Amount.tsx
Puts the `LoadingIndicator` component in place of the `$N/A` previously displayed when the fiat exchange rates were loading.
> components/Amount: use LoadingIndicator component for fiat rate

- components/BlueWalletWarning.tsx
- components/LayerBalances/index.tsx
- components/SuccessErrorMessage.tsx
- locales/en.json
- stores/SettingsStore.ts
- views/Settings/NodeConfiguration.tsx
This fleshes out the `SuccessErrorMessage` component and adds a warning for BlueWallet LndHub users. More info here: https://bluewallet.io/sunsetting-lndhub/
This PR also handles failures on account creation and display users with error messages from the server.
> BlueWallet LndHub.io warning message

- views/Settings/InvoicesSettings.tsx
- views/Settings/PaymentsSettings.tsx
Relates to issue: [**ZEUS-1384**](https://github.com/ZeusLN/zeus/issues/1384)
Invoices and Payment settings would not get recorded on system swipe-back because the write to storage was only on the press of the back button. This PR changes the behavior to write to local storage after each change of the text field or toggle. The PR also removes the loading indicator from these two views to allow smooth entry of the text fields. …
> Settings: Invoices + Payments: fix swipe back bug

- components/Amount.tsx
- components/Channels/ChannelsHeader.tsx
- components/KeyValue.tsx
- stores/SettingsStore.ts
- views/Channels/ChannelsPane.tsx
Relates to issue: [**ZEUS-1341**](https://github.com/ZeusLN/zeus/issues/1341)
> Privacy: Lurker mode: fix toggle behavior

- components/Conversion.tsx
- locales/en.json
- stores/FiatStore.ts
- views/LnurlPay/LnurlPay.tsx
- views/OpenChannel.tsx
- views/PaymentRequest.tsx
- views/Send.tsx
- views/SendingLightning.tsx
Relates to issue: [**ZEUS-1354**](https://github.com/ZeusLN/zeus/issues/1354), [**ZEUS-1304**](https://github.com/ZeusLN/zeus/issues/1304)
This PR:
- Displays rate in sats when it's the unit selected [**ZEUS-1354**](https://github.com/ZeusLN/zeus/issues/1354)
- Fleshed out the conversion rates displayed on various views [**ZEUS-1304**](https://github.com/ZeusLN/zeus/issues/1304)
- Allows users to choose their units when opening a channel or paying a 0 amount lightning invoice …
> Conversion: display rate in sats when it's the unit selected

- ios/zeus/AppDelegate.m
This change ensures that persistent data on iOS is cleared out upon uninstall. See notes from `react-native-encrypted-storage` here: https://github.com/emeraldsanto/react-native-encrypted-storage#note-regarding-keychain-persistence
> iOS: clear Keychain data on uninstall (1/2)

- ios/zeus/AppDelegate.m
This change ensures that persistent data on iOS is cleared out upon uninstall. See notes from `react-native-encrypted-storage` here: https://github.com/emeraldsanto/react-native-encrypted-storage#note-regarding-keychain-persistence
[pt 1/2](https://github.com/ZeusLN/zeus/pull/1397)
> iOS: clear Keychain data on uninstall (2/2)

- views/Receive.tsx
Just a small typo - I was confused as of why the range is shown with double minus sign, so I replaced it with a single one.
> Receive: fix typo (show range with "a - b" instead of "a--b")

- locales/en.json
- stores/SettingsStore.ts
- stores/UnitsStore.ts
- utils/FeeUtils.test.ts
- utils/FeeUtils.ts
- views/Settings/Display.tsx
This PR adds the ability for a user to choose whether or not they want to see all 8 decimals when the unit selected is bitcoin. Originally we would default to showing only the required places.
Settings:
Disabled (original, default behavior):
Enabled:
> Settings: Display: Show all decimal places

- components/AmountInput.tsx
- components/Conversion.tsx
- views/LnurlPay/LnurlPay.tsx
- views/OpenChannel.tsx
- views/PaymentRequest.tsx
- views/Receive.tsx
- views/Send.tsx
This is a refactor featuring a new component `AmountInput` that allows a user to input an amount in the unit of their choosing. Appropriate conversions are displayed underneath the field.
> Component: Amount Input

- views/Channels/Channel.tsx
- views/Routing/SetFees.tsx
> SetFees: Use local value of timeLockDelta

- views/Channels/Channel.tsx
Users can see the channel point in the funding section on an active, opened channel. They can see the closed TX on a closed channel. However, prior to this PR, they were unable to see the channel ID or channel point on a pending channel.
> views/Channel: Pending channel: show channel point

- stores/BalanceStore.ts
- views/Wallet/Wallet.tsx
In [this commit](https://github.com/ZeusLN/zeus/commit/73b0beda77795d3afe6785d39f6d352c182802fa) we added a regression that caused balances for LNDHub accounts to only refresh on initial connection.
> Bug fix: LNDHub: allow balance refresh

- components/WalletHeader.tsx
- ios/zeus.xcodeproj/project.pbxproj
- models/Invoice.ts
- models/Transaction.ts
- stores/ActivityStore.ts
- stores/FiatStore.ts
- stores/PosStore.ts
- utils/DateTimeUtils.ts
- utils/ThemeUtils.ts
- views/Activity/Activity.tsx
- views/Receive.tsx
- views/Wallet/PosPane.tsx
On the POS orders list, items can now be slided to the left to expose a payment and delete button. The delete button will hide the order from the open orders list. This is useful for removing orders that customer were unable to pay. The payment button will take the server to the activity list (filtered only to received payments) to associate a made payment with an order.
* verify that dependencies …
> POS: add ability and associate existing payments with open orders and hide open orders

- components/Amount.tsx
- components/Conversion.tsx
- stores/FiatStore.ts
Relates to issue: **ZEUS-1453**
This fixes #1453. Additionally when loading fails N/A is now shown instead of also showing the loading indicator endlessly.
Also fixed an import in Conversion.tsc (not sure why this had no negative effect before).
- a lot of errors are found in node modules
> Fixed showing loading indicator for fiat amount endlessly

- backends/LndHub.ts
LNbits does not support on-chain receiving, so in our `LNDHub` backend definition, let's check for the LNBits url path `/lndhub/ext`, and if it matches the user's host, don't show the on-chain components in the UI.
> backends/LndHub: supportsOnchainReceiving: check for LNbits url

- stores/ModalStore.ts
- views/Wallet/Wallet.tsx
This fixes issues #1432, #1402, #1038
By handling back button press globally (in Wallet.tsx) back button now correctly removes screens from stack even if they were not opened from the default screen. Additionally modal dialogs can now be closed using back button.
> Fix Android back button issues

- stores/ModalStore.ts
- stores/SettingsStore.ts
- utils/BiometricUtils.ts
- views/Lockscreen.tsx
- views/Wallet/Wallet.tsx
This fixes #1279.
Before, when the setting "require login after app returns from background" was enabled, Zeus was always reconnecting to your node when you started the app. Even if the last app usage was seconds ago. This was because a restart of the app was forced when the app state changed to background. Now the loggedIn flag is just set to false instead.
Additionally pressing back button on lock screen now closes the app (before it was just reloading the lock screen). …
> Lock without reconnect

- backends/CLightningREST.ts
- backends/Spark.ts
- components/LayerBalances/index.tsx
- models/Channel.ts
This PR
- Fixed the regression from [this PR](https://github.com/ZeusLN/zeus/pull/1266) that didn't take multiple channels per peer into account
- Fixes msat channel fields that were broken in [CLN v23.05](https://github.com/ElementsProject/lightning/releases/tag/v23.05)
- Handles the CLN-rest bug that displays lightning balances with more than three decimal places, which we believe was introduced in [CLN-REST v0.10.3](https://github.com/Ride-The-Lightning/c-lightning-REST/releases/tag/v0.10.3)
> Core Lightning: display multiple channels per peer + update msat fields

- components/WalletHeader.tsx
- stores/SettingsStore.ts
- views/Lockscreen.tsx
- views/Wallet/Wallet.tsx
The commit 22a9c8c broke the setting "Require login after app returns from background" because it did not logout when the user was logged in. Not sure if this breaks FaceID again because I can't test it on iOS.
Also fixed an error when pressing back while on POS screen in certain situations.
Additionally removed some unnecessary `await`s.
* verify that dependencies are installed for both iOS and …
> Bug fix: locking when going to background

- build.sh
This keeps stdin open and allocates a pseudo-TTY.
> build.sh: make sure build process can be interrupted

- views/handleAnythingQRScanner.tsx
For example when scanning a node config from the Wallet header, the camera stays active after automatic navigation to the node config screen (the green dot in the notification bar stays visible).
Fixed this by calling `navigation.goBack()` before navigating to the new screen to close the QR code scanner. In case a node config was scanned from the node config screen, this problem did not occur because the navigation
automatically closed the QR scanner, probably because the navigation target was the second element on the navigation stack.
I have tested this PR with the following types of …
> Camera: prevent scanning in background

- models/Invoice.ts
This fixes #1290.
Model has to be a translated string to make the translations work and allow opening details.
Why are translated strings used for the model property? The distinction of the various activities should not be based on a translated string, I think.
> ZEUS-1290: Invoice details are not displayed if clicked on from Activity view

- locales/en.json
- views/Settings/NodeConfiguration.tsx
Currently, a node can be deleted by tapping the delete button once. To avoid unwanted deletion, confirmation is now required by changing the button text on the first tap to 'Tap to confirm' and actually deleting on the second tap.
> Node config: require confirmation to delete a node

- components/SetFeesForm.tsx
- views/Accounts/ImportAccount.tsx
- views/Channels/Channel.tsx
- views/EditFee.tsx
- views/Invoice.tsx
- views/LnurlPay/Metadata.tsx
- views/Lockscreen.tsx
- views/NodeInfo.tsx
- views/OpenChannel.tsx
- views/Order.tsx
- views/Payment.tsx
- views/PaymentPaths.tsx
- views/PaymentRequest.tsx
- views/Receive.tsx
- views/Routing/RoutingEvent.tsx
- views/Send.tsx
- views/SendingLightning.tsx
- views/SendingOnChain.tsx
- views/Settings/CertInstallInstructions.tsx
- views/Settings/Display.tsx
- views/Settings/NodeConfiguration.tsx
- views/Settings/PointOfSale.tsx
- views/Settings/PointOfSaleReconExport.tsx
- views/Settings/Privacy.tsx
- views/Settings/Security.tsx
- views/Settings/Settings.tsx
- views/Settings/SignVerifyMessage.tsx
- views/Transaction.tsx
- views/UTXOs/UTXO.tsx
This fixes #1478 by setting `keyboardShouldPersistTaps='handled'` for all ScrollViews. This allows buttons to handle the press event while a TextInput has focus. Clicking somewhere else outside the TextInput still closes the keyboard (this would not work with `always`). Set this for all ScrollViews, even if they do not contain TextInputs or Buttons because this might change in the future.
* verify …
> Fix button press when keyboard is open

- components/LayerBalances/LightningSwipeableRow.tsx
- components/LayerBalances/OnchainSwipeableRow.tsx
This fixes #1500 by reducing horizontal padding of the button texts. Also removed bottom padding so it is now vertically aligned.
> Improved balance view buttons spacing

- views/NodeInfo.tsx
The row 'Synced to chain' was not displayed at all if not synced to chain.
> Node Info: show 'Synced to chain' = False if not synced

- components/Button.tsx
- components/Header.tsx
- components/TextInput.tsx
- views/AddNotes.tsx
This fixes #1482 by using the Zeus TextInput component instead of the one of react-native.
> AddNotes: improved layout and colors

- views/PaymentRequest.tsx
This fixes #1304 by showing the fiat rate (if enabled in settings) on lightning payment request screen.
After some thoughts I think the conversion is not needed for historical transactions (Activity screen).
Screenshot:
> Payment request: Show fiat conversion below main amount

- ios/Podfile.lock
- package.json
- views/Wallet/Wallet.tsx
- yarn.lock
Relates to issue: [**ZEUS-1463**](https://github.com/ZeusLN/zeus/issues/1463)
This PR removes dependency `react-native-restart`, which we were using to allow users to restart the app when they were facing connection issues.
The library was contributing to an issue where iOS users had their settings cleared out due to a race condition. We also maintain the restart functionality by clearing the stores, resetting the node connection status, and making all the required calls again. …
> deps: remove `react-native-restart`

- stores/SettingsStore.ts
This fixes fiat currency display being enabled on fresh install. Was introduced by #1466.
> Disable fiat currency display for fresh install

- backends/EmbeddedLND.ts
- lndmobile/wallet.ts
Wire up `signMessage` and `verifyMessage` in *EmbeddedLnd.tsx*
> [Pegasus] Backend: Wiring up signMessage and verifyMessage

- stores/SettingsStore.ts
- views/Receive.tsx
The default addresses format for LND instances was set to nested Segwit instead of native Segwit. Native Segwit provides smaller transactions sizes and cheaper fees.
Still trying to pintpoint where the regression happened.
> Bug fix: change default address format from np2wkh to p2wkh

- backends/Eclair.ts
- backends/LND.ts
- backends/Spark.ts
- stores/NodeInfoStore.ts
- stores/SettingsStore.ts
- utils/BackendUtils.ts
This fixes #1492 and fixes #1479.
#1479 was caused by cached backend calls being used although the node config was changed. So the calls are now removed when reconnecting to a node.
#1492 was due to results of older requests being received and processed after the results of newer requests. Now, results of non-latest requests are generally discarded.
* verify that dependencies are installed for both …
> Fix node connection issues

- components/Sats.tsx
- stores/FiatStore.ts
- stores/UnitsStore.ts
> Revert "Round sat amounts to 3 decimals"

- views/Wallet/BalancePane.tsx
Relates to issue: [**ZEUS-1549**](https://github.com/ZeusLN/zeus/issues/1549)
There is a bug in c-lightning-REST that causes the backend to return more than 3 decimal places (msat) in returned balances. This PR ensures that at most 3 decimal places are shown. If a balance is only whole numbers, no decimal places will be shown.
This was covered already in same changes to the balance slider code but not in the combined balance
BEFORE
AFTER
* verify that `package.json` …
> ZEUS-1549: limit combined balance to 3 decimals

- stores/FiatStore.ts
Fixed the display of the fiat conversion rates, when unit is set to sats
BEFORE
AFTER
> Fiat currency conversion: Moscow time

- stores/SettingsStore.ts
- utils/LocaleUtils.ts
- views/Settings/Language.tsx
Changed the keys of LOCALE_KEYS to ISO 639-1 to be able to use it as language for libs like humanize-duration.
> Settings: change locale keys to ISO 639-1

- components/CollapsedQR.tsx
- components/Touchable.tsx
- views/Receive.tsx
The value of the QR code generated on Receive screen is sometimes quite long. To save some space (and avoid unnecessary need for scrolling) the value is now truncated if longer then 3 lines. It can be expanded by clicking on it.
Truncated:
Expanded:
> Receive: truncate long QR code values

- stores/ChannelsStore.ts
Switching between nodes would fail to clear out and reset pending and closed channel data.
> Bug fix: ChannelsStore: reset: clear out all channels data

- models/Invoice.ts
This fixes the display of expiry time for invoices in LNDHub when the expiry is returned as a UNIX timestamp
Before:
After:
> LNDHub: fix display of expiry time, hash, preimage

- package.json
- views/Wallet/Wallet.tsx
- yarn.lock
This fixes #1567 by using RNRestart again, but only on Android.
> Use RNRestart on Android

- android/app/build.gradle
- android/build.gradle
Updated Android libraries, migrated to androidx, removed support library, updated Kotlin.
Might be a good idea to test with Android 9 to be sure that the support library is really not needed anymore.
Version 3.24.1 of protoc is newer than 21.0-rc-1... (see here: https://protobuf.dev/support/version-support/)
> Updated Android libraries

- views/ContactDetails.tsx
- views/Settings/AddContact.tsx
- views/Settings/Contacts.tsx
- Fixing the size of Header icons, mainly the **Back** button on the `AddContact,` `Contacts` and `ContactDetails` view.
- Disabling the `SAVE CONTACT` button if an extra field of pubkey is generated and not being filled correctly.
- On `AddContact`Previously we had to tap on the plus icon to open the gallery for adding photos, we changed that to make the whole background circle pressable.
- If the contact has only one address available (either lnAddress, onchainAddress, or pubkey) , we get forwarded to the payments and skip going to `ContactDetails` view only if the user is coming from the `Send` view (we still will be forwarded to the `ContactDetails` view if we coming from `Settings` so the user can edit the contact).
> Contacts: Fixes

- stores/InvoicesStore.ts
- views/LnurlPay/LnurlPay.tsx
Relates to issue: [ lnurl / luds #234: LNURL-pay: Drop metadata description hash validation](https://github.com/lnurl/luds/pull/234)
See attached issue.
> LNURL-pay: Drop metadata description hash validation

- backends/Eclair.ts
- backends/LND.ts
- backends/LightningNodeConnect.ts
- components/NodeIdenticon.tsx
- models/Invoice.ts
- stores/FeeStore.ts
- utils/Base64Utils.test.ts
- utils/Base64Utils.ts
- utils/ConnectionFormatUtils.ts
This fixes #1477.
The method currently used to encode strings to base64 (btoa) does not accept multi-byte utf8 characters because it is meant to be used for encoding binary data. Changed this to Buffer.toString('base64') which works with all utf8 strings.
> Sign/Verify message: fix signing with special characters

- views/Settings/SetPin.tsx
Even when "Scramble PIN numbers" is disabled, the related hint was displayed on confirm PIN screen.
> Remove scramble pin hint on confirmation screen

- components/AmountInput.tsx
- stores/UnitsStore.ts
The unit switcher icon was showing dollar when fiat was enabled and the current unit was sats (next unit is Bitcoin so it should show Bitcoin).
Before:
After:
> AmountInput: unit switcher: fix icon displayed

- components/WalletHeader.tsx
Instead of navigating to Send component and let it handle the clipboard value, handle it the same way the QR code handler does it. One advantage is that clipboard values that cannot be handled by the Send component can still be handled without changes to the handling code in WalletHeader.
> Refactor: clipboard handling

- views/SendingLightning.tsx
- views/Wallet/Wallet.tsx
This fixes #1511.
When transaction is successfully sent or is in transit, back press now navigates to Wallet.
Additionally improved back press subscription removal in Wallet.
> Improve back press handling in SendingLightning

- stores/SettingsStore.ts
- utils/LndMobileUtils.ts
This PR makes some changes to the default Neutrino config for embedded nodes.
First, mainnet nodes are limited to known BTCD instances. BTCD seems to handle broadcasting+fee bumping better as the mempool size is uncapped by default and generally plays nicer with LND as it is also written in Go.
Our new BTCD instance `btcd2.lnolymp.us` has been added along with `node.eldamar.icu`. Bitcoin Core instances `node.lnolymp.us` and `node.blixtwallet.com` have been removed (at least for the time being). `btcd.lnolymp.us` has taken the new hostname `btcd1.lnolymp.us`.
Secondly, the Neutrino setting `dontAllowOtherPeers` has been set to `true` by default. This will ensure that Zeus doesn't connect to any Bitcoin Core peers that may cause problems.
If you …
> Embedded node: Neutrino config changes

- components/Conversion.tsx
This fixes #1694 by disabling the Conversion component while fiat rates are being loaded. So this loading indicator can no longer be clicked:
> Prevent enabling fiat rates display while loading

- locales/en.json
- stores/LSPStore.ts
- stores/SettingsStore.ts
- views/Settings/LSP.tsx
Users will now be able to request Simple Taproot Channels from their 0-conf chan LSPs. A toggle for the option is now added to `Settings` > `LSP`.
The functionality is already deployed to our LSP, OLYMPUS by ZEUS.
> LSP: add ability to request Simple Taproot Channels

- stores/SyncStore.ts
- utils/LndMobileUtils.ts
- utils/SleepUtils.ts
- views/PaymentRequest.tsx
The sleep method used busy waiting which is unnecessarily utilizing CPU. Now using setTimeout instead.
> Improve sleep

- views/IntroSplash.tsx
This fixes #1703. Pressing back now exits the app except while wallet is creating.
> Exit app on back press on IntroSplash

- views/Settings/NodeConfiguration.tsx
Right now `implementation` defaults to `lnd` if `!embeddedLndNetwork`. This leads to this issue: If an embedded node exists and you edit an existing CLN node, the node interface was wrongly displayed as `LND (REST)`.
Now `implementation` only defaults to `lnd` if `!embeddedLndNetwork && newEntry`.
> Node Configuration: Default implementation to lnd only if newEntry

- components/SuccessErrorMessage.tsx
- package.json
- yarn.lock
- Updating react-native-elements 3.4.2 -> 3.4.3
- Making "link" and "mainStyle" optional in SuccessErrorMessage.tsx
-> This fixes all TypeScript type errors for: `Icon`, `ListItem`, `SuccessMessage/WarningMessage/ErrorMessage`
> React-native-elements update, "link" and "mainStyle" optional in SuccessErrorMessage.tsx

- views/Send.tsx
Fixes: #1731 
This PR addresses a bug where the `isValid` state was not being reset to true when a correct value of address was entered after an error.
> Send: Fix - Reset isValid state during input validation

- components/SetFeesForm.tsx
- stores/ChannelsStore.ts
- views/Channels/Channel.tsx
- views/Routing/RoutingEvent.tsx
- views/Routing/SetFees.tsx
This finally fixes #420.
Additionally renamed ChannelsStore.getChannelInfo function to loadChannelInfo since it does not return a value and get functions usually do.
Now displaying loading indicator instead of button:
And displaying result message below button:
> Edit channel fees: fix showing feedback after fees have been set

- .github/ISSUE_TEMPLATE/enhancement.yml
I think it is helpful to have a 3rd template for github issues. Beware the label `Enhancement` doesn't exist yet and needs to be created first.
> New GitHub issue template for enhancement

- android/app/src/main/java/com/zeus/MainApplication.java
- package.json
- stores/ChannelsStore.ts
- views/Channels/ChannelsPane.tsx
- yarn.lock
Currently, when creating a new channel for a known node, the node has no alias (pub key is displayed instead).
> Channels: fix loading aliases for new channels of known nodes

- components/Button.tsx
- components/OnchainFeeInput.tsx
- views/Channels/Channel.tsx
- views/EditFee.tsx
This improves the layout and colors of the close channel and corresponding fee selection dialogs. Currently it is not recognizable that additional elements appear when close channel is pressed. This is resolved by adding a margin below the button so that when scrolled to the bottom and pressing the button, the additional elements are partly visible.
Before:
After: …
> Improved layout of close channel and fee selection

- views/Settings/Nodes.tsx
> Prevent calling refreshSettings twice when nodes screen is opened

- .gitignore
- fetch-libraries.sh
Currently, the fetch-libraries postinstall script always downloads the lib files, even if the current versions are already present. Now the hash of the already present files are checked and only downloaded if missing or changed. The iOS zip file is now kept for making the check possible.
> Improve fetch-libraries script

- backends/CLightningREST.ts
Relates to issue: [**ZEUS-1772**](#1772)
Fixes bug where addresses do not get generated with new versions of c-lightning-REST. Address type selection not added as P2TR/Native Segwit selection is determined by your node config.
> ZEUS-1772: Core Lightning REST: On-chain Receive does not show address

- backends/CLightningREST.ts
- backends/Eclair.ts
- backends/EmbeddedLND.ts
- backends/LND.ts
- backends/LightningNodeConnect.ts
- backends/LndHub.ts
- backends/Spark.ts
- utils/BackendUtils.ts
- views/OpenChannel.tsx
This PR adds a new `supportsChannelCoinControl` check to the backends. Changes here will allow LND v0.16.4 and lower users to continue using the app, and open channels, even when their instances have strict API param checking.
> Backends: add supportsChannelCoinControl check

- components/ModalBox.tsx
Relates to issue: [**ZEUS-1686**](https://github.com/ZeusLN/zeus/issues/1686)
This was causing the address type picker to be cut off when using higher than default font size settings on Android.
> ZEUS-1686: ModalBox: take fontScale into account when setting height

- views/Settings/Seed.tsx
This PR takes the seed phrase on the Back up wallet view, lays it out in columns instead of rows, and centers it all.
Columns is the far more common layout that I've seen across hardware wallets and seed plates.
iPhone 15 Pro Max - Before
iPhone 15 Pro Max - After
iPhone SE (3rd generation) - Before
iPhone SE (3rd generation) - After
iPad Pro (12.9-inch) (6th generation) - Before
iPad Pro (12.9-inch) (6th generation) - After
* verify that `package.json` and `yarn.lock` …
> Back up wallet: order seed phrase in columns and center

- views/Settings/LightningAddress/NostrRelays.tsx
When deleting a ZEUS PAY Nostr relay, the client does not submit an updated `relays_sig`. This can lead to invalid Zaplocker checks on the payment request view.
> [Bug fix] Lightning Address Settings: Nostr relays: update relays_sig on relay deletion

- views/SendingLightning.tsx
- views/Wallet/Wallet.tsx
Discovered by mix:
This bug occurs when you've previously paid a Zaplocker payment (in transit) then make a successful payment.
This was caused by two things:
- Zaplocker error still being rendered on the view, despite payment success
- LnurlPay reset call being called on the `refresh` function of the main wallet view, instead of the `fetchData` call
* verify that dependencies are installed for …
> [Bug fix] Sending Lightning: fix wrong display of Zaplocker warning

- components/WalletHeader.tsx
This fixes #1607.
Before, you could not know there are pending channels:
Now:
Different theme:
> Channels pane: Added clock icon to Button in WalletHeader in case there are pending channels

- views/Settings/Seed.tsx
On some devices, the seed phrase would continue on to a third column. This was because a fixed `maxHeight` was determining where the columns were split - which can vary based on resolution density.
This fix explicitly defines two columns 1-12, and 13-24 of the seed phrase and adjusts some margins.
Before:
After: 
iPad check: …
> [Display bug] Seed: explicitly create two columns

- views/Settings/SetDuressPassword.tsx
- views/Settings/SetPassword.tsx
- Added Tap-to-confirm logic for deleting passphrase and deleting duress passphrase
- Using themeColor instead of red
I cannot see any effect for this: `containerStyle={{ borderColor: themeColor('delete') }}`
-> so I deleted it.
> Tap-to-confirm logic for deleting passphrase / themeColor instead of red

- views/AddNotes.tsx
We were getting the dark background in light themes as well, so I made the background transparent for all themes.
Before:
After:
> AddNotes: Transparent background in all themes

- views/Send.tsx
This relates to issue: #1811 
_We added a `Proceed` button on the Send screen, so we will have to tap it to confirm before going with the entered address_
> Send: Confirm before proceeding to the address

- assets/images/SVG/Clock.svg
- components/Amount.tsx
This fixes #1774.
- fixed alignment of several elements (pending icon, sats, FIAT icon, BTC icon)
- fixed slightly cut off BTC icon
- removed empty space in Clock.svg
Before:
After:
> Fixes alignments and RTL layout in Amount.tsx

- views/Settings/Language.tsx
This fixes #1790. This was caused because the language value (e. g. English) instead of the key (e. g. en) was saved and then migrated to the key.
> Save language key instead of value in settings

- locales/en.json
- stores/SettingsStore.ts
- views/Settings/LSP.tsx
This PR adds a reset button to the LSP settings page when the default settings are changed. This is particularly helpful for users who change their default LSP and want to change back to the defaults.
With no settings changed:
With settings changed:
> LSP Settings: add reset button

- locales/en.json
- stores/ActivityStore.ts
- utils/ActivityFilterUtils.ts
- views/Activity/ActivityFilter.tsx
This PR adds a settings in `Activity filter` for in transit payments. It is off by default so users will need to opt in to see them.
> Activity Filter: In transit payments

- views/SendingLightning.tsx
- views/SendingOnChain.tsx
As discussed with @kaloudis, Wordmark logo is now a bit bigger.
> SendingLightning/SendingOnChain: Slightly bigger Wordmark logo

- assets/images/SVG/DynamicSVG/LightningSvg.tsx
- assets/images/SVG/DynamicSVG/OnChainSvg.tsx
- views/Receive.tsx
Different width and height is needed for the icons in swipeable row and on receive screen, so it is dynamic now.
Before:
After:
> Make LightningSvg and OnChainSvg components dynamic with width and height props

- locales/en.json
- views/PaymentRequest.tsx
Currently, the Zaplocker warning will only show when paying someone's lightning address from within the app (the `user_pubkey` property is used on the payment endpoint, although perhaps we should switch over to `hodl_invoice`).
This change will allow the warning to be displayed even if the payment request is loaded by a user's Nostr client.
* verify that dependencies are installed for both iOS and …
> Extend Zaplocker warning to zaps

- components/PaidIndicator.tsx
Since new Zeus logo led to bad contrast, color is now themeColor('text') which has good contrast.
Before:
After:
> PaidIndicator: changed color for better contrast

- views/Receive.tsx
Before, Zeus was displaying a button "COPY ADDRESS" for a lightning invoice when amount was below dustlimit leading to lightning only (no unified and on-chain options).
Now it displays "COPY INVOICE":
> Receive: copy invoice button instead of copy address when receiving dust

- locales/en.json
- views/Settings/NodeConfiguration.tsx
Adds an additional restore warning to the Node Configuration view for Embedded LND nodes.
> Embedded node: add additional restore warning

- components/CollapsedQR.tsx
Due to scanning issues caused by several factors (overall QR size, small quietZone, low contrast because of new theme colors) this adds ability to tap on the QR to enlarge it to fullscreen. It will also use black/white colors and increase quietZone. To go back to normal mode you can tap anywhere.
QuietZone is now relative to screensize (before it was relatively smaller for bigger screens) and normal size of QR (before tapping) is now slightly smaller.
**Before:**
Phone:
Tablet:
**After:**
Phone:
Tablet:
This will also fix #1604.
I have tested this PR with the following types of nodes …
> CollapsedQR: Tap to enlarge QR

- locales/en.json
- stores/SettingsStore.ts
- views/PaymentRequest.tsx
- views/Settings/PaymentsSettings.tsx
This PR makes two changes to how fee limits for LN payments work in ZEUS:
1. The default values are changed:
- Fee limit fixed: 100 sats -> 1000 sats
- Fee limit percentage: 0.5% -> 5%
- Fee limit method setting is effectively removed
2. The default fee limit method logic has been changed.
**Previously**: the method (percentage or fixed) would be chosen based on what the user had in their settings (default: fixed) - regardless of the payment size.
**Now**: Fee limit method will default to fixed for amounts up to 1000 sats and percentage for amounts greater than 1000 sats. You'll be able to change which method and values to use though, under the Settings section of the Payment Request view.
New explainer has been added to the Payment settings view:
If …
> New fee limit defaults and behavior

- components/Screen.tsx
- components/WalletHeader.tsx
- views/LnurlPay/Success.tsx
- views/SendingLightning.tsx
- views/SendingOnChain.tsx
- views/Settings/Contacts.tsx
- views/Settings/PointOfSale.tsx
- views/Settings/Security.tsx
- views/Settings/SocialMedia.tsx
Some minor improvements:
- Fixed typescript compile errors
- Fixed activity button color in PosPane
- Fixed font family
- Fixed react-native error by disabling scrolling of flat lists: `VirtualizedLists should never be nested inside plain ScrollViews with the same orientation because it can break windowing and other functionality - use another VirtualizedList-backed container instead.`
* verify …
> Several minor improvements

- .github/PULL_REQUEST_TEMPLATE.md
- .github/workflows/lint.yml
- .github/workflows/prettier.yml
- .github/workflows/test.yml
- README.md
- check-styles.test.ts
- components/CollapsedQR.tsx
- package.json
- views/Channels/Channel.tsx
- views/ContactDetails.tsx
- views/EditFee.tsx
- views/LnurlPay/Success.tsx
- views/Routing/RoutingHeader.tsx
- views/Settings/AddContact.tsx
- views/Settings/LightningAddress/ChangeAddress.tsx
- views/Settings/LightningAddress/NostrKeys.tsx
- views/Settings/LightningAddress/index.tsx
This fixes #1659 by moving themeColor() calls from static style objects to render methods.
Remove color from RoutingHeader completely as it has no effect.
> Fix updating colors on theme change

- stores/ChannelsStore.ts
`isLightningReadyToReceive` did not wait for channel load because `getChannels` did not return a promise. So no active channel was found because `getChannel` removes all channels before reloading them.
> Fix channels screen reload loop

- views/Settings/NodeConfiguration.tsx
When creating a new Core Lightning node, the placeholder for the host is just `localhost` although currently, the protocol must be entered too (like `https://localhost`). Now it defaults to https by adding it automatically to the host name.
> Node Config: update comments for params used by c-lightning-REST

- views/OpenChannel.tsx
This PR disables and untoggles the Announce option on the Open Channel view, when Simple Taproot Channel is toggled. Simple Taproot Channels are currently only supported with unannounced channels.
> Open Channel: toggle off and disable Announce when Taproot Channel toggled

- stores/ChannelsStore.ts
Relates to issue: [**ZEUS-1898**](https://github.com/ZeusLN/zeus/issues/1898)
Bug was getting triggered by `sorted` being undefined. I believe the sort does more cycles ever since we refactored the channels code.
> ZEUS-1898: Fix crash on sort by channel close height

- locales/en.json
- views/Settings/LightningAddress/index.tsx
Relates to issue: [**ZEUS-1901**](https://github.com/ZeusLN/zeus/issues/1901)
> ZEUS PAY explainer: remove language about LSP if backend doesn't support it

- components/AmountInput.tsx
- stores/UnitsStore.ts
- utils/AddressUtils.test.ts
- utils/handleAnything.ts
- views/LnurlPay/LnurlPay.tsx
- views/Send.tsx
- views/Wallet/KeypadPane.tsx
Relates to issues: [**ZEUS-1417**](https://github.com/ZeusLN/zeus/issues/1417), **ZEUS-1580**, **ZEUS-1527**, **ZEUS-1871**
The primary purpose of this PR is to ensure that chosen units persist across app restarts. This is particularly helpful for shops that ring up sales based in fiat currencies.
This PR also makes a change to `AmountInput` that ensures that the units are not reset when a generated invoice is cleared (hitting the X button).
As a result, I believe [ZEUS-1580](https://github.com/ZeusLN/zeus/issues/1580) is now resolved.
I've also ensured that [ZEUS-1527](https://github.com/ZeusLN/zeus/issues/1527) and [ZEUS-1871](https://github.com/ZeusLN/zeus/issues/1871) remain corrected.
If you modified or added a utility file, did you add new unit …
> Persist chosen units across app restarts

- models/Transaction.ts
If amount is 0 and fee is not (e. g. channel operation tx), fee percentage is shown as "Infitity%":
Now, the percentage is hidden if amount is 0.
> Transaction details: do not show fee percentage if amount is 0

- components/WalletHeader.tsx
- locales/en.json
Also re-added missing locale string.
Before:
After:
> Improve wallet header layout

- views/ContactDetails.tsx
Slightly decreased the font-size of name from `ContactDetails` view from **44** to **40**
Before:
After:
> ContactDetails: Decrease font-size of name

- models/Contact.ts
- utils/ContactUtils.ts
- views/ContactDetails.tsx
- views/Send.tsx
- views/Settings/AddContact.tsx
- views/Settings/Contacts.tsx
This addresses an issue with Contacts images on iOS. With iOS design, the `DocumentDirectoryPath` changes with each update. This would cause our saved images to break upon update.
Related issue: https://github.com/itinance/react-native-fs/issues/528
This PR ensures that images persist across app updates.
> RNFS: account for changing DocumentDirectoryPath

- components/KeyValue.tsx
- views/Order.tsx
Currently the order view in the POS only displays the single unit price for each item, even if there are multiple of the same item listed on an order.
This PR clearly displays the total and single unit values of each item on the bill.
Before:
After:
> POS: Order: clearly display per unit + total values

- locales/en.json
- models/Payment.ts
- views/Channels/Channel.tsx
- views/Payment.tsx
This PR adds the payee destination pubkey to the Payment view.
Before:
After:
> Activity: Payment: include destination

- models/Payment.ts
- stores/TransactionsStore.ts
- views/SendingLightning.tsx
When completing a payment, display the payment preimage instead of the payment hash, if possible. The preimage has some caveats in being used as a receipt but functions better than the payment hash.
Before:
After:
> Sending Lightning: Success: display preimage

- views/Activity/Activity.tsx
- views/Activity/ActivityFilter.tsx
- views/UTXOs/CoinControl.tsx
Most screens use the Back icon to go back/close the current view. Now also using this icon for the three remaining screens (Activity, ActivityFilter, CoinControl).
> Harmonize back/close icons

- components/DropdownSetting.tsx
- locales/en.json
- stores/SettingsStore.ts
- views/Receive.tsx
- views/Settings/InvoicesSettings.tsx
Adds 10 minute, 1 hour, 1 day, 1 week presets for the expiration time field and a dropdown field for the units. Dropdown also included on the Invoice settings view
https://github.com/ZeusLN/zeus/assets/1878621/730d04eb-863b-4ce0-a3db-939d6637df16
> Receive: add preset buttons for expiration time

- utils/LndMobileUtils.ts
```; A period to wait before for closing channels with outgoing htlcs that have
; timed out and are a result of this nodes initiated payments. In addition to
; our current block based deadline, if specified this grace period will also be
; taken into account. Valid time units are {s, m, h}.
; Default:
;   payments-expiration-grace-period=0s
; Example:
;   payments-expiration-grace-period=30s
```
Set to 336h, or two weeks.
> Embedded LND: conf: payments-expiration-grace-period

- utils/LndMobileUtils.ts
Halve the maximum force close fee rate set by clients. Still at a healthy rate but should help the LSP save on fees.
> Embedded LND: conf: max-commit-fee-rate-anchors

- views/LnurlPay/LnurlPay.tsx
Relates to issue: [**ZEUS-1981**](https://github.com/ZeusLN/zeus/issues/1981)
This approach resets the selected currency to sats when loading the LNURL-Pay view.
> ZEUS-1981: LNURL payment amount defaults to current currency

- components/LayerBalances/LightningSwipeableRow.tsx
- utils/handleAnything.test.ts
- utils/handleAnything.ts
There were issues when scanning a QR code with a unified bitcoin URI containing an lnurl part (example: `bitcoin:BC1QUXCS7V556UTNUKU93HSZ7LHHFFLWN9NF2UTQ6N?pj=https://ts.dergigi.com/BTC/pj&lightning=LNURL1DP68GURN8GHJ7ARN9EJX2UN8D9NKJTNRDAKJ7SJ5GVH42J2VFE24YNP0WPSHJTMF9ATKWD622CE953JGWV6XXUMRDPXNVCJ8X4G9GF2CHDF`).
When using a backend supporting on-chain sends, the lightning swipeable row was non-functional.
When using a backend not supporting on-chain sends, the lightning part was interpreted as bolt11.
I have tested this PR with the following types of nodes (please specify node version …
> Fixed handling of unified bitcoin URIs with lnurl

- backends/CLightningREST.ts
- views/Channels/Channel.tsx
As [reported by Bitcoin Puerto Rico](https://njump.me/nevent1qqs28wvlkju30rsjhepesqywdphz2s7s83hcv250pazc4fnzd9pjn9cpp4mhxue69uhkummn9ekx7mqpzfmhxue69uhk7enxvd5xz6tw9ec82cspzemhxue69uhhyetvv9ujumn0wd68ytnzv9hxgqgkwaehxw309aex2mrp0yh8qunfd4skctnwv46qygx2d9khak62s6l8clvcw27jlxjygsx03ck70pf4xm9m8fs2aztyrud8m503), it appears the c-lightning-REST interface is opening channels at 1 sat/vbyte no matter what fee rate you set.
It appears that the c-lightning-REST backend does not accept sats/vbyte as a unit as [detailed here](https://github.com/Ride-The-Lightning/c-lightning-REST/blob/master/controllers/channel.js#L32C61-L32C66). This change has the interface submit the fee rate using `perkb` formatting.
If you modified or added a utility file, did you add …
> c-lightning-REST: OpenChannel: fix fee rate

- models/Payment.ts
- views/Payment.tsx
Relates to issue: [**ZEUS-1934**](https://github.com/ZeusLN/zeus/issues/1934)
Moves the `noteKey` logic for payment objects to the model.
This remedies a regression where notes added on the `SendingLightning` success screen were not being saved properly - may have been a regression from https://github.com/ZeusLN/zeus/pull/1920 …
> ZEUS-1934: Payment: Move noteKey logic to model

- stores/LSPStore.ts
- stores/Stores.ts
- views/Settings/LSP.tsx
Previously, we would use the embedded node's network config flag to determine whether to use the mainnet or testnet LSP host. This PR changes this test to leverage the testnet flag from the `NodeInfo` call.
Furthermore, this PR clears the channel acceptor when changing active nodes now that multiple backends are supported.
> LSP settings: set testnet host based on node info

- models/Invoice.ts
- stores/LightningAddressStore.ts
- views/Settings/LightningAddress/LightningAddressInfo.tsx
> Fix final casing issues for ZEUS Pay

- views/PaymentRequest.tsx
- views/Receive.tsx
- [Receive: hide settings icon when creating invoice](https://github.com/ZeusLN/zeus/commit/5fe5e76cde907c0901b4a2593b022a4853537c61)
- [PaymentRequest: hide pay button when invoice loading](https://github.com/ZeusLN/zeus/commit/5ee16805582a1855d4110af7b36c43c3e536107c)
##
> Send/receive: hide select buttons when loading

- views/Settings/NodeConfiguration.tsx
Instead of using the same hard-coded colors for every theme, now using theme colors.
Also added a colon after "Detected the following..." and improved spacing.
Before:
After:
> Improve node config import suggestion style

- stores/SettingsStore.ts
- utils/LndMobileUtils.ts
- views/Settings/EmbeddedNode/Peers/NeutrinoPeers.tsx
- views/Settings/EmbeddedNode/Peers/index.tsx
Relates to issue: [**ZEUS-2028**](https://github.com/ZeusLN/zeus/issues/2028)
Currently we hard code our default neutrino nodes and let users add additional nodes to connect to.
Let's change the behavior, display all the active peers on the Neutrino peers list, and allow users to reset to the defaults in case they delete them. …
> ZEUS-2028: Embedded LND: Neutrino peers: display all default peers

- components/Modals/InfoModal.tsx
Relates to issue: [**ZEUS-2053**](https://github.com/ZeusLN/zeus/issues/2053)
> ZEUS-2053: Android: Tooltip text hidden in Dark Theme mode

- views/NostrContacts.tsx
- The code now uses Promise.all() to wait for all asynchronous operations to complete before proceeding ensuring proper execution flow.
- Previously setState() was called inside the loop, which could result in multiple state updates and unnecessary re-renders. Now setState() is called only once after all asynchronous operations are completed, reducing unnecessary re-renders and improving performance.
> Refactor fetchNostrContacts

- stores/ChannelsStore.ts
- stores/LSPStore.ts
Relates to issue: [**ZEUS-2062**](https://github.com/ZeusLN/zeus/issues/2062)
In investigating the issue linked above, we discovered that peer connect errors from the LSP were displayed on the `OpenChannel` view. This PR adds a `silent` flag to the `connectPeer` call to be used in the `LSPStore` so that users do not see errors from calls they do not manually initiate. …
> ZEUS-2062: LSP peer connect: make silent on Open Channel view

- stores/SettingsStore.ts
- views/Wallet/Wallet.tsx
Relates to issue: [**ZEUS-2069**](https://github.com/ZeusLN/zeus/issues/2069)
Properly upgrade beta tester users to new LSP hosts and make sure wallet does not stall out if a connection to the LSP cannot be reached.
> ZEUS-2069: Settings: automatically upgrade users on old LSP host 

- components/Button.tsx
- components/Channels/SortButton.tsx
- components/UnitToggle.tsx
- views/Channels/Channel.tsx
- views/Wallet/KeypadPane.tsx
- views/Wallet/StandalonePosKeypadPane.tsx
This PR simplifies the `Button` component by folding the uncommonly used `quinary` boolean style into `quaternary`. It also fixes the style of the `AndroidNfcModal` whose button text was hard to read.
Before:
After:
> Button: simplify style, fix Android NFC modal display

- backends/LightningNodeConnect.ts
- stores/ChannelsStore.ts
- views/Channels/Channel.tsx
Previously, closing channels would not display errors if any occurred, which would cause some user confusion. This PR adds the display of those errors on the singular `Channel` view, instead of automatically redirecting the user back to the `Channels` list.
> Close channel: display error message

- fetch-libraries.sh
- ios/zeus.xcodeproj/project.pbxproj
This new LND builds bumps LNC v0.2.6-alpha -> v0.3.1-alpha
> LND v0.17.4-beta-zeus.2

- components/WalletHeader.tsx
- models/Contact.ts
- utils/PhotoUtils.test.ts
- utils/PhotoUtils.ts
- views/Settings/AddContact.tsx
- views/Settings/NodeConfiguration.tsx
- views/Settings/Nodes.tsx
- views/Settings/SetNodePicture.tsx
- views/Settings/Settings.tsx
This PR adds a new `PhotoUtils` and fixes a bug on Android for setting preset images to a node.
> PhotoUtils

- locales/en.json
- stores/SettingsStore.ts
- views/Lockscreen.tsx
- views/Settings/Display.tsx
- views/Wallet/Wallet.tsx
This PR adds the ability for users to select which node/wallet to use on start-up.
Currently the setting is presented under `Settings` > `Display`
> Add ability to select node on start-up

- locales/en.json
- views/Settings/CurrencyConverter.tsx
This PR adds some error handling for the `CurrencyConverter` view for when the rates haven't been fetched. Previously, 
Before:
After:
> Currency Converter: error handling for rate fetch failure

- views/Wallet/Wallet.tsx
Ensure that connection to the LSP is not attempted if the node is not configured for 0-conf channels
> LSP: ensure node is configured before attempting connection to LSP

- components/PinPad.tsx
- views/Lockscreen.tsx
- views/Wallet/Wallet.tsx
This fixes #1880.
In Lockscreen, after successful login, we navigated to Wallet. Also, when going to background, we called `navigation.pop()` to close a possibly open PIN screen. Both caused that the navigation state was lost.
Instead we now call `navigation.pop()` after successful login in Lockscreen and clear the entered pin in PinPad when going to background. …
> Keep navigation state when resuming from background and login is required

- utils/ErrorUtils.test.ts
- utils/ErrorUtils.ts
We got some report of this error message being thrown frequently. Turns out there's a regression in `ErrorUtils` that causes errors passed in as strings, such as the payment timeout message to be handled incorrectly.
This also adds a generic error message in the edge case that the error is undefined.
> [bug fix] ErrorUtils: handle edge cases 

- backends/EmbeddedLND.ts
- backends/LND.ts
- backends/LightningNodeConnect.ts
- lndmobile/LndMobileInjection.ts
- lndmobile/channel.ts
- locales/en.json
- stores/ChannelsStore.ts
- views/Channels/Channel.tsx
- views/Receive.tsx
This PR adds the ability for LND users to close channels to an external address.
> LND: CloseChannel: close to external address

- locales/en.json
- views/AddNotes.tsx
- views/Invoice.tsx
- views/Payment.tsx
- views/Transaction.tsx
This PR affixes the buttons on the `Transaction`, `Payment`, and `Invoice` views to the bottom of the page and gives them a uniform style. It also modifies the `AddNotes` view slightly, fixing a casing issue and simplifying the save button.
Before and afters:
> Note buttons: fix to bottom of views

- backends/EmbeddedLND.ts
- backends/LND.ts
- backends/LightningNodeConnect.ts
- lndmobile/LndMobileInjection.ts
- lndmobile/channel.ts
- locales/en.json
- stores/ChannelsStore.ts
- views/Channels/Channel.tsx
- views/Receive.tsx
This PR adds the ability for LND users to close channels to an external address.
> [v0.9.0] LND: CloseChannel: close to external address

- backends/CLightningREST.ts
- backends/Eclair.ts
- backends/LND.ts
- backends/LightningNodeConnect.ts
- backends/Spark.ts
- stores/ChannelsStore.ts
- utils/BackendUtils.ts
Renamed openChannel to openChannelSync.
> Fixed openChannel

- views/Settings/CurrencyConverter.tsx
- views/Settings/EmbeddedNode/Peers/NeutrinoPeers.tsx
- views/Settings/EmbeddedNode/Peers/ZeroConfPeers.tsx
Fixed error:
> VirtualizedLists should never be nested inside plain ScrollViews with the same orientation because it can break windowing and other functionality - use another VirtualizedList-backed container instead.
> Fix nested VirtualizedLists error

- android/settings.gradle
- components/PinPad.tsx
- ios/Podfile.lock
- package.json
- yarn.lock
Entering pins without haptic feedback is extremely annoying (typos happening without notice).
The library respects system settings for haptic feedback.
Setup is done for Android but not for iOS - see https://www.npmjs.com/package/react-native-haptic-feedback.
> Haptic feedback for pin pad buttons

- views/Settings/SetPassword.tsx
- views/Settings/SetPin.tsx
This fixes #1757. After setting a new PIN or password, no additional login is required now. Also improved color of 'Delete Password' button:
> Do not require login after setting new PIN or password

- views/Settings/NodeConfiguration.tsx
This fixes #2171. Additionally, a reconnect is initiated if active node is edited while multiple nodes exist.
> Reconnect only if relevant property of active node was changed

- stores/SettingsStore.ts
- utils/PhotoUtils.ts
- views/Accounts/ImportingAccount.tsx
- views/Channels/Channel.tsx
- views/ContactDetails.tsx
- views/NostrContacts.tsx
- views/PSBT.tsx
- views/Receive.tsx
- views/SendingLightning.tsx
- views/SendingOnChain.tsx
- views/Settings/AddContact.tsx
- views/Settings/Contacts.tsx
- views/Settings/EmbeddedNode/DisasterRecoveryAdvanced.tsx
- views/Settings/EmbeddedNode/RestoreChannelBackups.tsx
- views/Settings/LightningAddress/NostrRelays.tsx
- views/Settings/NodeConfiguration.tsx
- views/Settings/Nodes.tsx
- views/Settings/Seed.tsx
- views/Settings/SeedRecovery.tsx
- views/Settings/SelectCurrency.tsx
- views/Settings/SetDuressPassword.tsx
- views/Settings/SetDuressPin.tsx
- views/Settings/SetNodePicture.tsx
- views/Settings/SetPassword.tsx
- views/Settings/SetPin.tsx
- views/TxHex.tsx
The new react-navigation version has a breaking change which we didn't take care of: The navigate function no longer goes back on the stack to a previously mounted Screen but always puts the Screen on top of the stack. Now you need to call popTo to have the old behavior.
> Fix navigation upgrade regressions

- App.tsx
- components/Header.tsx
- components/WalletHeader.tsx
- utils/NavigationUtils.ts
- views/Activity/Activity.tsx
- views/Wallet/Wallet.tsx
- Allow defining transition animation using route params
- Improved animations for some navigations (Just for demonstration. Needs to be done for a lot more navigations.)
- Swapped nodes and settings in header
- Enable animations for bottom tab navigator
- Fixed spacing of bottom tab icons
> Improve animations (and more)

- views/POS/ProductCategoryDetails.tsx
- views/Settings/LightningAddress/NostrRelays.tsx
Use ArrowLeft svg for back buttons.
Also fixed another nested VirtualizedLists error.
> Harmonize back icons

- locales/en.json
- views/Settings/Currency.tsx
- views/Settings/CurrencyConverter.tsx
- views/Settings/PointOfSale.tsx
- Improved error message for POS Square if currency is disabled
- Hide currency settings and converter if currency is disabled (-> removed currency disabled handling accordingly)
> Improve currency enabled error handling

- locales/en.json
- views/POS/ProductDetails.tsx
Issue: https://github.com/ZeusLN/zeus/issues/2199
Before:
After:
> POS: Add Delete Product btn and remove the icon

- stores/ChannelBackupStore.ts
- views/Settings/EmbeddedNode/DisasterRecoveryAdvanced.tsx
Relates to issue: [**ZEUS-2042**](https://github.com/ZeusLN/zeus/issues/2042)
When manually recovering SCB data, a loading indicator will now be shown and an error message will be displayed properly on error.
- x ] iOS
> ZEUS-2042: add feedback to manual SCB recovery process

- views/LnurlChannel.tsx
Relates to issue: [**ZEUS-2214**](https://github.com/ZeusLN/zeus/issues/2214)
This PR changes to the behavior for LNURL-channel to default to private (unannounced) channels. It also updated the toggle to label to match that of the `Open Channel` view and use the label "Announced"
> ZEUS-2214: LNURL-channel: default to unannounced channel

- locales/en.json
- stores/SettingsStore.ts
- utils/LndMobileUtils.ts
- views/Intro.tsx
- views/IntroSplash.tsx
- views/Settings/NodeConfiguration.tsx
- views/Settings/SeedRecovery.tsx
This PR optimizes the Neutrino peers selected by default for users, by pinging predefined sets of peers and setting the user's peers to be only those with pings of under 200ms
> Neutrino: auto-select peers on wallet creation

- components/Modals/AlertModal.tsx
- locales/en.json
- stores/AlertStore.ts
- utils/LndMobileUtils.ts
- views/Settings/EmbeddedNode/Peers/NeutrinoPeers.tsx
This PR changes the upper threshold for what we consider an acceptable Neutrino ping from 200ms to 1000ms. This will be taken into consideration when auto-selecting Neutrino peers on wallet creation/recovery, on our new alerts system, and in the manual ping test system on the Neutrino peers settings page.
Related Neutrino commits:
https://github.com/ZeusLN/lnd/commit/41ce36eec3bb2d3bce8aa3a7bd102126381bed81
https://github.com/djkazic/neutrino/commit/c8fd04d4f772fec06ae5f71da5c641dd37db34c8
I have tested this PR with the following types of nodes (please specify node version and API …
> Neutrino: increase ping threshold, 200->1000ms

- components/UTXOPicker.tsx
The UTXO picker in Send dialog is a modal dialog. So it should have secondary background color (like hop picker).
> Fix UTXO picker background color

- views/Wallet/StandalonePosPane.tsx
https://github.com/ZeusLN/zeus/issues/2128
Earlier we used to get $0 when we try to checkout POS orders if fiat are disabled in settings. instead of that we should have the `sats` as currency in that case
Before:
https://github.com/ZeusLN/zeus/assets/50761978/94713b15-54c5-41ff-8aa3-9e781c3e1886
After:
https://github.com/ZeusLN/zeus/assets/50761978/fcb1d988-0fc0-4559-a82e-1c3baac41abe
> POS: Display 'sats' in CHARGE button when fiat is not enabled

- locales/en.json
- utils/LndMobileUtils.ts
- views/Intro.tsx
- views/IntroSplash.tsx
- views/Settings/EmbeddedNode/Peers/NeutrinoPeers.tsx
- views/Settings/NodeConfiguration.tsx
- views/Settings/SeedRecovery.tsx
This PR adds a button to manually trigger the newly-added peer selection function on the Neutrino peers settings page.
> Settings: Neutrino: add optimize peers button

- views/Settings/CurrencyConverter.tsx
Fixed the flags position in Currency Converter input boxes which broke due to our recent update to react native `0.74.2`
> Currency Converter: Fix flags position in input boxes

- models/Product.ts
- views/POS/ProductDetails.tsx
https://github.com/ZeusLN/zeus/issues/2200
> POS: Bug Fix - Leading zero in product price

- components/AmountInput.tsx
This PR seeks to address issues with the `AmountInput` component raised in comment https://github.com/ZeusLN/zeus/pull/2245#issuecomment-2181367621
- `I personally find it a bit irritating when the input is pre-filled with a "0" (not as placeholder, but really the value for the text input).`
This is directly addressed by this PR
- `Block entering of invalid chars (anything but numbers and decimal separators should be ignored for amount inputs)`
This is directly addressed by this PR
- `Remove invalid chars if pasted (e.g. somebody is pasting "12 304 sats", it should result to "12304")`
This is directly addressed by this PR
- `Allow leading zeros but remove them internally when whatever process is continued (product saved, invoice created etc.)`
- 
This is already addressed by `UnitStore`'s …
> `AmountInput` enhancements

- components/SwipeButton.tsx
- locales/en.json
- views/PaymentRequest.tsx
https://github.com/ZeusLN/zeus/issues/2034
Demo Video:
https://github.com/ZeusLN/zeus/assets/50761978/48ea415e-78e9-4026-8675-f9fb3891a19a
> Component: SwipeButton

- views/Lockscreen.tsx
- views/Settings/Nodes.tsx
- views/Wallet/Wallet.tsx
This PR fixes an issue with loading invoices when `Select node on start-up` is enable under Display settings.
Previously, when the app was being opened to pay an invoice, it would skip the `Nodes` view. This PR ensures that a node is selected by the user before the invoice is loaded.
> Startup: wait for node selection to load invoice

- stores/LSPStore.ts
- utils/ErrorUtils.test.ts
- utils/ErrorUtils.ts
Handles PascalCased errors from the LSP spec services.
Before:
After:
> ErrorUtils: handle PascalCase error messages from LSPS1

- components/Amount.tsx
- locales/en.json
- stores/SettingsStore.ts
- views/Settings/Display.tsx
Relates to issue: [**ZEUS-1503**](https://github.com/ZeusLN/zeus/issues/1503)
Settings view:
Enabled:
Disabled:
> ZEUS-1503: Settings: Display: add ability to hide millisat amounts

- views/Settings/SetNodePicture.tsx
Add CLN.jpg to selection for the CLNRest implementation. This existing image is used today for c-lightning-REST.
> Add CLN.jpg to selection for CLNRest in SetNodePicture.tsx

- components/LayerBalances/LightningSwipeableRow.tsx
- components/LayerBalances/index.tsx
- utils/AddressUtils.test.ts
- utils/AddressUtils.ts
- utils/handleAnything.ts
- views/Accounts/Accounts.tsx
> BIP-353: grok out on-chain addresses

- models/Payment.ts
A regression was added in https://github.com/ZeusLN/zeus/commit/77bcc7cd481f35dce27bd78197f185b6d3627e66 that causes payments in LND (REST) interfaces to all show as failed payments.
> [bug fix] LND (REST): incorrectly displayed failed payment

- backends/CLNRest.ts
- backends/CoreLightningRequestHandler.ts
Relates to issue: #1637
We spoke about this a bit on the telegram chat, to begin with we will limit the list of transactions to 150. Right now I was able to limit the expensive `bkpr-listaccountevents` and `listinvoices`. I couldn't restrict `listpays` because it doesn't take a limit argument. There is a `listsendpays` that can take a limit but it doesn't return bolt12 payments (classic CLN). 
> CLNRest: performance improvements using sql query

- backends/CLNRest.ts
CLNRest backend fix.
Current master branch uses the `/v1/listinvoices` endpoint for involves and does a limit of 150 records by created index. Unfortunately this limit is for the first 150 invoices and not the last 150 invoices. This means nodes with more than 150 invoices in the current master branch won't show up in the Activity View.
Link to code:
https://github.com/ZeusLN/zeus/blob/3e6cf778eed04527907133bbbe1c2aeac3bb1f82/backends/CLNRest.ts#L214
The fix is to move to the sql endpoint and order by created_index DESC.
I have tested this PR with the following types of nodes (please …
> [BugFix] CLNRest Backend Fix for paid invoices

- utils/ConnectionFormatUtils.test.ts
- utils/ConnectionFormatUtils.ts
- utils/handleAnything.ts
This PR adds a QR decoder specifically for CLNRest connections. It is inspired by the format used for c-lightning-REST connections.
> CLNRest: add QR format

- backends/CLNRest.ts
Like in PR #2290 and #2295, both `bkpr-listaccountevents` and `listinvoices` was converted to `sql` to improve performance. This PR is similar in purpose but for `listpays`. The `listpays` endpoint returns every lightning payment made by the node. In larger or older nodes this can be problematic. This PR limits payments returned to the last 150 payments made (completed, pending or failed).
This PR updates the `listpays` endpoint to `sql` to query the `sendpays` table. The `listpays` endpoint is a CLN plugin written in C; which I believe is defined [here](https://github.com/ElementsProject/lightning/blob/bc5c528910158635ec26bd64c10c8c97754905f1/plugins/pay.c#L536). The is no `pays` table available in the `sql` endpoint. The `sendpays` table is a list of payments attempts and payment parts. …
> [Enhancement] CLNRest convert /v1/listpays to /v1/sql

- android/app/src/main/java/com/zeus/LndMobileScheduledSyncWorker.java
- android/app/src/main/java/com/zeus/LndMobileService.java
> Android: update scheduled sync worker

- components/LayerBalances/index.tsx
- locales/en.json
We've received some reports of users that are confused on how to 'move funds to lightning' after depositing on-chain funds in the wallet.
This PR aims to improve the UX by prompting users to `Move on-chain funds to lightning` if they have a lightning balance of 0 and a non-zero on-chain balance.
> Layer Balances: prompt user to open channel if they only have on-chain funds

- views/SendingLightning.tsx
Previously, we would only display the button on timeout or no route found errors.
> Sending Lightning: always display Try Again button on error

- locales/en.json
- views/Settings/NodeConfiguration.tsx
Relates to issue: [**ZEUS-2189**](https://github.com/ZeusLN/zeus/issues/2189)
This includes two changes:
- NODE CONFIG SAVED is now never be displayed. If there are no changes, the Save button is hidden
- NODE ACTIVE is now a label, and placed above the action buttons
Before:
After:
> ZEUS-2189: Node Configuration: some buttons should be labels

- stores/InvoicesStore.ts
Relates to issue: [**ZEUS-2396**](https://github.com/ZeusLN/zeus/issues/2396)
> ZEUS-2396: External accounts: don't pass in preferred address type on new address call

- backends/EmbeddedLND.ts
- backends/LND.ts
- backends/LightningNodeConnect.ts
- views/Channels/Channel.tsx
In Lightning, force closes used pre-negotiated fee rates.
In a recent release of LND (v0.18.0?), force channel closes with fee rates provided now throw the following error:
`[ERR] RPCS: [/lnrpc.Lightning/CloseChannel]: force closing a channel uses a pre-defined fee`
This PR:
- On the backend, on the Close channel call, ensures fee rates are not passed in if the force close flag is.
- On the frontend, moves the force close toggle above the other close channel fields, and hides the fee rate field if force close is switched on.
I have tested this PR with the following types of nodes (please …
> Close Channel: Force Close: fee rate fix

- views/Settings/CurrencyConverter.tsx
https://github.com/ZeusLN/zeus/issues/2437
To fix this issue, we made the following changes:
- We added a check that immediately stops the conversion process if the input field is cleared. This prevents the input from converting an empty value into `0`.
- When the input is cleared, we made sure all related converted values in the other currency fields are also cleared, instead of showing incorrect conversions.
> Bug Fix: Prevent Currency input to display '0' when it is empty

- views/Receive.tsx
- views/Settings/InvoicesSettings.tsx
When using Blinded Paths with LND, route hints are incompatible and AMP invoice are not support _yet_. This PR toggles these settings off and disables the switches when Blinded Paths are enabled on the `Receive` view and under `Settings`.
> Receive: Blinded Paths: turn off and disable AMP and Route Hints

- views/Lockscreen.tsx
When in POS mode, a back button did not appear on the `Lockscreen`. This would cause users to either have to brick ZEUS or restart the app if they did not know the password.
> Lockscreen: include back button when in POS mode

- components/SetFeesForm.tsx
In v0.9.1 we allow the setting of inbound fees for channels, which can be set to negative values.
The problem is that on Android, the `numeric` keyboard shows the `-` char, whereas on iOS, it does not.
Changing the keyboard type to `decimal` will result in no change for most Android systems, whereas iOS should have access to the full keyboard so that users can hit the `-` char.
* verify that …
> [bug fix] SetFeesForm: allow iOS users to input negative amounts for inbound fees

- views/PaymentRequest.tsx
https://github.com/ZeusLN/zeus/issues/2403
> PaymentRequest: Handling payment calls from separate functions

- stores/UTXOsStore.ts
- views/Accounts/ImportingAccount.tsx
When generating existing addresses, importing an external account can take longer. This PR adds a loading indicator and progress indicator to the `ImportingAccount` view to improve the UX when generating many pre-existing addresses
> ImportingAccount: add loading indicator

- views/LnurlPay/LnurlPay.tsx
Relates to issue: [**ZEUS-2443**](https://github.com/ZeusLN/zeus/issues/2443)
Retain currency unit state when paying a LNURL-pay or lightning address.
Unsure why we were resetting units previously - perhaps for the range not displaying correctly?
> ZEUS-2443: LNURL-Pay: retain currency unit state

- backends/LightningNodeConnect.ts
- views/Settings/Nodes.tsx
Relates to issue: [**ZEUS-2472**](https://github.com/ZeusLN/zeus/issues/2472)
> ZEUS-2472: Unable to Add Lightning Node Connect Node When No Nodes are Present

- views/Intro.tsx
#2485  
(In the Intro view, we have changed the ADVANCE OPTIONS to redirect to Menu instead of Settings)
> Intro: Redirect to Menu instead of Settings

- views/Settings/SeedRecovery.tsx
> SeedRecovery: fix uneven columns and margins

- components/OnchainFeeInput.tsx
- views/Channels/Channel.tsx
- views/OpenChannel.tsx
- views/Send.tsx
Relates to issue: [**ZEUS-2491**](https://github.com/ZeusLN/zeus/issues/2491)
- Users must now manually set a fee rate when mempool fee suggestion fails, when opening a channel, closing a channel, or making an on-onchain transaction
- Opening a channel, closing a channel, and making an on-onchain transaction is blocked when the fee rate is set to 0 sats/vbyte
- On the `Open Channel` view the fee input form is now moved out and above the `Advanced settings` section
- Fixes display of the icon on the `Open Channel` button on the `Open Channel` view
- `OnchainFeeInput`: when suggestions are disabled, force users to manually set the fee rate before proceeding
I have tested this PR on …
> ZEUS-2491: force user to set rate on mempool fee suggestion error

- build.sh
Related issue: [ZEUS-2470](https://github.com/ZeusLN/zeus/issues/2470)
"Reproducible Builds" feature is not working for 0.9.1, so it's also failing at WalletScrutiny. Using a newer (v14.0) container makes it work.
> Using new react-native-android container for v0.9.1

- App.tsx
- components/LayerBalances/LightningSwipeableRow.tsx
- components/LayerBalances/OnchainSwipeableRow.tsx
- components/LayerBalances/PaymentMethodList.tsx
- components/LayerBalances/index.tsx
- utils/AddressUtils.test.ts
- utils/AddressUtils.ts
- utils/handleAnything.test.ts
- utils/handleAnything.ts
- views/ChoosePaymentMethod.tsx
Related issues: [ZEUS-2399](https://github.com/ZeusLN/zeus/issues/2399), [ZEUS-2433](https://github.com/ZeusLN/zeus/issues/2433)
When presented with a payment string that has multiple methods, this new `ChoosePaymentMethod` view replaces the `Accounts` view to provide a better UX. 
Users are presented with all the payment methods, and methods not supported by the backend are faded out:
* verify …
> Payment method list

- android/app/src/main/java/com/zeus/MainActivity.kt
As of Android 13 we can use setRecentsScreenshotEnabled to avoid data leak via recents.
Before:
After:
> Android only: Set 'setRecentsScreenshotEnabled' to false to avoid data leak via recents

- stores/ChannelsStore.ts
- views/HandleAnythingQRScanner.tsx
While testing our external account workflows against the Foundation Passport we found a few issues.
- LND now requires outputs to be defined when verifying a PSBT with `FundingStateStep`. Previously we were able to skip passing them in when only funding a single channel. We now pass them in/
- Passport (like the Krux) always returns back a signed PSBT instead of a TX hex, even dealing with a single sig wallet. We've now added formal handling for UR `bytes` and `crypto-psbt` formats. …
> External account workflow fixes

- views/HandleAnythingQRScanner.tsx
- views/PSBT.tsx
> PSBT: BC-UR: use 'crypto-psbt' instead of 'bytes' formatting

- components/BalanceSlider.tsx
- components/Channels/BalanceBar.tsx
- components/Channels/ChannelItem.tsx
- components/HopPicker.tsx
- components/KeyValue.tsx
- models/Channel.ts
- utils/ThemeUtils.ts
- views/Channels/Channel.tsx
- views/Channels/ChannelsPane.tsx
This PR attempts to visualize the channel reserve capacity of a channel. This is the reserve both parties must retain on their side of the channel to prevent cheating. Read more here: https://bitcoin.design/guide/how-it-works/liquidity/#what-is-a-channel-reserve
To convey this. We
- Add a reserve segment to the `BalanceBar` component in between the inbound and outbound amounts that is the composite color of the two.
- Add a color indicator circle to the `KeyValue` component to be displayed on the single `Channel` view to give the user an additional visual cue.
I have tested this PR with …
> Visualize channel reserve capacity

- stores/ChannelsStore.ts
Sometimes our embedded nodes have issues displaying our LSP's node alias from the graph data. This PR adds an index of predefined aliases to fall back on in case the alias cannot be fetched.
> Channels: fixed aliases

- stores/LightningAddressStore.ts
- views/Settings/LightningAddress/NostrKeys.tsx
This PR fixes two bugs with ZEUS Pay lightning addresses.
- Nostr relay sigs were not being updated when Nostr keys were changed
- The user's saved relay list was not being used for attestation lookup
> ZEUS Pay: update relay sig when Nostr key updated

- views/Lockscreen.tsx
This fixes #2544 for both, deleting PIN and Duress PIN.
> Delete PIN: Pop screens to avoid false navigation when using back button

- stores/SettingsStore.ts
- views/Settings/Security.tsx
Before Zeus had to be killed and restarted to reflect biometric system settings changes.
-> Added navigation focus listener to reflect settings changes made while Zeus is running immediately when returning to the Security screen.
> Refresh security settings on screen focus

- components/LayerBalances/LightningSwipeableRow.tsx
- components/LayerBalances/OnchainSwipeableRow.tsx
- locales/en.json
> Display info when clicking on swipeable rows while sync

- locales/en.json
- views/Intro.tsx
- views/IntroSplash.tsx
- views/Settings/WalletConfiguration.tsx
> Use "My Lightning Node" as nickname for Quick Start

- views/Channels/ChannelsPane.tsx
- Center tab bar items
- Reduce font size
> Improve channel tabs layout

- components/CollapsedQR.tsx
- locales/en.json
- stores/SettingsStore.ts
- views/Invoice.tsx
- views/PaymentRequest.tsx
- views/QR.tsx
- views/Receive.tsx
- views/Settings/InvoicesSettings.tsx
- New invoice setting "Display requested amount on invoice"
- Optionally display requested amount on invoice
This finally fixes #1600.
Before:
After:
> New invoice setting "Display requested amount on invoice"

- views/Settings/LSPS1/OrdersPane.tsx
Resolved the issue where the map function did not return parsed objects, that was resulting in empty **OrdersPane** view. 
> LSPS1/OrdersPane: Render LSPS1 Orders correctly

- backends/LND.ts
- backends/LightningNodeConnect.ts
Something we overlooked when implementing LSPS1 for remote LND nodes: on the [`SubscribeCustomMessages`](https://lightning.engineering/api-docs/api/lnd/lightning/subscribe-custom-messages/) endpoint, LND must be built with `devrpc` tags for messages with type outside of the custom range (>= 32768). The LSP spec uses messages with type 37913.
Since many remote node users do not have their LND instances built with the `devrpc` tag, we'll point them to use the HTTP interface instead. …
> LSPS1: default to REST interface for remote LND nodes

- views/Settings/Wallets.tsx
This fixes #1783.
The root cause was that we called `BackendUtils.disconnect()` after `updateSettings()` which led to calling `disconnect` with the new implementation (depending on the node you were switching to, coming from an LNC-connection), so the LNC-connection could not be disconnected properly.
> Switching from LNC to non-LNC node: Call BackendUtils.disconnect() with correct implementation

- package.json
- utils/DateTimeUtils.test.ts
- utils/DateTimeUtils.ts
- Created DateTimeUtils.test.ts
- fixed/improved DateTimeUtils
> Tests for DateTimeUtils, DateTimeUtils Improvements

- views/Channels/ChannelsPane.tsx
Relates to issue: [**ZEUS-2621**](https://github.com/ZeusLN/zeus/issues/2621)
> ZEUS-2621: Channels list: persist selection on reload

- views/Settings/PointOfSale.tsx
This fixes a bug, where Wallet.tsx still displayed POS tabs, after POS was disabled.
(Probably regression from https://github.com/ZeusLN/zeus/pull/2395)
> Reset POS status when disabling POS

- views/NetworkInfo.tsx
- views/NodeInfo.tsx
- views/Sync.tsx
https://github.com/ZeusLN/zeus/issues/2602
> Format block height with commas

- lndmobile/channel.test.ts
This adds first test coverage for channel backup functions in lndmobile/channel.ts.
> Tests for channel backup functions (lndmobile/channel.ts)

- components/Amount.tsx
- utils/LocaleUtils.ts
This fixes #1812.
Some languages like German capitalize all nouns, while others use lowercase for inline nouns. This adds proper language-specific casing for label texts based on locale (so far only fee label).
> add language-specific noun casing for in line usage

- components/OnchainFeeInput.tsx
- stores/FeeStore.ts
- views/EditFee.tsx
- views/Send.tsx
Now FeeStore is used to manage fee state between EditFee and parent screens via MobX observables. This removes the need to pass callback functions through navigation params, eliminating the "Non-serializable values found in navigation state" warning.
Additionally removed unused handleOnNavigateBack() in Send.tsx.
> Use store for fee updates between screens

- backends/LNC/credentialStore.ts
- backends/LightningNodeConnect.ts
This fixes an issue where Zeus was reconnecting to old host, even though mailbox server was modified.
Steps to reproduce:
- connect to LNC node
- modify host to something unreachable
- click "save"
-> Zeus will reconnect to old host...
The root cause was that serverHost was being stored in two places: within the main credentials object and as part of the persisted data. When loading credentials, the old serverHost value from persisted data was overriding the new host setting.
-> Fixed this by separating serverHost storage into its own dedicated storage location and implementing proper migration to handle existing data.
I have tested this PR on the following platforms (please specify …
> Fix LNC mailbox server switching

- models/Payment.ts
- views/Activity/Activity.tsx
This fixes #1444.
-> Keysend messages are displayed just like regular memos in Activity and Payment view.
> Display keysend messages like memos in Activity and Payment

- components/LoadingColumns.tsx
> Loading Columns: make surrounding wordmarks visible on light themes

- views/Receive.tsx
Previously, switching nodes while having active embedded-lnd or LNC subscriptions resulted in JSON parse errors and potential listener leaks. This PR implements proper subscription cleanup.
Steps to recreate the issue:
1. Connect to node via LNC
2. Create invoice
3. Switching to different node
-> JSON parse errors occur, when switching back and forth again the app even crashes.
* verify that …
> Improve listener cleanup and subscription handling

- backends/CLNRest.ts
- backends/LND.ts
- stores/NodeInfoStore.ts
- views/Wallet/Wallet.tsx
This implements 30s timeout for non-Tor connections (Tor connection timeout is unchanged = 2 minutes).
During initial node connection it stops after first failure.
This fixes #1734.
> Faster connection timeouts for non-Tor connections

- backends/EmbeddedLND.ts
- backends/LND.ts
- backends/LightningNodeConnect.ts
- lndmobile/LndMobileInjection.ts
- lndmobile/index.ts
- stores/PaymentsStore.ts
- views/SendingLightning.tsx
- views/Wallet/Wallet.tsx
> Payments: Update `getPayments` call to limit the number of payments

- views/Settings/LightningAddress/LightningAddressSettings.tsx
Relates to issue: [**ZEUS-2626**](https://github.com/ZeusLN/zeus/issues/2626)
> ZEUS-2626: Lightning Address Settings: Notifications setting does not persist

- locales/en.json
- models/Channel.ts
- stores/InvoicesStore.ts
- views/Channels/Channel.tsx
Relates to issue: [**ZEUS-2629**](https://github.com/ZeusLN/zeus/issues/2629)
When manually adding route hints to an invoice, peer SCID alias should be used in place of the channel ID when available.
> ZEUS-2629: Failed payment to invoices with route hints

- views/Lockscreen.tsx
When opening the App, there was no label "Enter passphrase".
When changing  the password/leaving POS, it is now consistent to when PIN is used.
This fixes #2657.
App opening:
Change password/leave POS:
App opening:
Change password/leave POS:
App opening:
Change password/leave POS:
> Lockscreen: Display "Enter Passphrase" just like "Enter PIN"

- views/Wallet/Wallet.tsx
Per a user on Telegram:
```When I am connecting to my tor and it fails and Zeus gives me the angry red screen, if I tap the space below the “restart” button and the bottom edge of my screen it takes me to the QR code scanner.```
> Bug fix: invisible tab navigation present on error

- locales/en.json
- stores/ContactStore.ts
- views/Settings/AddContact.tsx
First I just wanted to fix #2423. But while looking into the implementation, there was a lot more to do...
Refactor:
- Added `ContactInputField` component for reusable field inputs (easier to maintain and now 1297 lines vs. before 1525)
Bugfixes:
- Horizontal scrolling fixed for inputs (by `marginHorizontal: 24` for `inputContainer`)
- Using same `marginTop` for dividers now (normal vs. additional fields)
- After deleting a contact `clearPrefillContact()` is now called -> before, old data was visible, when you deleted a contact and then created a new one
- When editing an existing contact, proper array access checks are now done to avoid warning `[mobx.array] Attempt to read an array index (0) that is out of bounds (0). Please check length first. Out of bound indices will not be tracked …
> Contacts: Refactor, bugfixes, improved logic/behaviour

- views/Settings/WalletConfiguration.tsx
This fixes #2589 for LNDHub and Eclair.
> Wallet Configuration: Use showHideToogle for LNDHub and Eclair password inputs

- components/Text.tsx
- views/Receive.tsx
- views/Settings/ChannelsSettings.tsx
- views/Settings/Display.tsx
- views/Settings/InvoicesSettings.tsx
- views/Settings/LightningAddress/ChangeAddress.tsx
- views/Settings/LightningAddress/LightningAddressSettings.tsx
- views/Settings/LightningAddress/index.tsx
- views/Settings/PaymentsSettings.tsx
- views/Settings/Privacy.tsx
There is still work to do after this PR, but this is a step towards more consistent and cleaner layouting.
General:
Same overall padding/margin for Invoice, Payment, Privacy and Lightning Address Settings
&nbsp;
Payment Settings/Invoices Settings/Privacy Settings/Lightning Address Settings/Receive:
- improved styling to avoid problems in case of smaller screens/larger font size/longer locale strings (non english)
-> switch cannot be pushed out of display view or overlap with text anymore
-> switch is now correctly centered vertically in case text has more than 1 line
- removed `<Row>` component in `<Text>` component to not break layout if explainer is used
&nbsp;
Additionally:
- Payment Settings: `Lightning - Default Fee Limit`: "sats" now has more space to the right
- Lightning Address …
> Several layout improvements

- views/Receive.tsx
- views/Settings/InvoicesSettings.tsx
These changes
- improve rendering performance, when clicking `Receive` in on-chain swipeable row
- moved selectedIndex initialization to constructor (no more renderings with wrong selectedIndex)
- added `selectedIndex !== 2` condition to prevent unnecessary rendering
- show SettingsButton instead of ClearButton for selectedIndex=2 (on-chain), because here it makes sense to choose address type (and not going back to create another invoice)
- enhance addressType modalBox (Receive and InvoiceSettings)
- ~~60% height~~
- scrollable content for longer translations
- prevents unnecessary updates when same address type is selected
- Receive only: automatically generates new on-chain address when new address type is picked
If you modified or added a utility …
> Enhance on-chain receive workflow and address type selection

- components/ModalBox.tsx
This fixes #2477 by hiding modal dialogs when login is required.
> Hide modal dialogs on lock screen

- views/Wallet/Wallet.tsx
> Prevent displaying Wallets.tsx after enabling "Select node on startup"

- models/Invoice.ts
- models/Payment.ts
- views/Activity/Activity.tsx
- views/Invoice.tsx
- views/Payment.tsx
In #2634 I forgot to look at the receiving side, so now
- `Invoice.ts` handles keysend messages and regular memos in a single getter `getMemo()` instead of using a separate getter `getKeysendMessage()` (like we have it in `Payment.ts`).
- `Activity.tsx` uses `item.getMemo` instead of `item.memo` for invoice case as well (like payment case).
- `Invoice.tsx` does not show duplicate memos, and no memo row at all if memo doesn't exist (like we have it in `Payment.tsx`).
-> Memo handling and displaying is now consistent between sent and received payments.
I have tested this PR with the …
> Unify memo handling for sent and received payments (invoice and payment)

- components/Amount.tsx
- locales/en.json
- stores/SettingsStore.ts
- utils/PrivacyUtils.ts
- views/Settings/Privacy.tsx
This resolves #1410.
- Long press feature described in explainer (we don't switch to short press for temporarily disabling lurker mode because that can happen by accident easily)
- Short press on amount is now ignored if lurker mode is enabled (before it was cycling sats/BTC/FIAT which makes no sense)
- After a long press (lurker mode temporarily disabled) a short press will still cycle through sats/BTC/FIAT and every short press will reset the timeout for reenabling lurker mode
- Additionally fixed flickering of Greek chars by memoizing the generated Greek chars in PrivacyUtils (this will not lead to theoretical data leak because still new random Greek chars are generated with every new app start)
If you modified or added a utility file, did you add …
> Improve lurker mode

- components/CopyButton.tsx
This adds iconOnly mode to CopyButton for #2728 (share feature).
> Add iconOnly mode to CopyButton

- utils/NavigationUtils.ts
- views/Lockscreen.tsx
This fixes #1946, #2655 and #2659.
- replaced `attemptAdminLogin` with `pendingNavigation` to allow for navigation from POS to Menu
- allow using biometry when leaving POS
- use `popTo()` instead of `navigate()` in Lockscreen to remove Lockscreen from stack and prevent duplicate screens on stack
- added `return` after proceeding to wallet if POS is active
FYI: Not a regression but an existing bug: If Keypad is configured as default view, leaving POS navigates to Balance, not Keypad. I'm going to create an issue for this.
I have tested this PR with the following types of nodes (please …
> Fix security issues and security-related navigation issues

- views/Settings/Security.tsx
- views/Settings/SetPassword.tsx
- views/Settings/SetPin.tsx
This fixes #2709 by using `forBiometrics` navigation parameter when navigating to `SetPin` or `SetPassword` instead of state `pendingBiometricsEnable`.
-> Now whenever user cancels setting up pin or password, the biometric switch will not be enabled, when coming back to Security screen.
Additionally:
- SetPassword:saveSettings(): removed obsolete nav param `refresh`
-> Security.tsx is refreshing settings via `checkSettings()` in `componentDidMount()` anyway
- refactored Security.tsx:handleBiometricsSwitchChange()
-> removed redundant code in `if (isVerified)` case
I have tested this PR …
> Improve biometrics setup flow: Use nav param instead of "pendingBiometricsEnable" state

- models/Payment.ts
Relates to issue: [**ZEUS-2763**](https://github.com/ZeusLN/zeus/issues/2763)
> ZEUS-2763: CLN payments incorrectly listed as 0-amt

- views/NodeQRScanner.tsx
When user scanned something successfully and then uses back button (or back icon in header), user obviously doesn't want to scan something again, but decided to not do whatever was planned.
Example (how it is now):
- Channel open view
- scan a nodes pubkey
- try to open the channel, but it doesn't work (e.g. remote node refused to open because channel to small)
- giving up for now by using back button (or back icon in header)
-> scanner reopens
* verify that …
> Remove scan view from navigation stack after usage

- views/LnurlPay/LnurlPay.tsx
While doing backend calls, display LoadingIndicator and disable CONFIRM button in LnurlPay.tsx.
> Add LoadingIndicator to LnurlPay

- views/Settings/SeedQRExport.tsx
This PR builds off of https://github.com/ZeusLN/zeus/pull/2690 and stores the key locally so that key calculation only has to happen once.
> Embedded LND: Seed: ypriv/zpriv: cache locally

- locales/en.json
- stores/ChannelsStore.ts
This fixes the loading indicator being displayed forever in case backend cannot retrieve node alias (e.g. happening when paying to phoenix wallets).
> Payment path: Display 'Unknown' if backend throws or needs >10s to retrieve node alias

- views/Order.tsx
> Remove default tip of 21% for pos custom tip

- views/Activity/Activity.tsx
Since we now display memos/keysend messages in Activity view, we need to care about hiding those in case lurker mode is enabled...
Notes also need to be hidden.
> Activity: Hide memos/keysend messages and notes when lurker mode is enabled

- components/PinPad.tsx
- components/Touchable.tsx
With this PR you can long press the delete icon in Keypad pane to reset the amount.
> Keypad Pane: Long press "delete" icon to reset amount

- stores/PosStore.ts
- stores/SettingsStore.ts
- views/POS/ProductDetails.tsx
- views/Settings/PointOfSale.tsx
Product Price:
Before, `value` was replaced with '0' which leads to not using `AmountInput`'s default placeholder '0'.
Settings->POS->Tax percentage:
Before, `taxPercentage` was initialized with '0' and placeholder for "Text percentage" `TextInput` was missing.
-> **Note:** This will only affect fresh installs or in case user manually deletes the '0', because '0' is persisted in settings. It is not worth it to create migration for this though.
|Before|After|
|-|-|
|![grafik](https://github.com/user-attachments/assets/390c4001-b354-42b3-a263-6a939bfd03c4)|![grafik](https://github.com/user-attachments/assets/3763623c-ed36-4fa5-bfba-0e7b5261867e)|
|![grafik](https://github.com/user-attachments/assets/48ee157d-0aaa-4534-8d1d-c13df69d3095)|![grafik](https://github.com/user-attachments/assets/0b …
> POS: Use placeholders instead of "real" 0 value for Tax percentage and Product Price

- views/Settings/ChannelsSettings.tsx
- views/Settings/Display.tsx
- views/Settings/InvoicesSettings.tsx
- views/Settings/LightningAddress/LightningAddressSettings.tsx
- views/Settings/LightningAddress/NostrKeys.tsx
- views/Settings/LightningAddress/NostrRelays.tsx
- views/Settings/PointOfSale.tsx
- views/Settings/Privacy.tsx
> Use spread operator for updateSettings()

- views/Settings/Seed.tsx
Relates to issue: [**ZEUS-2804**](https://github.com/ZeusLN/zeus/issues/2804)
> ZEUS-2804: persistent back up your funds' warning in homescreen

- locales/en.json
As discussed with @kaloudis:
We have `"views.LSPS7.type": "Channel lease extension"`, so `"views.LSPS1.type": "Channel lease purchase"` just makes sense.
Before: `"views.LSPS1.type": "In advance channel purchase"`
> Rephrase "In advance channel purchase" to "Channel lease purchase"

- views/LnurlPay/LnurlPay.tsx
This fixes #2821.
Before, we were using `lnurl.minSendable` for `amount` only, but it's needed for `satAmount` also, since this is actually used for sending (`amount` is only used for displaying).
Additionally fixed another bug: When unit was set to `₿` or `Fiat` when scanning the lnurlp QR, `lnurl.minSendable` was used without conversion, resulting in `₿ 1` or `$1`.
**Note:** In `Fiat` case it will display `$0.00` in Amount input now, which is correct, but also `₿0.00 000 000` and `0sats`, which is wrong, because this conversion here uses the actual input `$0.00`. It still uses the correct satAmount (1) internally, so when user proceeds it works fine (see last screenshot), but of course we should think about how to handle this better, but not in this PR.
|Before|After|
|-|-| …
> improve minSendableSats handling

- stores/ActivityStore.ts
- views/Activity/Activity.tsx
This fixes #2824.
Additionally improved `setFilters()` so it maintains complete filter structure when saving to storage, ensuring consistent comparison with default filters for filter icon color, but also now only displaying trash icon if filters are not in default mode.
|Before|After|
|-|-|
|![grafik](https://github.com/user-attachments/assets/0245217d-23a9-4eae-a9b1-39693fb6313c)|![grafik](https://github.com/user-attachments/assets/e9b66c24-e005-42a5-81c4-58e41f710f73)| …
> Activity: Visible feedback in case filters are active, fix filter storage consistency

- views/Receive.tsx
Fixed the margin below expiry buttongroups and route hints switch
Before:
After:
> Receive: Fixed margin 

- lndmobile/channel.ts
- stores/ActivityStore.ts
- stores/BalanceStore.ts
- stores/ChannelBackupStore.ts
- stores/ChannelsStore.ts
- stores/FeeStore.ts
- stores/FiatStore.ts
- stores/InventoryStore.ts
- stores/InvoicesStore.ts
- stores/LSPStore.ts
- stores/LightningAddressStore.ts
- stores/LnurlPayStore.ts
- stores/NodeInfoStore.ts
- stores/NotesStore.ts
- stores/OffersStore.ts
- stores/PaymentsStore.ts
- stores/PosStore.ts
- stores/SettingsStore.ts
- stores/SyncStore.ts
- stores/TransactionsStore.ts
- stores/UTXOsStore.ts
- stores/UnitsStore.ts
- views/Wallet/Wallet.tsx
- Add missing public/private decorators
- Convert public methods to private where appropriate
- Remove unused methods
- Add @action decorator where appropriate
- Use runInAction in async methods
- Fix loading states in BalanceStore methods (set state after reset)
- Refactored channel backup methods (untested)
- Set error state in error handlers
* verify that dependencies are installed for both iOS …
> General refactoring mainly regarding MobX actions + fixed error state

- views/Menu.tsx
- views/Settings/Currency.tsx
- views/Settings/Security.tsx
- views/Settings/Settings.tsx
- views/Tools.tsx
This improves performance by reducing redundant getSettings() calls in various screens.
> Remove redundant getSettings() calls

- components/AmountInput.tsx
- views/OpenChannel.tsx
- views/Send.tsx
This displays the local amount in AmountInput if `Use all possible funds` is enabled, making it consistent/less flickering to normal view.
I added `forceUnit` prop to AmountInput to force it to sats mode, which is obviously needed when `Use all possible funds` is used.
When you disable it again, values get reset properly.
|Before|Before|After|
|-|-|-|
|![grafik](https://github.com/user-attachments/assets/138a6bd9-4de5-4617-911d-f6fe9a203c02)|![grafik](https://github.com/user-attachments/assets/4b25de7a-5403-498b-9fad-e14984e8493b)|![grafik](https://github.com/user-attachments/assets/bbb2a02d-9613-43cc-ba52-2f683872219e)|
I have tested this PR on the following platforms (please …
> Open Channel/Send on-chain: use AmountInput to display fundMax

- android/app/src/main/java/com/zeus/LndMobile.java
- android/app/src/main/java/com/zeus/LndMobileService.java
- lndmobile/LndMobile.d.ts
- locales/en.json
- utils/LocaleUtils.ts
- views/Settings/Language.tsx
- views/Wallet/Wallet.tsx
This fixes #2501.
https://github.com/ZeusLN/zeus/pull/2735 has to be merged first.
**Note:**
As of Android 13, the OS gives users a way to stop Apps that are running in the background (see https://developer.android.com/develop/background-work/services/fgs/handle-user-stopping). Unfortunately that "Stop" button it not trying any graceful shutdown, but does a hard kill (tested with logging in `LndMobileService.java`). So we should provide a button on our own notification that will do a graceful shutdown. (Chances are low, but I guess it is not impossible to corrupt the db when doing a hard kill.)
**Changes:**
- Added button "Shutdown" to Android notification for persistent mode to stop LND gracefully
- Added bridge to use some locale strings on Java layer
-> translation cache will be …
> Android: Graceful shutdown button in notification for persistent mode

- views/Send.tsx
sets default amounts on the `Send` view to zero. Otherwise nothing is passed in and users get a proto error when hitting send:
> Send: ensure default amount is passed as 0

- views/Wallet/KeypadPane.tsx
This allows the `AmountInput` placeholder do its job. Now users will not have to delete a 0 and input their desired amount if they neglect to do so properly on the Keypad Pane view.
> Keypad Pane: don't pass in amount if 0

- stores/SettingsStore.ts
This optimizes the settings update process by extracting node properties updates into a dedicated method. It eliminates redundant `getSettings()` calls (storage operations, parsing JSON) which leads to significant performance improvements.
On Android emulator `updateSettings()` runs significantly faster now (average of 5 runs):
Before: 2285 ms
After: 1306 ms
* verify that dependencies are installed …
> Performance improvement for updateSettings()

- stores/SettingsStore.ts
- views/Settings/ChannelsSettings.tsx
- views/Settings/Display.tsx
- views/Settings/InvoicesSettings.tsx
- views/Settings/LightningAddress/LightningAddressSettings.tsx
- views/Settings/LightningAddress/NostrKeys.tsx
- views/Settings/LightningAddress/NostrRelays.tsx
- views/Settings/PointOfSale.tsx
- views/Settings/Privacy.tsx
This fixes a regression from https://github.com/ZeusLN/zeus/pull/2808, where making multiple rapid settings changes led to some settings changes not being saved because `updateSettings()` was still running. To recreate, try switching on multiple switches e.g. in display settings rapidly on simulator (physical devices are much faster and it might be difficult to recreate, but not sure), then leave the settings view and come back -> some settings were maybe not saved.
As discussed with @kaloudis a queue mechanism in updateSettings() would add too much complexity, so we decided to take this simpler approach.
**Note:** Text inputs are not locked, because it would lead to a flickering effect while typing (it is visible when Dropdowns are disabled), and it should also be pretty much impossible …
> Lock settings elements while updateSettings() is running

- stores/SettingsStore.ts
- views/Intro.tsx
- views/IntroSplash.tsx
- views/Lockscreen.tsx
- views/SendingLightning.tsx
- views/Settings/SeedRecovery.tsx
- views/Settings/SelectCurrency.tsx
- views/Settings/SetDuressPassword.tsx
- views/Settings/SetDuressPin.tsx
- views/Settings/SetPassword.tsx
- views/Settings/WalletConfiguration.tsx
- views/Settings/Wallets.tsx
- views/Wallet/Wallet.tsx
Before, getSettingsAndNavigate() was called everytime Wallet.tsx gained focus. Since processing getSettingsAndNavigate() takes some time, this resulted in the app not being responsive for a short time. Example: When you closed the menu and then immediately clicked on a balance slider, it was not responding.
With this PR the flow is optimized, so getSettingsAndNavigate() is only called:
- via handleFocus():
- On initial load (using existing initialLoad state)
- When coming from Lockscreen after logging in (using new triggerSettingsRefresh flag)
- When POS was enabled (using new posWasEnabled flag)
- via handleAppStateChange():
- when app comes from background (no PIN/password configured)
Additionally fixed a bug, where autonavigation into POS didn't work in this edge case:
- Configure a …
> Call getSettingsAndNavigate less often

- stores/SettingsStore.ts
This fixes a regression introduced by https://github.com/ZeusLN/zeus/pull/2843:
When you open `Send` view this error occured:
` ERROR  Could not load settings [TypeError: this.updateNodeProperties is not a function (it is undefined)]`
Converting the methods to arrow functions ensures they maintain the correct `this` binding to the SettingsStore instance. This is needed since `getSettings()` calls `updateNodeProperties()` when loading settings e.g. in the Send view.
* …
> Convert getSettings() and updateNodeProperties() to arrow functions

- views/Receive.tsx
Creates a new advanced settings toggle on the `Receive` view to remove clutter.
|Before|After|
|-|-|
|![simulator_screenshot_05FCD34F-8070-48AD-A231-47BD19A1B9A4](https://github.com/user-attachments/assets/6b8c2d92-111f-4e26-b04e-76f00fbb7fa7)|![simulator_screenshot_4BD02F68-0ECE-42C4-8514-8128289CC998](https://github.com/user-attachments/assets/f6cbeb33-9114-4af3-ad3d-a5a8a2a29888)|
* verify that …
> Receive: advanced settings toggle

- stores/LightningAddressStore.ts
In v0.10.0-alpha we made some refactors that now have local notifications fire correctly. However, we never restricted them to only be fired when autoredeem was happening in the background. This PR fixes that and stops local notifications from firing when payments are manually redeemed.
> ZEUS Pay: don't fire local notifications on manual redemption

- locales/en.json
- models/Channel.ts
- views/Channels/Channel.tsx
- views/Channels/ChannelsPane.tsx
- Adds a display of 0-conf Confirmed SCID to the single `Channel` view
- Display all aliases on the single `Channel` view are displayed in short channel format
- Ensure 0-conf purchased chans can be renewed by linking the renewal info and the 0-conf Confirmed SCID
|Display of 0-conf Confirmed SCID on the Channel view|
|-|
|![simulator_screenshot_40E855F5-43F2-4D07-B219-1C326750A712](https://github.com/user-attachments/assets/f42543fc-f750-4161-a0b7-d567ae5f20a6)|
* …
> Channel: display 0-conf Confirmed SCID and ensure renewal

- stores/LSPStore.ts
- views/LSPS7/index.tsx
Clears the last loaded order when attempting to extend a channel lease.
> LSPS7: clear last order when entering extension flow

- android/app/src/main/java/com/zeus/LndMobileTools.java
- android/app/src/main/java/com/zeus/MainActivity.kt
- ios/LndMobile/LndMobileTools.m
- ios/LndMobile/LndMobileTools.swift
- lndmobile/LndMobile.d.ts
- views/Settings/EmbeddedNode/LNDLogs.tsx
Update the log functions for Embedded LND wallets to accommodate the new multi-wallet structure
> Embedded LND: update log functions

- views/Settings/Language.tsx
- views/Wallet/Wallet.tsx
Ensure `bridgeJavaStrings` only runs on Android.
> Locales: bridgeJavaStrings: only execute on Android

- lndmobile/channel.ts
It appears we've hit a regression in v0.10.0, potentially from: https://github.com/ZeusLN/zeus/pull/2769
From a user:
```
Ok, next step:
With the remaining OnChain amount I am trying to oben a new channel to your LSP. I set „use all funds“ (in german: Gesamtes Guthaben verwendet). 
But then I receive an error:
„cannot use local funding amount and fundmax parameters“
```
* verify that dependencies …
> Embedded LND: Open Channel: fund max fix

- views/Settings/Wallets.tsx
This addresses a bug where the wallet will go thru a boot loop, if the user has `Settings > Display > Select wallet on startup` enabled, and is selecting an Embedded LND wallet.
Also saves us on unnecessary calls for other backends.
> Wallets: skip connecting procedures if wallet already active

- views/Settings/CustodialWalletWarning.tsx
I have aligned the dismiss warning explainers
Before:
After:
> Dismiss warning: Fix styling

- components/PaymentPath.tsx
- stores/ChannelsStore.ts
This hopefully fixes #2953.
Previously, getNodeInfo() was called during render. Since getNodeInfo() is asynchronous and might be called multiple times for multiple hops, the first result that arrives could trigger unnecessary additional getNodeInfo() calls. By moving the alias prefetching to lifecycle methods, we ensure that getNodeInfo() is only called once per hop when necessary.
* verify that …
> PaymentPath: move getNodeInfo() call outside render()

- views/LnurlPay/LnurlPay.tsx
Relates to issue: [**ZEUS-2954**](https://github.com/ZeusLN/zeus/issues/2954)
Addresses issue of fixes satoshi amounts from LNURLp's being passed into the amount input form with commas and breaking the request call.
> ZEUS-2954: LNURL-pay fixes

- views/Tools/CurrencyConverter.tsx
Issue #2968 
We are now resetting selectedCurrency param after handling to allow re-adding the same currency.
> [bug fix] Currency converter: Same currency can't be added after deletion

- utils/LndMobileUtils.ts
- views/Settings/WalletConfiguration.tsx
Bug initially reported by @myxmaster: upon wallet creation and selection (after already having a remote wallet), prompt to restart is thrown. This is because LND is technically started up to generate the seed and initialize the wallet.
This change, only marks our `embeddedLndStarted` flag, used by the prompt, on subsequent starts, once the `walletPassword` has been defined.
* verify that …
> fix: Embedded LND: don't mark as started on wallet creation

- views/Tools/CurrencyConverter.tsx
Relates to issue: [**ZEUS-2967**](https://github.com/ZeusLN/zeus/issues/2967)
Swaps the edit icon with a checkmark icon when in edit mode.
|default|edit mode|
|-|-|
|![simulator_screenshot_D668325B-FCCE-41F5-8ED3-5F722C4AADD3](https://github.com/user-attachments/assets/cdf8c917-a1bc-4d54-9279-cf80b3530fa9)|![simulator_screenshot_C11EE36A-6148-41A6-8ED1-BFE6A8A86E47](https://github.com/user-attachments/assets/d1fa4680-62f6-492d-b849-6061f4e89535)|
* verify that …
> ZEUS-2967: toggle edit icon on Currency Converter

- components/Amount.tsx
- locales/en.json
Since fiat denominations in the app are always approximations, leveraging exchange rates, let's prefix them all with the approximation symbol: ≈
|-|-|-|
|-|-|-|
|![Simulator Screenshot - iPhone 16 Plus - 2025-04-03 at 22 25 23](https://github.com/user-attachments/assets/17476b5f-f176-4449-af96-3e42d7eba679)|![Simulator Screenshot - iPhone 16 Plus - 2025-04-03 at 22 25 30](https://github.com/user-attachments/assets/ad50609c-1fcb-4b6e-bf6d-1309e15eee0a)|![Simulator Screenshot - iPhone 16 Plus - 2025-04-03 at 22 26 17](https://github.com/user-attachments/assets/0a073746-4e60-424d-aa30-5769452565fe)|
|-|-|
|-|-|
|![Simulator Screenshot - iPhone 16 Plus - 2025-04-03 at 22 27 05](https://github.com/user-attachments/assets/d264a4b9-bd33-4fc2-b461-d9cf3e768221)|![Simulator Screenshot - iPhone 16 …
> Add approximate symbol to fiat amounts

- backends/CLNRest.ts
The problem is that previously clnrest's supportsOffers was returning a Promise<boolean> instead of a boolean like all the others. This was not awaited and therefore was always evaluated as true. Let's actually set it to always true since cln has offers enabled by default since v24.11. Unless you want to work with different return types and implement a check that works across cln versions. The current check would not work on newer cln versions since the option experimental-offers was removed.
I …
> clnrest: supportOffers is always true starting with cln 24.11

- backends/CLNRest.ts
- backends/CoreLightningRequestHandler.ts
- backends/EmbeddedLND.ts
- backends/LND.ts
- backends/LightningNodeConnect.ts
- backends/LndHub.ts
- backends/NostrWalletConnect.ts
- models/Channel.ts
- models/ClosedChannel.ts
- stores/ChannelsStore.ts
- utils/BackendUtils.ts
- views/Channels/Channel.tsx
- views/Channels/ChannelsPane.tsx
Relates to issue: [**ZEUS-2894**](https://github.com/ZeusLN/zeus/issues/2894)
> feat: CLNREST listclosedchannels

- locales/en.json
- views/Channels/Channel.tsx
This PR makes two changes to the `Channel` view
- Hides the external address field when force close is toggled on
- Adds info modal text for the force close switch
> enhancement: Close channel changes

- stores/ChannelsStore.ts
- views/OpenChannel.tsx
Relates to issue: **ZEUS- #2780**
This PR addresses two UI bugs in the OpenChannel view:
- Error messages persist when switching between "Open Channel" and "Connect Peer" tabs
- The lightning loading indicator remains visible after errors occur during connection attempts
**Solution**
When switching between tabs in the OpenChannel view, we now properly reset all error messages and loading indicators. This ensures that errors from one tab don't incorrectly appear in the other tab.
https://github.com/user-attachments/assets/0cb170d7-b329-434b-8925-a4259cb02df7
I have tested this PR with the …
> Channel and peer connection error clearing in UI

- stores/CashuStore.ts
- views/Cashu/UnspentTokens.tsx
A series of modifications to make Cashu support more robust, largely centered around iterating the counter to avoid `outputs have already been signed` errors.
> refactor: Cashu robustness

- models/Channel.ts
- stores/InvoicesStore.ts
Invoices with custom route hints did not include the correct channel id because peer_scid_alias was used even if it contained '0'. Changed the type to string and now using channel id if peer_scid_alias is '0'.
> fix: LND: custom route hints channel ID

- locales/en.json
- views/Settings/Wallets.tsx
- views/Wallet/Wallet.tsx
When the "Select wallet on startup" option is enabled, the app incorrectly initiates a connection to the previously selected wallet in the background. The user is shown a wallet selection screen, but a wallet is already being activated
And also the wording needs to be changed from `Select node on startup` to `Select wallet on startup`. 
**Solution :** 
- Modified the app startup flow to completely bypass wallet activation when "Select wallet on startup" is enabled.
- Added proper state handling in the Wallets screen to track when it's being displayed in "startup mode".
- Prevented Android hardware back button from exiting the wallet selection screen when in startup mode.
- Removed the back button from the header when in startup mode.
- Ensured the restart prompt is never shown when …
> App startup wallet selection 

- PushNotificationManager.tsx
Relates to issue: [**ZEUS-2998**](https://github.com/ZeusLN/zeus/issues/2998)
Explicitly checks Android devices for Google Mobile Services (Google Play Services) before running notification services.
> fix: Notifications: check Android for Google Mobile Services

- stores/LightningAddressStore.ts
- views/LightningAddress/ZeusPayPlus.tsx
- views/LightningAddress/ZeusPayPlusPerksList.tsx
Removes hardcoded values for ZEUS Pay+ annual subscription fees and LSP discounts, which are now returned from the service.
> feat: ZEUS Pay+ dynamic values

- views/Activity/Activity.tsx
This PR, solves the problem of real-time updates of notes in the activity view.
https://github.com/user-attachments/assets/7e212c0b-18ee-4815-ae0f-0cfdcd5a891d
> fix: notes rendering in activity view

- utils/TipUtils.test.ts
- utils/TipUtils.ts
- views/Order.tsx
Fixed a bug in the total sats calculation where the tip percentage was applied incorrectly.
Previously, we were using `new BigNumber(subTotalSats).multipliedBy(1.${effectivePercentage})` that was causing incorrect results:
For example, with subTotalSats = 100 and tip = 5%, the calculation became:
totalSats = 100 * 1.5 = 150 (**which is equivalent to a 50% tip**)
Now, we correctly calculate:
totalSats = 100 * (1 + 5 / 100) = 105 …
> fix: Incorrect totalSats calculation after adding tip %

- locales/en.json
- stores/CashuStore.ts
- Add early return when balanceSats < Number(value) in mintoken (cashuStore)
- Avoid calling getProofsToUse() and other expensive operations
- Improve performance by stopping execution at the balance check
> fix: avoid unnecessary processing when mint balance is insufficient

- views/Channels/ChannelsPane.tsx
Relates to issue: [**ZEUS-3156**](https://github.com/ZeusLN/zeus/issues/3156)
For LND-based nodes, `ping_time` is returned in microseconds but was previously displayed as milliseconds. The current changes fix this by properly converting microseconds to milliseconds.
> fix: list peers ping time precision

- utils/AddressUtils.test.ts
- utils/AddressUtils.ts
- views/Swaps/index.tsx
Issue raised on telegram https://t.me/zeusLN/100002 where legacy addresses were not being handled while making swaps. 
> fix: legacy Testnet addresses + receive swaps to legacy

- views/Receive.tsx
Relates to issue: [**ZEUS-3143**](https://github.com/ZeusLN/zeus/issues/3143)
<p align="center">
</p>
@kaloudis
> feat: Receive: tuck QR tabs and 'Receive via NFC' button under advanced toggle

- stores/FiatStore.ts
- stores/UnitsStore.ts
- utils/UnitsUtils.alt.test.ts
- utils/UnitsUtils.test.ts
- utils/UnitsUtils.ts
- views/Wallet/KeypadPane.tsx
- views/Wallet/StandalonePosKeypadPane.tsx
Relates to issue: [**ZEUS-3175**](https://github.com/ZeusLN/zeus/issues/3175)
Previously, we assumed all fiat currencies has 2 decimal places.
ISO 4217 table available here: https://en.wikipedia.org/wiki/ISO_4217#List_of_ISO_4217_currency_codes
> ZEUS-3175: handle currencies w/ varying number of digits after the decimal separator

- stores/Stores.ts
- stores/TransactionsStore.ts
- views/Receive.tsx
- views/SendingLightning.tsx
Since we call `getSettingsAndNavigate()` less often (https://github.com/ZeusLN/zeus/pull/2660), Zeus is not updating the balance everytime when Wallet.tsx gets focus. That is fine, especially because `getSettingsAndNavigate()` does a lot more and adds quite some loading time. But Zeus **should** update the balance after the user sent or received funds.
This is now done, including updating fiat rates, by using a new flag `triggerBalanceUpdate` in SettingsStore.
* verify …
> Trigger balance update after sending/receiving funds

- components/Amount.tsx
Relates to issue: **ZEUS- #3139 **
This PR fixes RTL (right-to-left) layout issues in the Amount component that were introduced after PR #3179 was merged. The rounding indicator feature inadvertently broke the RTL/LTR logic and caused symbol misplacement issues.
1. **Restored approximate symbol (≈) for all fiat currencies** - Since fiat amounts are inherently approximate due to exchange rate volatility, all fiat displays now show the ≈ symbol to indicate this uncertainty.
2. **Fixed RTL symbol placement** - Restored proper RTL/LTR conditional rendering paths that were consolidated incorrectly in #3139 , ensuring currency symbols and indicators appear on the correct side based on text direction.
If you modified or added a utility file, did you add new …
> fix: add approximate symbol for fiat currencies and fix RTL placement

- views/Swaps/index.tsx
This PR is to improve the user experience on the Swaps view by preventing the input amounts from resetting when the display unit is changed. Previously, toggling between sats, BTC, and fiat would clear the fields. Now,  the amount is recalculated and displayed in the newly selected unit. 
- []X N/A
> enhancement: Swaps: Amount conversion when toggling units

- views/PaymentRequest.tsx
On occasion, the `LND is getting ready to make payments` error is displayed for remote node connections. We believe this was caused due to a race condition in the deprecated `UNSAFE_componentWillMount` lifecycle func.
> fix: 'LND is getting ready to make payments' for remote connections
