README.md

* center pic 
* syntax highlighting
* fix dots and minor stuff
Note: The line breaks before and after the links don't change the formatting in github, they just make the plaintext easier to read.

center pic

---

views/Receive.tsx

For some reason, the memo and amount fields were getting deselected every time you added or removed a character from one of those fields.
The syntax is a bit messier now but at least it is not annoying to create an invoice.
Will revisit down the line.

Receive -> Lightning: Fix bug where memo + amount fields get deselected after each character

---

models/CloseChannelRequest.ts
stores/ChannelsStore.ts
stores/UnitsStore.ts
views/Channel.tsx
views/Wallet/Channels.tsx
views/Wallet/Invoices.tsx
views/Wallet/Payments.tsx
views/Wallet/Transactions.tsx
views/Wallet/Wallet.tsx

You can now close channels from within Zeus

Feature: Close Channel

---

README.md

The included link has more details on the configuration required to get the build running on Windows for Android.

Updated README.md for some helpful Android setup steps

---

Navigation.ts
stores/BalanceStore.ts
stores/ChannelsStore.ts
stores/InvoicesStore.ts
stores/NodeInfoStore.ts
stores/PaymentsStore.ts
stores/SettingsStore.ts
stores/TransactionsStore.ts
views/BTCPayConfigQRScanner.tsx
views/Settings.tsx

The Settings page now has a button to scan BTCPay configs. Just go to Settings > Services > LND Rest in your BTCPay instance and getting a QR code to scan in Zeus

Feature: BTCPayServer Support

---

android/app/build.gradle
android/app/src/main/java/com/zeus/MainApplication.java
android/settings.gradle
ios/zeus.xcodeproj/project.pbxproj
package-lock.json
package.json
views/Wallet/MainPane.tsx

 Design: Linear Gradient and white buttons on the Main Pane

---

models/OpenChannelRequest.ts
views/OpenChannel.tsx

this was causing some Channel Opens to fail

Bug fix: min_confs to number

---

Navigation.ts
models/NodeInfo.ts
views/NodeInfo.tsx
views/Wallet/MainPane.tsx

You can now pull up your Node information and URIs to send to people to connect to you

Feature: Node Info view

---

stores/BalanceStore.ts
stores/NodeInfoStore.ts
views/Wallet/MainPane.tsx

This should help people diagnose their connection problems better

Feature: Better error messages for connecting to you node

---

android/app/BUCK
android/app/build.gradle
android/app/src/main/AndroidManifest.xml
android/app/src/main/java/com/zeus/MainActivity.java
android/app/src/main/java/com/zeus/MainApplication.java
android/app/src/main/java/com/zeus/extensions/CustomClientFactory.java

com.zeus -> com.zeusln.zeus

---

stores/UnitsStore.ts

Plus fix a bug that would display number sat values as sat, instead of sats

Feature: Split up sat denominated values with commas

---

views/Wallet/Channels.tsx
views/Wallet/Invoices.tsx
views/Wallet/Payments.tsx
views/Wallet/Transactions.tsx

Hopefully this fixes some related scrolling issues where some users are unable to press items at the end of lists

Design/Bug Fix: Remove padding between button group and lists on the main Wallet view

---

stores/InvoicesStore.ts
views/Receive.tsx

The last invoice you created would linger on the Receive view

Bug Fix: Properly clear out newly generated invoices

---

android/app/build.gradle
components/BalanceSlider.tsx
components/CopyButton.tsx
ios/zeus/Info.plist
package-lock.json
package.json
stores/ChannelsStore.ts
typings/react-native-camera-kit/index.d.ts
utils/DateTimeUtils.ts
views/Channel.tsx
views/OpenChannel.tsx
views/PaymentRequest.tsx
views/Receive.tsx
views/Send.tsx
views/SendingLightning.tsx
views/SendingOnChain.tsx
views/Settings.tsx
views/Wallet/Channels.tsx
views/Wallet/Invoices.tsx
views/Wallet/MainPane.tsx
views/Wallet/Payments.tsx
views/Wallet/Transactions.tsx
views/Wallet/Wallet.tsx

-Feature: Channels show remote node alias
-Feature: Channels visually display local/remote balance ratio
-Feature: DateTimeUtils
-Maintenance: Upgrade react-native 0.58.3 -> 0.59.3
-Maintenance: Upgrade react-native-elements 0.19.1 -> 1.1.0

v0.0.9 mega pr

---

package.json
patches/rnck-build.gradle.patch

RNCameraKit needs a build.gradle upgrade to build succesfully

Android release patch

---

App.tsx
components/FeeTable.tsx
package-lock.json
package.json
stores/FeeStore.ts
stores/Stores.ts
typings/react-native-data-table/index.d.ts
utils/FeeUtils.test.ts
utils/FeeUtils.ts
views/OpenChannel.tsx
views/Send.tsx
views/SendingOnChain.tsx

Initial WhatTheFee.io implementation

---

views/Invoice.tsx
views/Wallet/Invoices.tsx

Changes the display of invoices so that, if they have been settled, the amount displayed is the actual settled amount. All other times, the original value of the invoice is displayed.

Display actual amount paid if invoice is settled.

---

android/app/build.gradle
android/app/src/main/java/com/zeus/MainApplication.java
android/settings.gradle
components/QRCodeScanner.tsx
package.json
views/AddressQRScanner.tsx
views/BTCPayConfigQRScanner.tsx
views/LNDConnectConfigQRScanner.tsx
views/NodeQRScanner.tsx

I'm hoping this code will make the app degrade nicely to the internal QR code scanner if no zxing-whatever-capable reader apps are present, but didn't test that yet. Will wait for feedback.
Also I don't know how this will work on iPhone, but I expect it to be fallback as well.

Invoke an external QR code reader.

---

stores/InvoicesStore.ts
views/PaymentRequest.tsx

-Handle payment request lookup failures
-Clear existing payment request details on failure
https://github.com/ZeusLN/zeus/issues/130

Gracefully handle payment request lookup failures

---

views/PaymentRequest.tsx

https://github.com/ZeusLN/zeus/issues/113

Fix issue where buttons get cut off on the Lightning Invoice view

---

utils/NodeUriUtils.test.ts
utils/NodeUriUtils.ts
views/NodeQRScanner.tsx
views/OpenChannel.tsx
views/Settings/Nodes.tsx

Open Channel view: Suggest import of node URI from clipboard

---

views/Wallet/MainPane.tsx

Main Pane: Point 'Send' arrow up

---

components/QRCodeScanner.tsx
utils/NodeUriUtils.test.ts
utils/NodeUriUtils.ts
views/AddressQRScanner.tsx
views/NodeQRScanner.tsx
views/OpenChannel.tsx

Don't leave user on the Send screen with the single input, take them to the payment request view or the send on-chain view

Improve Send/Scan workflow

---

views/Wallet/Wallet.tsx

LN Payments - Invoices - On-chain transactions - Channels

Switch main view tab order

---

views/SendingLightning.tsx

Often times the screen would go white when trying to send an LN payment. Also added the 'Go to Wallet' button for every scenario

ZEUS-154: Sending screen: catch routing failure

---

stores/NodeInfoStore.ts
utils/RESTUtils.ts

Get my node info

---

models/Payment.ts

return 0 if fee not returned from API

Payment> set fallback fee

---

views/Receive.tsx

see https://github.com/ZeusLN/zeus/issues/168

ZEUS-168: Fix cutoff issues on Receive view

---

stores/InvoicesStore.ts
utils/RESTUtils.ts
views/PaymentRequest.tsx

lnd: Lightning fee estimates

---

android/app/src/main/AndroidManifest.xml
ios/zeus/AppDelegate.m
ios/zeus/Info.plist
views/Wallet/Wallet.tsx

Prompt Zeus to open if you come accross a bitcoin, lightning, or lnurl link in your webbrowser

Add basic linking

---

android/app/build.gradle

...retag 0.2.1 after merge
Else F-Droid can't build.
Ref: https://gitlab.com/fdroid/fdroiddata/-/merge_requests/6428/diffs#diff-content-cfb6f1b11aaaa01cc4ceaee3c0e20dfb89b00c1d

Keep versionName and Tag consistent

---

stores/ChannelsStore.ts
utils/RESTUtils.ts
views/Channel.tsx

Needed for lnd users that want to close a channel when the counter-party is inactive

Force close support

---

views/Settings/AddEditNode.tsx

for those with shorter devices

Turn Node Configuration Screen to scroll view

---

Navigation.ts
views/OpenChannel.tsx
views/Settings.tsx
views/Settings/About.tsx

About page

---

views/OpenChannel.tsx

Upgrade Open Channel view

---

utils/AddressUtils.test.ts
utils/AddressUtils.ts

see https://github.com/ZeusLN/zeus/issues/317

handle extra params on BTC addresses

---

ios/zeus/Info.plist

see https://github.com/ZeusLN/zeus/issues/316

Modify iOS security params

---

models/ForwardEvent.ts
stores/ChannelsStore.ts
stores/FeeStore.ts
utils/RESTUtils.ts
views/NodeInfo.tsx
views/Wallet/Wallet.tsx

lnd: Forwarding History

---

utils/LndConnectUtils.test.ts
utils/LndConnectUtils.ts

macaroons were not being handled properly unless they were the first param in the string

Fix lndconnect processing

---

backends/Eclair.ts
backends/LND.ts
backends/LndHub.ts
utils/handleAnything.ts
views/LnurlPay/LnurlPay.tsx
views/Send.tsx

Relates to issue: **ZEUS-353**

 Bug fix: lnd: on-chain txs listed in reverse order

---

README.md

Corrects link to Raspibolt Zeus over Tor

Updated links for Raspibolt resources.

---

views/Wallet/MainPane.tsx

Relates to issue: **ZEUS-373**

Translations: make sure buttons on Main Pane are translated

---

backends/Eclair.ts
backends/Spark.ts
stores/ChannelsStore.ts
stores/FeeStore.ts
views/Wallet/MainPane.tsx

Fixes https://github.com/ZeusLN/zeus/issues/382
Partially fixes https://github.com/ZeusLN/zeus/issues/381 (except c-lightning-REST)
Supersedes https://github.com/ZeusLN/zeus/pull/380 (because I had to fix it in my own way -- basically changing the button render condition slightly -- it would be impossible to test).
* verify that `package.json` and `package-lock.json` have …

A handful of bugfixes in Éclair and Spark

---

components/SetFeesForm.tsx
locales/en.json
stores/FeeStore.ts

Relates to issue: [**ZEUS-339**](https://github.com/ZeusLN/zeus/issues/339)

Fee Rates: remove confusing mili msat label in favor of PPM

---

android/app/build.gradle
ios/zeus.xcodeproj/project.pbxproj
package-lock.json
package.json

v0.4.0 version bump

---

README.md
utils/LndConnectUtils.ts

Code signing + LndConnectUtils params fix

---

android/gradle/wrapper/gradle-wrapper.properties

Android: bump gradle 5.5 -> 6.3

---

backends/LndHub.ts
backends/Spark.ts
package.json
utils/AddressUtils.test.ts
utils/AddressUtils.ts
utils/VersionUtils.test.ts
utils/VersionUtils.ts

See https://github.com/btcpayserver/btcpayserver/issues/2110 for more context

Add support for all bech32 QR code schemes

---

README.md

Fix F-Droid link in README

---

stores/InvoicesStore.ts

Fixes https://github.com/ZeusLN/zeus/issues/401.

fix lnurl when callback already contains querystrings.

---

stores/UnitsStore.ts

UI: Remove gap between fiat currency symbols and amounts

---

backends/LND.ts

Data was not getting refreshed when using Tor because the calls weren't cleared out from the stack on returned response.

Fix sticky data when using Tor

---

android/settings.gradle

F-Droid: add react-native-tor to Android settings.gradle

---

views/SendingLightning.tsx

Some of the APIs return these values as blank strings.

Fix false positives when sending LN payments

---

components/HopPicker.tsx
utils/PrivacyUtils.ts
views/Channel.tsx
views/Invoice.tsx
views/NodeInfo.tsx
views/Payment.tsx
views/Settings/Nodes.tsx
views/Transaction.tsx
views/Wallet/Channels.tsx
views/Wallet/Invoices.tsx
views/Wallet/MainPane.tsx
views/Wallet/Payments.tsx
views/Wallet/Transactions.tsx
views/Wallet/Wallet.tsx

Relates to issue: [**ZEUS-338**](https://github.com/ZeusLN/zeus/issues/338)

Refactor PrivacyUtils

---

stores/TransactionsStore.ts

Relates to issue: https://github.com/ZeusLN/zeus/issues/418
Fixes false failure on CLightning.

fixes issue #418

---

views/Settings/AddEditNode.tsx

Relates to issue: [**ZEUS-502**](https://github.com/ZeusLN/zeus/issues/502)

Hide Cert Verification buttons when built-in Tor is used

---

views/Receive.tsx

iOS: Receive: Fix invoice toggles

---

components/Amount.tsx
components/Channels/ChannelItem.tsx
components/Channels/ChannelsHeader.tsx
components/LayerBalances/index.tsx
components/Value.tsx
components/text/Body.tsx
stores/FiatStore.ts
stores/UnitsStore.ts
views/Wallet/MainPane.tsx

A `<Value />` component for displaying values throughout the app.
This needs some cleanup and would love to chat if there's anything I'm doing here that could be simpler / more straightforward.
Also it should be pretty straighforward to rewrite the existing `getAmount` method based on the new logic of `getUnformattedAmount` method but since I believe we can deprecate `getAmount` eventually, so not sure if that's necessary.
Another thing this component could be set up to support is displaying bytes / vbytes. Didn't bother with that for now but should be easy addition.
Also, in addition to various rules about left / right and spacing for monies, there are also rules about commas:
https://fastspring.com/blog/how-to-format-30-currencies-from-countries-all-over-the-world/
For instance here's …

Amount component

---

locales/en.json
utils/AddressUtils.test.ts
utils/AddressUtils.ts
utils/handleAnything.ts

https://lightningaddress.com/
https://github.com/andrerfneves/lightning-address/blob/master/README.md

Add support for Lightning Addresses (LNURL Pay)

---

backends/LND.ts
components/FeeBreakdown.tsx
stores/FeeStore.ts
views/Channels/Channel.tsx

Fee rate was display as 10x bigger than it actually was.

Fix display of fee rate

---

utils/AddressUtils.test.ts

Add Bech32m - P2TR address validation tests

---

package-lock.json
package.json

Previous PR submitted for this but making a new one to keep it clean. Evan requested that we make graceful-fs a dev dependency and install latest version. Some people were running into issues with this on newer machines running Android.

Add graceful-fs as dev dependency and update to latest version

---

views/PaymentRequest.tsx

Relates to issue: [**ZEUS-585**](https://github.com/ZeusLN/zeus/issues/585)

 ZEUS-585: Back button on Lightning Invoice screen just reloads invoice

---

components/QRCodeScanner.tsx

Relates to issue: [**ZEUS-578**](https://github.com/ZeusLN/zeus/issues/578)

ZEUS-578: Add QRCodeScanner cache

---

views/PaymentRequest.tsx

Relates to issue: [**ZEUS-646**](https://github.com/ZeusLN/zeus/issues/646)

Remove ability to pay custom amount on invoices

---

components/DropdownSetting.tsx

Relates to issue: [**ZEUS-639**](https://github.com/ZeusLN/zeus/issues/639)

Android: Fix flickering when adding node info

---

views/Wallet/Wallet.tsx

https://user-images.githubusercontent.com/1878621/145908759-4febb414-4780-496f-a9fb-f580d89312fb.mov

Add swipe up ability to Activity caret

---

components/SuccessErrorMessage.tsx
views/IntroSplash.tsx
views/LnurlPay/Metadata.tsx
views/OpenChannel.tsx
views/Send.tsx
views/Settings/AddEditNode.tsx
views/Settings/SignVerifyMessage.tsx

Success/Error Message component + UI Enhancements

---

Navigation.ts
components/QRCodeScanner.tsx
views/AddressQRScanner.tsx
views/Lockscreen.tsx
views/PaymentRequest.tsx
views/Wallet/Wallet.tsx

-Lockscreen
New styles (Buttons + Error message component)
Make sure backing up in the app doesn't drop you off on the black Lockscreen
-QR Code scanner
Handle cache bug

Navigation enhancements

---

stores/UnitsStore.ts
views/Invoice.tsx
views/Payment.tsx
views/PaymentRequest.tsx
views/Transaction.tsx

Update to use `Amount` and `KeyValue` components

Update Invoice, Payment, Tractions views

---

views/Receive.tsx
views/Settings/AddEditNode.tsx

Receive: update styling

---

components/Channels/ChannelsHeader.tsx
views/Channels/ChannelsPane.tsx

https://user-images.githubusercontent.com/1878621/150904694-6fc5680c-53f5-4b5f-bc1b-a7e09d3d7bcb.mov

Collapsible channels donut

---

stores/SettingsStore.ts

On the currency page, fixed 'Austrlian Dollar' typo

Australian Dollar typo fix

---

views/Routing/Routing.tsx

- make sure scroll list doesn't cut off any items
- use ErrorMessage component on fetch error

Routing view enhancements

---

android/app/src/main/AndroidManifest.xml

App doesn't render properly in landscape.

Android: Enforce portrait mode all the time

---

stores/FiatStore.ts

Should use standard comma separators

Fix format of Israeli New Shekel

---

backends/CLightningREST.ts
backends/LND.ts
stores/TransactionsStore.ts
utils/RESTUtils.ts
views/PaymentRequest.tsx
views/Send.tsx

Troubleshooting keysends for LND v0.14+
So far:
- Removed old `v1` endoint, always run through `/v2/router/send`
- Fixed timeout to 60s (pertinent to `react-native-tor` work we'll do later this week or next)
- Removed timeout field from view

Keysend troubleshooting

---

README.md

Updated README image

---

.eslintrc.js
backends/CLightningREST.ts
views/Channels/Channel.tsx
views/LnurlAuth.tsx
views/LnurlChannel.tsx
views/Send.tsx
views/Settings/Nodes.tsx

See https://eslint.org/docs/rules/object-shorthand

Add object shorthand to eslint rules

---

views/Settings/AddEditNode.tsx

Node config: go to Nodes view on safe

---

android/app/src/main/AndroidManifest.xml
ios/zeus/Info.plist
utils/LinkingUtils.ts
views/Lockscreen.tsx
views/Wallet/Wallet.tsx

Fixes https://github.com/ZeusLN/zeus/issues/640. Also handles linking when user has a passphrase enabled

Create LinkingUtil and fix linking on Android

---

views/Send.tsx

Autocorrect on this field was causing some jumping around on the cursor and text input

Send: make sure destination field doesn't autocorrect

---

components/TextInput.tsx
views/Lockscreen.tsx

Lockscreen enhancements

---

components/TextInput.tsx
views/Lockscreen.tsx

TextInput: add support for secure text entry

---

views/Activity/Activity.tsx
views/Activity/ActivityFilter.tsx
views/Invoice.tsx
views/Payment.tsx
views/Transaction.tsx

This PR consists of two components:
-[Ensure back button on activity items returns user back to Activity view](https://github.com/ZeusLN/zeus/commit/8be41bbf73aa3e9e78665a74901f8c6398e87f46)
-[Ensure activity is reloaded when returning to Activity view from Activity Filters view](https://github.com/ZeusLN/zeus/commit/39d28b3ae5e31760c141c05e91025aca703bfaf8)

Activity Navigation

---

views/Activity/Activity.tsx
views/Activity/ActivityFilter.tsx
views/Channels/Channel.tsx
views/Invoice.tsx
views/NodeInfo.tsx
views/OpenChannel.tsx
views/Payment.tsx
views/Receive.tsx
views/Routing/Routing.tsx
views/Routing/RoutingEvent.tsx
views/Routing/SetFees.tsx
views/Settings/AddEditNode.tsx
views/Settings/Currency.tsx
views/Settings/Help.tsx
views/Settings/Language.tsx
views/Settings/Nodes.tsx
views/Settings/Privacy.tsx
views/Settings/Security.tsx
views/Settings/Settings.tsx
views/Settings/SignVerifyMessage.tsx
views/Settings/Theme.tsx
views/Transaction.tsx
views/UTXOs/CoinControl.tsx
views/UTXOs/UTXO.tsx

Remove all bottom borders and make them the same color as the theme background

Update header styles

---

locales/en.json
views/Settings/AddEditNode.tsx

Tweak cert warning modal

---

views/PaymentRequest.tsx

We recently moved LND to use the new `SendPaymentV2` endpoint. This endpoint sets the fee limit to 0 if not specified. This PR moves the fee limit field out from under the AMP group of settings to underneath the estimated fee, and sets the default limit to 10 sats.
This PR also removes the timeout field as we have it hardcoded to one minute now to accommodate Tor users.

LND: set default fee limit

---

views/Send.tsx

Let `Amount` component handle null values

Send+Receive: unify rate behavior

---

utils/handleAnything.ts

A few tricks to optimize the handleAnything function. Mainly, we must check first if the value is a node URI BEFORE we check to see if it is a lightning address because the checking is stricter for node URIs than lightning addressees. Previous set-up was causing crashes on the main camera when scanning node URIs.

Optimize handleAnything

---

backends/LND.ts

Allow LND users to pay their own invoices

LND: allow self payment

---

components/Button.tsx
components/CollapsedQR.tsx
views/OpenChannel.tsx
views/Send.tsx
views/SendingLightning.tsx
views/SendingOnChain.tsx
views/Settings/AddEditNode.tsx

This PR updates styles on buttons throughout the app, making the `Button` component more dynamic with more overrides.
This PR also updates styling on the `SendingOnChain` and `SendingLightning` views and adds removes auto-correct from the host fields on the `AddEditNode` view.

Update button styles

---

package-lock.json
package.json

We were previously pointing to the feature branch

Bump react-native-tor to v0.1.8

---

components/SetFeesForm.tsx

Relates to issue: [**ZEUS-838**](https://github.com/ZeusLN/zeus/issues/838)

SetFeesForm: remove preset values

---

backends/CLightningREST.ts
stores/TransactionsStore.ts
views/PaymentRequest.tsx

Relates to issue: **[ZEUS-846](https://github.com/ZeusLN/zeus/issues/846)**

added max fee percent for c-lightning

---

android/app/build.gradle
android/app/src/main/java/com/zeus/MainApplication.java
android/settings.gradle
ios/Podfile.lock
locales/en.json
package-lock.json
package.json
views/Wallet/Wallet.tsx

A better reset mechanism for when the Tor connection stalls out

React Native Restart

---

stores/ChannelsStore.ts
views/Wallet/MainPane.tsx
views/Wallet/Wallet.tsx

Speeding up wallet refresh and fixing channel outbound/inbound totals

---

Navigation.ts
locales/en.json
stores/SettingsStore.ts
views/Settings/About.tsx
views/Settings/Olympians.tsx
views/Settings/SetPassword.tsx
views/Settings/Settings.tsx
views/Wallet/Wallet.tsx

https://user-images.githubusercontent.com/1878621/156861723-c368080b-7ad8-4d1a-a1e6-cc174efdd2f2.mov

Olympian sponsor display in-app

---

locales/en.json
views/Receive.tsx

Relates to issue: [**ZEUS-881**](https://github.com/ZeusLN/zeus/issues/881)
PR also changes memo placeholder

Remove default invoice amount

---

models/ForwardEvent.ts
package-lock.json
package.json
stores/FeeStore.ts
stores/UnitsStore.ts
views/Routing/Routing.tsx

Issue #569. Made a new PR due to a tragic rebase on the other one.

Displaying msats for lnd routing fees

---

.github/ISSUE_TEMPLATE/feature_request.md

Quite a few issues made on issue are for feature requests, figured a template would come in handy.

Create feature request issue template

---

backends/LND.ts
views/PaymentRequest.tsx
views/Receive.tsx

MPP brings great benefits in terms of route finding and privacy. Let's switch it on by default for people.

Put MPP on by default

---

android/app/src/main/AndroidManifest.xml
ios/zeus/Info.plist
package-lock.json
package.json

https://github.com/fiatjaf/lnurl-rfc/blob/luds/17.md

Update js-lnurl and support LUD-17

---

stores/FiatStore.ts
stores/SettingsStore.ts
stores/UnitsStore.ts

https://github.com/ZeusLN/zeus/issues/891

Gracefully fail missing currencies & disable ISK

---

views/Receive.tsx
views/Send.tsx

Also properly handles settings of amount on Send view

Fiat conversion: handle commas

---

components/TextInput.tsx
views/Receive.tsx
views/Send.tsx

Make it more clear to users that they can toggle units on amount fields on the `Send` and `Receive` views.

TextInput: add toggleable prefix and suffix

---

components/CollapsedQR.tsx

Decrease QR size for low res phones

---

utils/AddressUtils.ts
views/Settings/AddEditNode.tsx

Let's not encourage users to use an LNDHub instance that's not run by someone they know.

Remove default LNDHub host

---

locales/en.json
views/OpenChannel.tsx

OpenChannel: don't announce channels by default

---

components/CollapsedQR.tsx

CollapsedQR: fix color of icon on Hide/Show button

---

views/SparkQRScanner.tsx

SparkQRScanner: fix imports to include implementation

---

README.md

Minor non-app-functional adjustment to add a link to Citadel (https://runcitadel.space/) to Full Node Solutions
- [ X] Other
- [] I’ve run `npm run tsc` and made sure my code compiles correctly
- [X ] N/A
* verify that dependencies are installed for both iOS and …

Update README.md w/ new node solution

---

views/Wallet/Wallet.tsx

This PR hides the new Default Pane when there's a connection error. Still need to make a new error screen though - ours is ugly.

Wallet: fix error display for new Default Pane

---

locales/en.json

Relates to issue: [**ZEUS-1048**](https://github.com/ZeusLN/zeus/issues/1048)

Routing: change label from 'You received' to 'Fee received'

---

utils/UnitsUtils.test.ts
utils/UnitsUtils.ts
views/Wallet/DefaultPane.tsx

This PR adds decimal placeholders when a user presses the decimal button on the new Default Pane.

DefaultPane: add decimal placeholder

---

components/Button.tsx

Center button text by removing nonexistent icons. Before and after:

Center the text on buttons

---

views/PaymentRequest.tsx

Fix toggle position

---

stores/TransactionsStore.ts
views/PaymentRequest.tsx

Relates to issue: https://github.com/ZeusLN/zeus/issues/1090

Change fee limit

---

locales/en.json
stores/ActivityStore.ts
views/Activity/ActivityFilter.tsx

Relates to issue: **#1011**
Added a minimum amount filter to the activity filter

Add minimum amount filter

---

views/Send.tsx

views/Send: minor refactoring and typing improvment

views/Send: minor refactoring and typing improvment

---

backends/LND.ts
stores/FeeStore.ts

Relates to issue: [**ZEUS-1073**](https://github.com/ZeusLN/zeus/issues/1073)
Previous PR #991, handled this, but only for LND.

ZEUS-1073: handle commas when setting channel fees

---

stores/SettingsStore.ts
utils/ThemeUtils.ts

Added:
- Blacked Out
- Scarlet

New Themes: Blacked Out + Scarlet

---

stores/SettingsStore.ts
views/Settings/Settings.tsx

- Update display names of interfaces
- Settings: trim margins on node identicon to leave more space for labels
- Settings: fix width of dividers

Node interface display tweaks

---

stores/ActivityStore.ts

Previously streaming updates would disregard and reset all filters. Now filters are acknowledged. If an streaming update does not meet the filter conditions, it will not be shown.

Activity: acknowledge filters when handling streaming updates

---

components/Button.tsx
views/Wallet/DefaultPane.tsx

Default Pane: make action buttons uniform height

---

stores/SettingsStore.ts
utils/ThemeUtils.ts
views/Settings/AddEditNode.tsx

Added Black & Red theme "Deadpool"

Add Deadpool theme

---

components/Amount.tsx
components/Channels/ChannelItem.tsx
components/Channels/ChannelsHeader.tsx
components/Conversion.tsx
components/FeeBreakdown.tsx
components/LayerBalances/index.tsx
stores/SettingsStore.ts
stores/UnitsStore.ts
utils/AddressUtils.ts
utils/FeeUtils.test.ts
views/Activity/Activity.tsx
views/Channels/Channel.tsx
views/Invoice.tsx
views/Payment.tsx
views/PaymentRequest.tsx
views/Receive.tsx
views/Routing/RoutingEvent.tsx
views/Routing/RoutingHeader.tsx
views/Routing/RoutingListItem.tsx
views/Send.tsx
views/Transaction.tsx
views/UTXOs/CoinControl.tsx
views/UTXOs/UTXO.tsx
views/Wallet/DefaultPane.tsx
views/Wallet/MainPane.tsx

This is a new component called `Conversion`. When fiat rates are enabled it will show the sats amount when fiat is the displayed units, and the fiat amount when sats or BTC is the displayed units.
It is used on the following view:
- Default pane
- Main (balance) pane

Component: Conversion

---

views/Settings/AddEditNode.tsx

Relates to issue: [**ZEUS-1181**](https://github.com/ZeusLN/zeus/issues/1181)

Bug fix: LNC: spaces at end of pairing phrase auto-delete

---

components/Channels/ChannelsHeader.tsx

Allows for ChannelsHeader to apply custom theme colors to legend.

fix for applying custom themes to ChannelsHeader

---

App.tsx
components/layout/AppContainer.tsx
package.json
yarn.lock

Updates to resolve bug with header icons / buttons in iPhone 14 Plus / Pro / Pro Max.
Changed View container component to SafeAreaView in App. Updated react native elements to 3.4.2 to resolve padding issue with header component.

Fix for iPhone 14 Plus / Pro / Pro Max header bug

---

backends/CLightningREST.ts
backends/Eclair.ts
backends/LND.ts
backends/LightningNodeConnect.ts
backends/LndHub.ts
backends/Spark.ts
components/LayerBalances/index.tsx
stores/InvoicesStore.ts
utils/RESTUtils.ts

Relates to issue: [**ZEUS-1217**](https://github.com/ZeusLN/zeus/issues/1217)
This adds a new function in `RESTUtils` called `supportsOnchainReceiving` which defines whether or not a backend supports receiving payments on-chain.
Previously, we had a check in place, on the LNDHub host string, to prevent LNbank users from seeing the on-chain balance pane or attempting to generate an on-chain address. This new function is more easy to grok, and only needs to be defined in one place. …

RESTUtils: add supportsOnchainReceiving definition

---

views/LnurlAuth.tsx

LNURL-auth: update display to use Success and ErrorMessage components

---

views/LnurlPay/LnurlPay.tsx
views/Receive.tsx

Relates to issue: [**ZEUS-1221**](https://github.com/ZeusLN/zeus/issues/1221)
This PR fixes a number of LNURL issues:
- As detailed in ZEUS-1221, fixed amount LNURLw requests of msat amounts could not be processed and initiated
- LNURLp requests previously rounded to the nearest sat
- Display of successfully created LNURLw invoices did not display the full message (chopped up during refactoring for BIP-21/Unified QRs) …

LNURL patches

---

components/UTXOPicker.tsx

Relates to issue: [**ZEUS-1226**](https://github.com/ZeusLN/zeus/issues/1226)

UTXOPicker: fix display of UTXOs

---

views/Settings/Settings.tsx

Settings: remove clearnet/Tor display to prevent text cutoff

---

Navigation.ts
components/WalletHeader.tsx
utils/handleAnything.ts
views/BTCPayConfigQRScanner.tsx
views/CLightningRestQRScanner.tsx
views/LNDConnectConfigQRScanner.tsx
views/LightningNodeConnectQRScanner.tsx
views/Send.tsx
views/Settings/AddEditNode.tsx
views/Settings/Display.tsx
views/Settings/NodeConfiguration.tsx
views/Settings/Nodes.tsx
views/Settings/Privacy.tsx
views/SparkQRScanner.tsx
views/handleAnythingQRScanner.tsx

Relates to issue: [**ZEUS-446**](https://github.com/ZeusLN/zeus/issues/446)
This PR:
- adds BTCPay, LNC, c-lightning-REST connection strings to `handleAnything`
- adds the `handleAnythingQRScanner` to the `NodeConfiguration` view

handleAnything: add BTCPay, LNC, c-lightning-REST strings

---

components/Switch.tsx
utils/ThemeUtils.ts
views/Activity/ActivityFilter.tsx
views/Channels/Channel.tsx
views/OpenChannel.tsx
views/PaymentRequest.tsx
views/Receive.tsx
views/Send.tsx
views/Settings/Display.tsx
views/Settings/NodeConfiguration.tsx
views/Settings/Privacy.tsx
views/Settings/Security.tsx

New `Switch` component to maintain uniform styling throughout the app

component: Switch

---

components/DropdownSetting.tsx
views/Settings/NodeConfiguration.tsx

https://github.com/ZeusLN/zeus/issues/1236

components/DropdownSetting: simplify display calculation

---

components/LayerBalances/LightningSwipeableRow.tsx
components/LayerBalances/OnchainSwipeableRow.tsx
stores/SettingsStore.ts
utils/ThemeUtils.ts

new Themes: Mighty, Green

---

components/TextInput.tsx
locales/en.json
views/LnurlPay/LnurlPay.tsx
views/Send.tsx

Relates to issue: [**ZEUS-1238**](https://github.com/ZeusLN/zeus/issues/1238)
Keysend
LNURL-pay

Keysend + LNURL-pay: allow users to specify amount in BTC and fiat

---

models/Invoice.ts

Relates to issue: **[ZEUS-1240](https://github.com/ZeusLN/zeus/issues/1240)**

bug fix: c-lightning-REST: keysends received show 0 amount

---

views/Channels/Channel.tsx

Close Channel: add ability to get rate suggestions from Mempool.space

---

views/EditFee.tsx

Relates to issue: [**ZEUS-1273**](https://github.com/ZeusLN/zeus/issues/1273)

views/EditFee: fix display on iOS

---

views/NodeInfo.tsx

Relates to issue: [**ZEUS-1271**](https://github.com/ZeusLN/zeus/issues/1272)
Return to previous screen instead of going right to the `Wallet` view

views/NodeInfo: fix back button behavior

---

views/Wallet/KeypadPane.tsx

Relates to issue: [**ZEUS-1271**](https://github.com/ZeusLN/zeus/issues/1271)

views/Wallet/KeypadPane: allow only one decimal

---

backends/LND.ts
components/CollapsedQR.tsx
ios/zeus.xcodeproj/project.pbxproj
locales/en.json
views/Receive.tsx

- Give iOS app full support for iPad resolutions
- Change header from `Receive` to `Pay` when in POS mode
- Decrease padding on top of ZEUS logo
- Change button label from `Receive via NFC` to `Pay via NFC` when in POS mode
- Optimize polling of invoices and transactions

POS: update Pay+Paid display & add iPad resolutions

---

stores/InvoicesStore.ts

Relates to issue: [**ZEUS-1295**](https://github.com/ZeusLN/zeus/issues/1295)

Unified Invoice: don't display until both on-chain + LN invoices are loaded

---

components/WalletHeader.tsx

WalletHeader: SettingsButton: go to Nodes on long-press for fast switching

---

stores/SettingsStore.ts

Settings: Privacy: turn auto-read from clipboard off by default

---

views/Settings/NodeConfiguration.tsx

Relates to issue: [**ZEUS-1321**](https://github.com/ZeusLN/zeus/issues/1321)

ZEUS-1321: LNDHub: don't allow saving of account w/o creds

---

components/QRCodeScanner.tsx

QRCodeScanner: fix position of button overlay

---

assets/images/SVG/Add.svg
components/WalletHeader.tsx
views/Channels/ChannelsPane.tsx

Channels: turn header toggle into button

---

locales/en.json
stores/SettingsStore.ts
views/Wallet/Wallet.tsx

LNDHub: fix login race condition

---

stores/FeeStore.ts
stores/Stores.ts

This PR adds support for testnet fee rate recommendations from Mempool.space

Fee recommendations: add testnet rates from Mempool.space

---

assets/images/SVG/Caret Right.svg
views/PaymentRequest.tsx

Tucks away the settings on the `Payment Request` view for quicker payments and less clutter.

views/PaymentRequest: add Settings toggle

---

stores/FiatStore.ts
stores/SettingsStore.ts
views/Settings/Currency.tsx

Relates to issue: [**ZEUS-1338**](https://github.com/ZeusLN/zeus/issues/1338)
Restores:
🇮🇸 Icelandic Krona (ISK)
Adds:
🇱🇧 Lebanese Pound (LBP)
🇲🇾 Malaysian Ringgit (MYR)
🇺🇦 Ukrainian Hryvnia (UAH)
🇯🇲 Jamaican Dollar (JMD)
🇨🇴 Colombian Peso (COP)
🇲🇽 Mexican Peso (MXN)
🇹🇿 Tanzanian Shilling (TZS)
🇶🇦 Qatari Riyal (QAR)
🇹🇳 Tunisian Dinar (TND)
🇳🇴 Norwegian Krone (NOK)
🇦🇪 United Arab Emirates Dirham (AED)
🇹🇹 Trinidad & Tobago Dollar (TTD)
🇵🇭 Philippine Peso (PHP)
🇮🇩 Indonesian Rupiah (IDR)
🇷🇴 Romanian Leu (RON)
🇨🇩 Congolese Franc (CDF)
🇨🇲🇨🇫🇹🇩🇨🇬🇬🇶🇬🇦 Central African CFA franc (XAF)
🇰🇪 Kenyan Shilling (KES)
🇺🇬 Ugandan Shilling (UGX)
🇿🇦 South African Rand (ZAR)
🇨🇺 Cuban Peso (CUP)
🇩🇴 Dominican Peso (DOP)
🇧🇿 Belize Dollar (BZD)
If you modified or added a …

Fiat currencies: new additions from Yadio

---

components/PinPad.tsx
locales/en.json
stores/SettingsStore.ts
views/Settings/Display.tsx

Adds ability to toggle between standard and big keypad buttons
Big:
Standard:
Settings page:

settings/Display: add option for big keypad buttons

---

views/Activity/Activity.tsx

Relates to issue: [**ZEUS-1322**](https://github.com/ZeusLN/zeus/issues/1322)
iPad:

Activity: show lightning invoice memos

---

components/Screen.tsx

This is required to probably render iOS screens with different elements, at different resolutions.
- x ] N/A

iOS: add SafeAreaView to Screen component

---

components/BalanceSlider.tsx
components/Channels/ChannelItem.tsx
components/HopPicker.tsx

This is a refactor, mainly pertaining to the `BalanceSlider` and `ChannelItem` components to make the style uniform with what's seen on the main `Channels` view:

Refactor: BalanceSlider, ChannelItem, HopPicker

---

locales/en.json
stores/TransactionsStore.ts
views/SendingLightning.tsx

SendingLightning: handle In-Flight payments

---

components/FeeBreakdown.tsx
utils/UrlUtils.ts
views/Channels/Channel.tsx

Relates to issue: *[ZEUS-1437](https://github.com/ZeusLN/zeus/issues/1437)*

Channels: Add Block explorer links

---

views/Activity/Activity.tsx

Activity: Fix lagging issue

---

views/Send.tsx

In the recent PR to add support for Tor LN addresses we added a new loading indicator to `Send` view to indicate to the user that the address was being loaded. The change added a regression where users were no longer easily able to enter in lightning addresses into the destination field due to re-render.
This PR fixes that regression and moves the loading indicator to the top right corner.
* verify …

views/Send: fix loading icon position + input issue

---

components/KeyValue.tsx

Relates to issue: **ZEUS-1452**
Allow the user to copy information from an invoice f.e: Memo, Hash, Pre-image, etc.

Add ability to copy on invoice details screen

---

.eslintrc.js
backends/LNC/credentialStore.ts
utils/handleAnything.ts
views/Wallet/KeypadPane.tsx

Enable eslint `no-unreachable`. Remove current no unreachable code.

eslint: remove unreachable code

---

models/Invoice.ts
models/Payment.ts

Relates to issue: https://github.com/ZeusLN/zeus/issues/1464
Fix few compatibility issues with CLN 23.05 (and older).
Before fix, activity not working at all (app crashes). Now working.
And or invoice amounts was 0 (I think this bug maybe exist since CLN v0.12.0, with change https://github.com/ElementsProject/lightning/pull/5306):
I still unable to open specific invoice (nothing happens when tapping on invoice), but I'm not sure it's related.  

Fix compatibility issues with CLN 23.05 in activity

---

views/Wallet/Wallet.tsx

Regression from [this PR](https://github.com/ZeusLN/zeus/pull/1470). I should have caught it in code review.

iOS: FaceID fix

---

stores/ChannelsStore.ts

There were awaits of enrichChannels() calls marked as unnecessary because there was a missing await within enrichChannels(). Might have lead to problems since the returned channels might not have the right state.

Channels: await node info retrieval in enrichChannels

---

views/Send.tsx

LND does not have full coin control support yet in Zeus

Send: hide UTXOPicker for LND backends

---

package.json
yarn.lock

Relates to issues: [**ZEUS-1115**](https://github.com/ZeusLN/zeus/issues/1115), [**ZEUS-1540**](https://github.com/ZeusLN/zeus/issues/1540)
dep `bolt11` has been updated to add Signet support. Must be tested.

deps: `bolt11` 1.2.7 -> 1.4.1

---

models/Utxo.ts

Relates to issue: [**ZEUS-1532**](https://github.com/ZeusLN/zeus/issues/1532)

CLN-rest: UTXOs: fix display of amounts

---

components/AmountInput.tsx

Relates to issue: [**ZEUS-1527**](https://github.com/ZeusLN/zeus/issues/1527)

ZEUS-1527: On-chain payment request amount not correctly processed on Send view

---

components/AmountInput.tsx

Relates to issue: [**ZEUS-1550**](https://github.com/ZeusLN/zeus/issues/1550)

ZEUS-1550: AmountInput: getSatAmount: handle amounts with comma separator

---

package.json
patches/rnqli-build.gradle.patch
yarn.lock

Revert "deps: `react-native-qrcode-local-image` update and remove patch"

---

components/Sats.tsx
stores/FiatStore.ts
stores/UnitsStore.ts

This fixes #1549 by rounding sat amounts to 3 decimals.
This cannot happen when using LND REST because the balance is provided in sats only. Hence tested with hard-coded balances.
Before:
After:

Round sat amounts to 3 decimals

---

android/build.gradle

Relates to issue: [**ZEUS-1583**](https://github.com/ZeusLN/zeus/issues/1583)
Zeus doesn't operate on versions of Android below 9.0. On 8.0 it will install but crash on startup. Let's ensure that Android 8.0 users are properly informed that Zeus doesn't run on their device.

Android: bump minSdkVersion to 28 (Android 9)

---

components/Channels/ChannelItem.tsx
components/HopPicker.tsx

This fixes #1606.
Also removed an unnecessary condition (showChannelModal).

HopPicker: improve channel selection colors

---

components/PaymentPath.tsx

Localized "Forwarded" and "Fee".

Localized payment path strings

---

stores/ChannelsStore.ts

Open Channel: skip peer connect step if host not specified

---

stores/FiatStore.ts
stores/SettingsStore.ts

https://en.wikipedia.org/wiki/Mauritanian_ouguiya

Currency: 🇲🇷 Mauritanian Ouguiya (MRU)

---

locales/en.json
models/Invoice.ts
views/Invoice.tsx

Invoice: display keysend messages

---

components/Amount.tsx
models/Transaction.ts
views/Activity/Activity.tsx

This PR adds a display of the fee paid in the `Activity` list view:

Activity: display fee in list

---

components/DropdownSetting.tsx
components/OnchainFeeInput.tsx
locales/en.json
stores/FeeStore.ts
stores/SettingsStore.ts
views/EditFee.tsx
views/OpenChannel.tsx
views/Send.tsx
views/Settings/PaymentsSettings.tsx
views/Settings/Privacy.tsx
views/Settings/Settings.tsx

This PR moves the onchain fee input field into its own component `OnchainFeeInput`. The new component fetches rates from Mempool.space automatically, if enabled, and sets your preference as determined by a new settings in Payment settings.
The `EditFee` view will now highlight your preference if applicable.
The `DropdownSetting` component now has a `disabled` prop. …

component: OnchainFeeInput + preferred mempool rate setting

---

models/Payment.ts
models/Transaction.ts
views/Payment.tsx
views/Transaction.tsx

This PR adds a percentage value next to the fee paid amount on both the `Payment` and `Transaction` views.
The percentage will be at max three decimal places, and will remove all trailing zeroes.
This PR also fixes the display of sent on-chain amounts, which were previously including the fee in the amount sent.

Payments + Transactions: display fee percentage next to amount

---

views/Channels/Channel.tsx

[refactor] Channel view: Close Channel: use OnchainFeeInput component

---

components/PaymentPath.tsx
models/Payment.ts
stores/ChannelsStore.ts
views/PaymentPaths.tsx

Relates to issue: [**ZEUS-1638**](https://github.com/ZeusLN/zeus/issues/1638)
https://github.com/ZeusLN/zeus/assets/1878621/f4ce788b-72f3-4b1b-ba6f-8640a1ab1752

ZEUS-1638: Payment Path: always fetch and display alias

---

android/app/build.gradle
android/app/src/main/java/com/zeus/LndMobile.java
android/app/src/main/java/com/zeus/LndMobileScheduledSync.java
android/app/src/main/java/com/zeus/LndMobileScheduledSyncWorker.java
android/app/src/main/java/com/zeus/LndMobileService.java
android/app/src/main/java/com/zeus/LndMobileTools.java
android/app/src/main/java/com/zeus/MobileTools.java
android/build.gradle
lndmobile/LndMobile.d.ts
lndmobile/log.ts

Logs created with hyperlog are not accessible and since hyperlog is outdated and requires deprecated jcenter I removed hyperlog and jcenter in this PR.

Android: Remove hyperlog

---

components/WalletHeader.tsx

Wallet header: Navigate to node selection when pressing on node name

---

views/Activity/ActivityFilter.tsx

Relates to issue: [**ZEUS-1666**](https://github.com/ZeusLN/zeus/issues/1666)
Before:
After:

ZEUS-1666: Change X icon in Filter Activity screen

---

components/LayerBalances/index.tsx

Make 'Lightning' and 'On-chain' in swipeable rows localizable

---

views/SendingLightning.tsx

Relates to issue: [**ZEUS-1667**](https://github.com/ZeusLN/zeus/issues/1667)
The `LnurlPaySuccess` success component will now be hidden unless the payment has returned a success value and no error value.

ZEUS-1667: LNURL Receipt after failed payment

---

utils/Base64Utils.ts

Keysend patch

---

views/Settings/NodeConfiguration.tsx

Ignore white spaces and line breaks that occur in between pasted macaroon chars

---

package.json
utils/handleAnything.test.ts
utils/handleAnything.ts

Created a first test as a starting point. Please review and let me know if this works for you. I will add more tests then.

handleAnything: initial tests

---

locales/en.json

Improve locale: rescan subtitle

Improve locale: rescan subtitle

---

locales/en.json
views/Settings/AddContact.tsx

Fixes: [#1710 ](https://github.com/ZeusLN/zeus/issues/1710)

Contacts: Add ability to delete contacts

---

views/Sync.tsx

Refactors the `Sync` view by adding vertical alignment and adding a action button at the bottom of the page to 'Go back'
Before:
After:

Sync: refactor layout

---

stores/SyncStore.ts
utils/LndMobileUtils.ts
views/Settings/Settings.tsx
views/Wallet/Wallet.tsx

Relates to issue: https://github.com/ZeusLN/zeus/issues/1708
Refactors the sync logic:
- Remove sync pause/resume logic (no longer needed thanks to performance fixes in (https://github.com/ZeusLN/zeus/pull/1726)
- Refactors Mempool.space tip query into own function, `getBestBlockHeight`
- Mempool.space tip query now called every 30 seconds to keep tip data current
- If current block on node exceeds best known block height, call to Mempool.space again. If the call fails. Set the best known block to the node's current block
I have tested this PR with the following types of nodes (please …

refactor: Sync logic

---

views/Activity/Activity.tsx

This has been overlooked in the rework https://github.com/ZeusLN/zeus/pull/1732.

Remove pauseSyncingUpates call from Activity

---

components/OnchainFeeInput.tsx

When "Enable Mempool.space fee suggestions" was disabled, style was broken. When it is enabled, it is fine (before and after this PR).
Before:
After:
After ("Enable Mempool.space fee suggestions" enabled):

Channel View: Fix on-chain fee input style by importing correct TextInput

---

locales/en.json

Improved en locale views.Settings.LightningAddress.statusExplainer2

---

backends/LND.ts
backends/LightningNodeConnect.ts
lndmobile/index.ts
locales/en.json
models/Payment.ts
views/Activity/Activity.tsx
views/Payment.tsx

This will help users who pay ZEUS PAY/Zaplocker payments, hold invoices, or just users with stuck payments, that their payments are in transit.

Activity: display In Transit Payments

---

package.json

Updated some scripts for windows compatibility, added 'ra" script for conenience, added 'gradlew'.
The 'patch' script now explicitely runs the 2 existing patches, so if more patches are added, they need to be added here too.

Updated some scripts for Windows compatibility, added 'ra' and 'gradlew'

---

components/LayerBalances/LightningSwipeableRow.tsx
components/LayerBalances/OnchainSwipeableRow.tsx

With PR #1760 I accidentally deleted styles which are needed for vertical alignment. Readded those now.
Before:
After:

Balance sliders: Readded styles for vertical align

---

views/Wallet/Wallet.tsx

Relates to issue: [**ZEUS-1810**](https://github.com/ZeusLN/zeus/issues/1810)

ZEUS-1810: Refactor store reset trigger upon connection establishment

---

assets/images/SVG/DynamicSVG/LightningSvg.tsx
assets/images/SVG/DynamicSVG/OnChainSvg.tsx
components/LayerBalances/index.tsx

Replace swipeable row icons

---

views/Settings/EmbeddedNode/DisasterRecovery.tsx

DisasterRecovery: Fixed non-uniform UI

---

views/Wallet/Wallet.tsx

Stroke removed, because it is not needed with the new SVG (using stroke will lead to cut off parts of the graphic).

Remove stroke for CaretUp

---

views/Settings/Settings.tsx

- changed receive icon from stroke to fill for CLN backends and fixed margin
- moved currency icon 1 px to left
Before:
After:

Settings: fix minor icon issues

---

utils/ErrorUtils.ts

Before, Zeus didn't display the error screen when there was no localeString. For example in case the CLN macaroon was not correct, instead of an error the wallet screen was displayed in a buggy state (no balance, channels, or any data).

ErrorUtils: Make localeString optional

---

assets/images/SVG/DynamicSVG/AddressSvg.tsx
assets/images/SVG/DynamicSVG/LightningSvg.tsx
assets/images/SVG/DynamicSVG/OnChainSvg.tsx
assets/images/SVG/DynamicSVG/UnifiedSvg.tsx
views/Receive.tsx

QR selector: removed circle and adjusted colors

---

views/Send.tsx

When typing something in the destination text input in Send view, e.g. an LN address, the android keyboard might suggest the address if it was typed before. When you click on the suggestion to paste it in the text input, there is a space char added behind the pasted string. The space char then leads to an invalid LN address error.
So text will be trimmed now. …

Send: Remove leading and trailing space chars from text input for destination

---

views/LnurlPay/LnurlPay.tsx

LnurlPay: Fixed Margin

---

locales/en.json
stores/LightningAddressStore.ts

ZEUS PAY: display error to user when preimage not found on device

---

components/AmountInput.tsx
views/LnurlPay/LnurlPay.tsx

Relates to issue: [**1871**](https://github.com/ZeusLN/zeus/issues/1871)

ZEUS-1871: Payment flow bug fix

---

README.md

Add StartOS guides
Simple README edit, I did not run any tests, etc (other than checking the links), hopefully this is alright for a copy change.

README: add Start9 links

---

components/Amount.tsx
components/text/Body.tsx
views/LnurlPay/LnurlPay.tsx

Fix size of min/max amount for lnurlpay

---

views/Receive.tsx

Fix adding route hints to invoice when requesting from keypad if enabled in settings

---

components/LayerBalances/LightningSwipeableRow.tsx

Relates to issue: [**ZEUS-1858**](https://github.com/ZeusLN/zeus/issues/1858)
Although not explicitly specified in the Unified QR docs or BIP-21 spec, some pieces of software like BTCPay have been using LNURLs for their lightning parameters instead of bolt11 invoices.
This PR adds support for those LNURLs within Unified QRs

ZEUS-1858: Unified QRs: handle LNURLs used as lightning param

---

locales/en.json
models/Payment.ts
stores/ActivityStore.ts
utils/ActivityFilterUtils.ts
views/Activity/Activity.tsx
views/Activity/ActivityFilter.tsx
views/Payment.tsx

Relates to issue: [**ZEUS-1900**](https://github.com/ZeusLN/zeus/issues/1900)
This PR adds logic for LND that loops. through the HTLCs associated with the payment to check and see if they are all failed. If so, display the payment as failed instead of as in-transit. This PR also adds the ability to filter failed payments in the Activity filter. The filter is off by default.
* verify that …

ZEUS-1900: In-transit payments: convert to failed payments

---

components/Channels/FilterOptions.tsx
locales/en.json
stores/ChannelsStore.ts

Relates to issue: [**ZEUS-1476**](https://github.com/ZeusLN/zeus/issues/1476)
This PR adds online and offline filters to the channels list that can be used in combination with the existed announced and unannounced filters.

Channels: Filters: Online/Offline

---

assets/images/SVG/DragDots.svg
locales/en.json
package.json
views/Settings/Nodes.tsx
yarn.lock

Relates to issue: [**ZEUS-1642**](https://github.com/ZeusLN/zeus/issues/1642)
Power users have a growing list of nodes and accounts on their `Nodes` view. Let's give them the ability to re-order their lists by adding a new grip icon to the list items.
https://github.com/ZeusLN/zeus/assets/1878621/303936e1-65b4-4d59-bb21-5f2356f534a4 …

ZEUS-1642: Nodes: add ability to reorder list

---

backends/LightningNodeConnect.ts

Regression added to LNC connections while adding the Read-only wallet label functionality.

LNC: fix supportsLightningSends permission check

---

stores/NodeInfoStore.ts

This is a regression from 363f72abb0640c7fcda7329885923a84ddc3b3a6. Also improved error handling of `getNetworkInfo`.

Fixed connection errors for old connection attempts being shown

---

views/Wallet/Wallet.tsx

Especially Keypad icon (₿) was too small, introduced by https://github.com/ZeusLN/zeus/commit/cfcf6767374bb92b02dcd384b16b51f4e18f0f06.
While at it, also slightly increased ChannelsIcon.
Before:
After:

Harmonize icon sizes in tab navigation

---

views/Settings/AddContact.tsx

Fix description field layout in AddContact view

---

views/Settings/Contacts.tsx

Enabled multiline for search bar, improved margins.

Improve Contacts layout

---

models/Invoice.ts
views/Activity/Activity.tsx

Before (big font and display size set in Android settings):
Before (default font and display size set in Android settings):
After (big font and display size set in Android settings):
After (default font and display size set in Android settings):

Improve activity layout

---

locales/en.json
views/Settings/Contacts.tsx

Contact picker: localize 'To' (recipient)

---

locales/en.json
stores/SettingsStore.ts
views/Order.tsx
views/Settings/PointOfSale.tsx
views/Wallet/StandalonePosKeypadPane.tsx
views/Wallet/StandalonePosPane.tsx
views/Wallet/Wallet.tsx

Relates to issue: [**ZEUS-1947**](https://github.com/ZeusLN/zeus/issues/1947)
Now you can add items to orders that are not tracked by your inventory.

Standalone POS: add optional keypad

---

views/Send.tsx

Send: Margin fix in Contact list

---

stores/FiatStore.ts
stores/SettingsStore.ts

Following are the currencies that have been added in this PR:
- ALL Albanian Lek
- ANG Netherlands Antillean Guilder
- AOA Angolan Kwanza
- BDT Bangladeshi Takka
- BGN Bulgarian Lev
- BHD Bahraini Dinar
- BIF Burundian Franc
- BMD Bermudan Dollar
- BWP Botswanan Pula
- DJF Djiboutian Franc
- DZD Algerian Dinar
- EGP Egyptian Pound
- ETB Ethiopian Birr
- GEL Georgian Lari
- GHS Ghanaian Cedi
- GNF Guinean Franc
- HNL Honduran Lempira
- IRR Iranian Rial
- JOD Jordanian Dinar
- KGS Kyrgystani Som
- KZT Kazakhstani Tenge
- LKR Sri Lankan Rupee
- MAD Moroccan Dirham
- MGA Malagasy Ariary
- NAD Namibian Dollar
- NPR Nepalese Rupee
- PAB Panamanian Balboa
- PEN Peruvian Sol
- PKR Pakistani Rupee
- RSD Serbian Dinar
- RWF Rwandan Franc
- UZS Uzbekistan Sum
- VND Vietnamese Dong

Added 33 new currencies

---

Navigation.ts
components/CopyButton.tsx
components/SuccessErrorMessage.tsx
locales/en.json
models/Transaction.ts
stores/Stores.ts
stores/TransactionsStore.ts
utils/UrlUtils.ts
views/RawTxHex.tsx
views/Transaction.tsx

This PR adds a display of the raw transaction hex in every transaction on the activity section of the app. There is a button to copy the hex to clipboard.
This is helpful, particularly for embedded node users who are having issues broadcasting their txs with Neutrino.

Transaction: raw TX hex

---

components/Channels/ChannelsFilter.tsx
components/HopPicker.tsx
views/Channels/ChannelsPane.tsx

HopPicker: add search, filters, sort

---

Navigation.ts
locales/en.json
views/Settings/EmbeddedNode/Advanced.tsx
views/Settings/EmbeddedNode/DisasterRecovery.tsx
views/Settings/EmbeddedNode/RestoreChannelBackups.tsx

This PR adds the ability for embedded node users to restore from channel backups after initial wallet recovery.

Embedded LND: Settings > Advanced > Restore channel backups from clipboard

---

views/Receive.tsx

Have keyboards on the `Receive` view be dismissed if you scroll on the main view.

Receive: make it easier to dismiss keyboard

---

lndmobile/index.ts

This PR fixes a bug where Embedded LND users would only see their first 100 created invoices. By default the `ListInvoices` endpoint only returns 100 invoices as max, and unlike the CLI command, returns invoices starting from oldest first.

Embedded LND: ListInvoices: increase max count and reverse

---

views/PaymentRequest.tsx

This PR makes a small change to the `PaymentRequest` view: affixing the `Pay this Invoice` button to the bottom of the view. This makes it easier to press.
Before:
After:

Payment request: fix Pay Invoice button to bottom of view

---

views/Send.tsx

There was an error when a selected contact was cleared in Send screen.
Steps to reproduce:
- Go to Send screen
- Select a contact
- Clear contact by clicking on the x
- Enter something else (e. g. a bitcoin address, do not select a contact in this step), and click proceed
-> The previously selected contact is displayed instead of the entered destination
* verify that dependencies are installed for …

Send screen: fix clearing selected contact

---

views/Settings/AddContact.tsx

https://github.com/ZeusLN/zeus/assets/50761978/df65b2b8-6c06-4608-b67e-1315aac41deb

AddContact: Remove photo on tap

---

ios/Podfile.lock
locales/en.json
package.json
views/Settings/EmbeddedNode/Peers/NeutrinoPeers.tsx
yarn.lock

Relates to issue: [**ZEUS-2070**](https://github.com/ZeusLN/zeus/issues/2070)
This PR adds latency check functionality to the `Neutrino peers` page for embedded LND users. Just hit the hour glass to get the latency for any host.
Moving forward we can automate this and notify users on startup if they will potentially have Neutrino sync issues.
`Success`: < 100ms
`Warning`: 100-200ms
`Error`: 200ms+ …

ZEUS-2070: Embedded LND: Neutrino: add ping test

---

backends/EmbeddedLND.ts
components/UTXOPicker.tsx
ios/LndMobile/Lnd.swift
lndmobile/LndMobileInjection.ts
lndmobile/wallet.ts
stores/TransactionsStore.ts
views/Send.tsx

Relates to issue: [**ZEUS-327**](https://github.com/ZeusLN/zeus/issues/327)
This PR adds support for on-chain send coin control for Embedded LND, LND REST, and LNC backends.

LND: on-chain coin control

---

stores/SettingsStore.ts

Settings: update mainnet Netrino peers

---

views/SendingLightning.tsx
views/SendingOnChain.tsx

Sending views: fix buttons to bottom

---

components/LightningLoadingPattern.tsx
components/LoadingColumns.tsx
components/LoadingIndicator.tsx
components/PaidIndicator.tsx
components/SuccessAnimation.tsx
ios/Podfile.lock
ios/zeus.xcodeproj/project.pbxproj
package.json
yarn.lock

Fixes the crop of the startup screen animation on Android.
Before:
After:

Android: fix crop of startup screen animation

---

views/Channels/Channel.tsx

Channel: remove keysend button

---

views/Settings/SignVerifyMessage.tsx

SignVerifyMessage: Fix layout

---

android/app/build.gradle
android/link-assets-manifest.json
assets/images/SVG/Error.svg
assets/images/SVG/ErrorIcon.svg
components/OnchainFeeInput.tsx
ios/link-assets-manifest.json
ios/zeus.xcodeproj/project.pbxproj
stores/FeeStore.ts
views/EditFee.tsx
views/SendingLightning.tsx
views/SendingOnChain.tsx

This fixes #2168.
Additionally fixed displaying gifs by updating android library (necessary for react native 0.73).

Allow entering custom fee if loading fees from mempool fails

---

models/Payment.ts

Model: Payment: fix isIncomplete check

---

locales/en.json
stores/SettingsStore.ts
utils/ThemeUtils.ts

Theme: Radioactive

---

views/Settings/LightningAddress/NostrRelays.tsx

`+` and `-` icons were always black which made them almost invisible with dark themes.

Nostr relays: use theme color for icons

---

models/Invoice.ts

Relates to issue: [**ZEUS-2201**](https://github.com/ZeusLN/zeus/issues/2201)
The bug report above details an issue with lnurlp payments from LNBits causing ZEUS to crash when pulled up through the `Activity` view. It appears that the `description` field is returned as an array, which was not handled in our model logic. This PR updates the `Invoice` model to handle such cases.
* verify that …

ZEUS-2201: Invoice: handle descriptions/memos returned as arrays

---

README.md

Remove Nayuta Core(out of service).

docs: remove Nayuta Core

---

locales/en.json
utils/handleAnything.test.ts
utils/handleAnything.ts
views/ContactDetails.tsx

https://github.com/ZeusLN/zeus/pull/2078

Send: Lookup nostr contacts

---

App.tsx
assets/images/SVG/Alert.svg
components/Modals/AlertModal.tsx
components/WalletHeader.tsx
locales/en.json
stores/AlertStore.ts
stores/ModalStore.ts
stores/Stores.ts
views/Wallet/Wallet.tsx

This PR adds an alert icon to the wallet header. When clicked it will notify the user if they have an issue that will affect operations including a high zombie channel count and neutrino peers with a high ping time.

Alerts: detect zombie channels + problematic neutrino peers

---

stores/UTXOsStore.ts
views/Wallet/Wallet.tsx

This PR ensures that UTXO and account data is reset when changing wallets/connections.
This would cause accounts to persist on the balance pane after changing to backends that don't support them. Found by Nick on our Telegram channel.

UXTOsStore: reset when changing wallets

---

views/Payment.tsx

Relates to issue: [**ZEUS-2215**](https://github.com/ZeusLN/zeus/issues/2215)
This PR adds the ability to view a BOLT 11 from a paid payment view by hitting the QR icon in the header.

ZEUS-2215: Payment: paid, display the BOLT 11 invoice

---

views/HandleAnythingQRScanner.tsx

This PR adds the ability for us to parse `crypto-account` data from BC-UR animated QR codes. Data will be directed to our new `Import Account` view.

BC-UR: parse crypto-account data

---

stores/UnitsStore.ts

The `getFormattedAmount` was using logic to flatten millisats on Bitcoin decimal amounts, causing items on the POS pane to be displayed incorrectly.
Before:
After:

getFormattedAmount: fix BTC decimal amounts

---

components/Channels/ChannelItem.tsx
components/LSPS1OrderResponse.tsx
locales/en.json

LSPS1: Add status bar for lsp and client balances

---

backends/CLightningREST.ts

Relates to issue: [**ZEUS-2225**](https://github.com/ZeusLN/zeus/issues/2225)

ZEUS-2225: c-lightning-REST: update getChannels call

---

components/TextInput.tsx
locales/en.json
stores/SettingsStore.ts
utils/LndMobileUtils.ts
views/Settings/EmbeddedNode/Advanced.tsx

Relates to issue: [**ZEUS-2158**](https://github.com/ZeusLN/zeus/issues/2158)
Allows mobile LND users to set a custom fee estimator.

ZEUS-2158: Embedded LND: Settings: add Custom fee estimator

---

models/Invoice.ts
views/Receive.tsx

CLNRest: show indicator on payment received

---

.github/PULL_REQUEST_TEMPLATE.md

Add CLNRest node type to PULL_REQUEST_TEMPLATE.md

Add CLNRest node type to PULL_REQUEST_TEMPLATE.md

---

backends/CoreLightningRequestHandler.ts

The [Core Lightning Documentation on the SQL](https://docs.corelightning.org/reference/lightning-sql) endpoint suggests not using `SELECT *` because queries like this are fragile, as columns will change across releases. This PR is an update to the query to pull the 7 specific columns zeus uses instead of the 17 prior to this PR. This change aligns with CLN recommendation of this endpoint and improves performance/efficiency. On my node I found this change saves roughly 40% data on the `/v1/sql` endpoint for `bkpr_accountevents`.
I have tested this PR with the following types of nodes …

[Enhancement] CLNRest select specific columns from bkpr_accountevents table 

---

backends/LND.ts
backends/LightningNodeConnect.ts

https://github.com/ZeusLN/zeus/issues/2117

LND: Network Info

---

utils/handleAnything.ts

https://github.com/ZeusLN/zeus/issues/2339

handleAnything: Fix lnaddress with onion domain

---

views/Send.tsx

We have upgraded the fetching of Contacts here on `Send` view (while displaying the favourite contacts).
Now we are using [ContactStore](https://github.com/ZeusLN/zeus/blob/master/stores/ContactStore.ts) which is being added recently in master

Send: Using ContactStore to fetch contacts

---

stores/SettingsStore.ts
utils/LndMobileUtils.ts

Adds a block of peers from Asia to try, if a user still hasn't found three peers with acceptable ping time.
- `peerTargetCount` added as a param to `optimizeNeutrinoPeers` (3)
- `SECONDARY_NEUTRINO_PEERS_MAINNET` refactored for groupings - room to add other regions now
- Checks fixed

Embedded Node: Optimize Neutrino Peers: Asia

---

locales/en.json
stores/UTXOsStore.ts
views/Accounts/ImportAccount.tsx

Originally we were generating 50 standard addresses and 50 change addresses. Now it will be user configurable.

Import Account: make count of addresses to generate user configurable

---

stores/SettingsStore.ts

Nostr: new default relays

---

locales/en.json
stores/SettingsStore.ts
utils/ThemeUtils.ts

Themes: replace Orange w/ Spooky

---

views/Settings/Contacts.tsx

Skip navigating from SendScreen to ContactDetails in case contact has only 1 address

---

components/Conversion.tsx

Entering in a decimal on the `Keypad` view will cause the conversion to display as `$NaN` - this change handles those edge cases.
Before:
After:

Conversion component: handle NaN edge cases

---

components/Channels/ChannelItem.tsx
components/LayerBalances/index.tsx
views/Accounts/Accounts.tsx
views/AddNotes.tsx
views/EditFee.tsx
views/SendingOnChain.tsx

The error we were facing in some of the views

Convert `require` to `import` while using images

---

.github/workflows/tsc.yml
App.tsx
backends/CLNRest.ts
backends/CLightningREST.ts
backends/Eclair.ts
backends/EmbeddedLND.ts
backends/LightningNodeConnect.ts
backends/Spark.ts
components/SetFeesForm.tsx
lndmobile/LndMobileInjection.ts
lndmobile/index.ts
lndmobile/scheduled-sync.ts
lndmobile/wallet.ts
models/Channel.ts
models/ClosedChannel.ts
package.json
views/Channels/Channel.tsx
yarn.lock

This PR adds the final Typescript check fixes for the codebase and re-adds the tsc GitHub workflow.

tsc: final codebase fixes and re-add GitHub workflow

---

views/Channels/ChannelsPane.tsx
views/Order.tsx
views/PSBT.tsx
views/Receive.tsx
views/Routing/Routing.tsx
views/Settings/LSPS1/index.tsx
views/TxHex.tsx

We had these issues in button layouts on Receive view which came after our recent typescript fix after this [change](https://github.com/ZeusLN/zeus/commit/9712aad0878f2d1b8b62da94ad02f2b12a1b041e#diff-879ea016c4558f026ea4413d7927fe60b543dec7a5572514fd3224c9da3eee52R1399)
Fixed the issue by reversing the changes.
Below is one of those layout issues
Before:
After:

Fix: Button Layouts in Views

---

views/Wallet/StandalonePosPane.tsx

Apparently we have created some bugs after merging the last tsc fix PR. 
This is one of the fixes of those bugs

Tsc Bug Fix

---

views/Wallet/StandalonePosPane.tsx

Issue: #2499 
We have removed unnecessary conditions in rendering of SearchBar which was causing the SearchBar to hide if no items were found while searching.

StandalonePOSPane: Fix SearchBar Bug 

---

stores/ChannelsStore.ts

Only console.log Pending HTLCs if existing

---

backends/CLNRest.ts
backends/CLightningREST.ts
backends/Eclair.ts
backends/LND.ts
backends/LightningNodeConnect.ts
backends/LndHub.ts
backends/Spark.ts
models/Invoice.ts
models/Order.ts
models/Payment.ts
models/Transaction.ts
stores/storeInstances.ts
utils/BackendUtils.ts

To avoid Require Cycle warnings a central file `storeInstances` is used now.

Use central storeInstances file

---

stores/LightningAddressStore.ts
views/Settings/LightningAddress/index.tsx

This PR addresses two issues with ZEUS Pay lightning address.
- Firstly, when users move to a new device, we now send a `newDevice` flag to the `/submitHashes` endpoint that ensures all pending payments are cleared and that all old hashes are deleted.
- Secondly, it fixes an issues where our old `missing preimage` error is not thrown after hitting the `Redeem all` button
Local hash count and a `Clear local hashes` button are added while in development.
* verify that …

ZEUS Pay: new device check

---

components/AccountFilter.tsx

Relates to issue: [**ZEUS-2523**](https://github.com/ZeusLN/zeus/issues/2523)

ZEUS-2523: Bug fix: Coins: external wallets marked hidden appear in tab nav

---

views/Receive.tsx

Previously, hitting the pencil icon off the `Keypad Pane` view would pass the amount (0) as a prop to the `Receive` view, inputting into the amount input field, unnecessarily. This small change prevents that from happening.

Receive: do not place 0 into amount input field

---

views/Settings/SeedRecovery.tsx

Improvements:
- allow selecting mnemonic word suggestion with one tap while keyboard is visible
- focus next word when selecting suggestion
- open keyboard when tapping on word or SCB label while already in selection mode (before the keyboard could only be brought back when tapping on the text input)
- hide restore button while typing to prevent starting restore with invalid/incomplete word in current input
- code refactoring …

Improve wallet recovery screen

---

utils/ContactUtils.ts

After consulting with @shubhamkmr04 removed unneeded logging, because it is a bit distracting (requires to scroll to see test results).

Remove ContactUtils console.log

---

components/PaymentPath.tsx

This fixes
`ERROR  Warning: Each child in a list should have a unique "key" prop. See https://reactjs.org/link/warning-keys for more information.`

PaymentPath: Add key props

---

components/LayerBalances/OnchainSwipeableRow.tsx
components/LayerBalances/index.tsx
stores/UTXOsStore.ts

Some UX improvements to `Accounts`:
- Remove stutter when hiding/filtering
- Reduce opacity of hidden/filtered accounts for readability
Before:
After:

Accounts: UX improvements

---

ios/Podfile.lock
ios/zeus.xcodeproj/project.pbxproj
locales/en.json
models/Channel.ts
package.json
views/Channels/Channel.tsx
yarn.lock

Adds display of ID and SCID to the single `Channel` view, and adds a few other refinements:
- Spacing fixes: reduce padding around balance slider, increase around status
- Center status
- Move Alias SCIDs below ID and SCID
Before:
After:

Channel: display ID and SCID

---

views/Activity/Activity.tsx

Hide export icon if activity empty

---

utils/DateTimeUtils.ts

Activity: Display year if not current year

---

views/Receive.tsx

Hide "RECEIVE VIA NFC" button while loading

---

index.js
models/BaseModel.ts

Fixes https://github.com/ZeusLN/zeus/issues/2489

Embedded LND: handle Long values

---

App.tsx
locales/en.json
views/Settings/EmbeddedNode/Advanced.tsx
views/Settings/EmbeddedNode/Troubleshooting.tsx
views/Settings/EmbeddedNode/index.tsx

This PR adds the most common settings for troubleshooting the Embedded LND node into one menu. This should allow users to more easily remedy the most common issues we hit with the 'node in the phone'

Embedded node: add Troublshooting menu

---

components/LayerBalances/OnchainSwipeableRow.tsx

Small regression caused by https://github.com/ZeusLN/zeus/pull/2569
Before:
After:

iOS: fix display of external account rows on sync

---

components/Channels/ChannelsFilter.tsx
components/Channels/FilterOptions.tsx
views/Channels/ChannelsPane.tsx

Relates to issue: [**ZEUS-2610**](https://github.com/ZeusLN/zeus/issues/2610)
Regression from https://github.com/ZeusLN/zeus/pull/2561/

ZEUS-2610: Channels: restore sort by Close Height

---

utils/ConnectionFormatUtils.ts
views/Settings/WalletConfiguration.tsx

Relates to issue: [**ZEUS-2623**](https://github.com/ZeusLN/zeus/issues/2623)

ZEUS-2623: Wallet config: Paste CLNRest Connection String

---

backends/CLNRest.ts

Relates to issue: [**ZEUS-2603**](https://github.com/ZeusLN/zeus/issues/2604)

ZEUS-2604: CLNRest: Cannot create LN invoice with empty amount

---

views/Settings/WalletConfiguration.tsx

New wallets are added by using `push()`, which fixes
`WARN  [mobx.array] Attempt to read an array index (2) that is out of bounds (2). Please check length first. Out of bound indices will not be tracked by MobX`.

Add wallet: use safe node addition

---

views/OpenChannel.tsx

Open Channel: change toggle header to tabs

---

components/TextInput.tsx
package.json
views/Settings/CurrencyConverter.tsx
views/Settings/Wallets.tsx
yarn.lock

Rare edge case, but previously, nodes with identical configurations had the same id, leading to
`ERROR  Warning: Encountered two children with the same key` (and whatever issues in the future).
Now also using index for keyExtractor in nodes DragList.
Since that broke drag functionality, updated DragList to 3.8.0 -> now working fine.
Dragging also tested in currency converter with new DragList version -> working fine as well.
* verify that `package.json` and `yarn.lock` …

Use index for keyExtractor in nodes DragList

---

utils/ActivityFilterUtils.ts

Relates to issue: [**ZEUS-2641**](https://github.com/ZeusLN/zeus/issues/2641)

ZEUS-2641: Activity: make send and receive inclusive of 0

---

views/Settings/WalletConfiguration.tsx

The `Wallet active` label was persisting when the wallet config was being copied.

Wallet config: set config to inactive when copied

---

views/Settings/Security.tsx

Security: After deleting PIN/passphrase, refresh pinExists and passphraseExists

---

views/Settings/SetPassword.tsx

Set password: Auto focus new password input

---

utils/handleAnything.test.ts
utils/handleAnything.ts

Adds trimming of data processed by handleAnything.
(I encountered a QR code that contained a whitespace after the bitcoin address and I was wondering why Zeus couldn't scan it...)

Trim input data in handleAnything

---

views/Settings/WalletConfiguration.tsx
views/Settings/Wallets.tsx

Relates to issue: [**ZEUS-2616**](https://github.com/ZeusLN/zeus/issues/2616)

ZEUS-2616: Switch wallet via 'Set wallet config as active' leads to buggy state

---

index.js

Add missing semicolon

---

assets/images/SVG/DeleteKey.svg
components/PinPad.tsx

Pin Pad: new delete key

---

models/Invoice.ts

Fixed another `[mobx.array] Attempt to read an array index (0) that is out of bounds (0). Please check length first. Out of bound indices will not be tracked by MobX` warning.
Added check to avoid potentially unnecessary backendcall `transactionsStore.getTransactions()`.

Fix array out of bounds warning, avoid potentially unnecessary backend call

---

utils/ErrorUtils.test.ts
utils/ErrorUtils.ts

See above...
This fixes a regression from https://github.com/ZeusLN/zeus/pull/2654 (partial matching).

Display complete error message, if error is unhandled but contains "Error"

---

views/Send.tsx

Relates to issue: [**ZEUS-2762**](https://github.com/ZeusLN/zeus/issues/2762)

ZEUS-2762: bolt12: Zeus sends sats when user specifies fiat

---

backends/CLNRest.ts
backends/LND.ts
backends/LightningNodeConnect.ts
views/Receive.tsx

To help with `Activity` performance we are modifying the LND activity calls to include hard limits of 500:
500 invoices
500 LN payments
Limit of 500 txs is now in a separate PR here: https://github.com/ZeusLN/zeus/pull/2771 as `max_transactions` on `GetTransactions` still hasn't been cut into an LND release yet

 Activity: LND: limit to 500 invoices + payments

---

views/Settings/WalletConfiguration.tsx

This fixes the margin issue of the error message (see No. 2. here: https://github.com/ZeusLN/zeus/pull/2594#pullrequestreview-2577805622) by removing the negative marginTop.
Additionally made the photo perfectly round (before borderRadius was not 1/2 of diameter) and also fixed its vertical alignment with the input.
-> Both is almost invisible, but was technically not clean before.
|before|after|
|-|-
|![grafik](https://github.com/user-attachments/assets/e39d116c-e921-4800-9c58-40d01134da93)|![grafik](https://github.com/user-attachments/assets/7540b164-e66e-4ca7-b4c6-cafe0c0660f5)|
|![grafik](https://github.com/user-attachments/assets/1d3bfbc3-1e8b-4788-b8ec-5dd258a8eb6d)|![grafik](https://github.com/user-attachments/assets/a25efc70-a4c0-4e17-ad0d-89f01ea7347e)|
This pull request is …

Wallet configuration: Fix minor layout issues

---

stores/TransactionsStore.ts

Relates to issue: [**ZEUS-2798**](https://github.com/ZeusLN/zeus/issues/2798)

ZEUS-2798: UTXO Consolidation Transaction Not Working

---

views/Tools.tsx

Added existing locale string for Tools header.

Missing 'Tools' locale string

---

stores/SyncStore.ts
utils/LndMobileUtils.ts

Now using MobX's `when` instead of polling with setInterval, providing immediate response to state changes.

Replace polling in expressGraphSync() with reactive handler

---

components/AmountInput.tsx
views/Settings/PaymentsSettings.tsx

Reported from a user on Nostr:
It seems the regression was added in https://github.com/ZeusLN/zeus/pull/2806
This change doesn't appear to reintroduce https://github.com/ZeusLN/zeus/issues/2802

AmountInput: fix flow from Keypad view

---

backends/CLNRest.ts
stores/TransactionsStore.ts
views/PaymentRequest.tsx
views/Settings/PaymentsSettings.tsx

Add an option to set custom timeout for LN payments in CLNRest, using the `retry_for` parameter.

Add option to set payments timeout for CLNRest

---

stores/ChannelBackupStore.ts

Relates to issue: [**ZEUS-2868**](https://github.com/ZeusLN/zeus/issues/2868)
Backup status params were not updated properly during our storage migration.

ZEUS-2868: fix display of backup status

---

views/NodeInfo.tsx

fix: update nodeInfo currentBlockHeight render condition

---

views/Settings/LSP.tsx

Update LSP doc link

---

stores/TransactionsStore.ts

In-flight payments would sometimes return as succesfully paid.

handlePayment: handle false positive on in-flight payment

---

views/Settings/LightningAddress/index.tsx

Relates to issue: [**ZEUS-2811**](https://github.com/ZeusLN/zeus/issues/2811)

ZEUS-2811: ZEUS Pay: fix Olympus chan check

---

android/app/src/main/AndroidManifest.xml

Relates to issue: #2888 
- Before
https://github.com/user-attachments/assets/9c8fe538-e88d-418a-8ba8-0b36847a9655
- After
https://github.com/user-attachments/assets/b424893c-1778-446f-80c3-d348b665ce47

fix: Updated AndroidManifest.xml to redirect to the email app correctly

---

locales/en.json
utils/ErrorUtils.test.ts
utils/ErrorUtils.ts

ErrorUtils: handle invalid response data from the server

---

components/Modals/AndroidNfcModal.tsx

Relates to issue: #2892 
Before:
After (Edit: Updated the Modal Background to Transparent):

UI: Add dynamic background/text colors to AndroidNfcModal

---

views/Settings/SeedRecovery.tsx

https://github.com/ZeusLN/zeus/issues/2928

[fix] Wallet recovery: app crash

---

views/Order.tsx

Somewhat related to https://github.com/ZeusLN/zeus/issues/2699
Previously, the Total (Bitcoin) value was displaying as **NaN**, which caused the Pay button to be disabled. This issue was due to taxSats being calculated using fiat rates, and when fiat rates were disabled, it resulted its value as **NaN**. 
This has now been fixed by updating the taxSats calculation to handle the case when fiat rates are disabled. 
Additionally, the values in fiat are not displayed now(they were $N/A anyways)when fiat rates are not enabled.
Before:
After:

[fix] POS Bug: prevent NaN in Total sats

---

stores/LightningAddressStore.ts
views/Settings/LightningAddress/index.tsx

Disabled at present for ZEUS Pay+

ZEUS Pay: don't allow users to set handles on account creation

---

components/DropdownSetting.tsx
views/Receive.tsx
views/Settings/InvoicesSettings.tsx
views/Settings/PaymentsSettings.tsx

Relates to issue: [**ZEUS-2608**](https://github.com/ZeusLN/zeus/issues/2608)
Before screenshots may be misleading as the issue is exacerbated on different resolutions. See original issue.
Before:
|Android: Receive|Android: Invoice Settings|iOS: Receive|iOS: Invoice Settings|
|-|-|-|-|
|![Screenshot_1744500569](https://github.com/user-attachments/assets/48a45b96-778f-4f6d-9de3-b3d6b1ea37b9)|![Screenshot_1744500559](https://github.com/user-attachments/assets/b097096a-198d-439c-a832-0fcf7fac1db8)|![simulator_screenshot_2308A3C5-917C-4563-B2FA-6B9E08FA3377](https://github.com/user-attachments/assets/c35ed857-30e3-4a40-94b7-07b682117e0f)|![simulator_screenshot_AEA80286-82EC-460A-867A-9A848184B35F](https://github.com/user-attachments/assets/40d11e90-c046-4fd4-8292-1ecd6d05bfe1)|
After …

ZEUS-2608: fix DropdownSetting alignment issues

---

models/Invoice.ts
models/Payment.ts
stores/ActivityStore.ts
utils/ActivityFilterUtils.test.ts
utils/ActivityFilterUtils.ts
views/Activity/ActivityFilter.tsx

Relates to issue: [**ZEUS-2670**](#2670)
Activities with keysend filter 
Activities without keysend filter 

feat : Activity add filters for Keysends

---

stores/FiatStore.ts
views/Tools/CurrencyConverter.tsx

The problem was that the fiat rates aren't being automatically fetched when the component mounts. Instead, the component only shows an error message that requires manual intervention.
Relates to issue: **ZEUS-2492**
Added a method call that fetches the fiatRate once the component mounts
- [] LND (REST)

fix: Added logic to fetch the fiatRates as the component mounts

---

views/Settings/WalletConfiguration.tsx

Relates to issue: [ZEUS-2679](https://github.com/ZeusLN/zeus/issues/2679)
This PR implements **`ShowHideToggle`** functionality for sensitive input fields across different node connection configurations to enhance security and user experience.
- **LND (REST)**:  
- Macaroon field – Added `ShowHideToggle` to allow secure toggling of the value.
- **LND (Lightning Node Connect)**:  
- Pairing Phrase – Integrated `ShowHideToggle` to hide/reveal the sensitive input.
- **Core Lightning (CLNRest)**:  
- Rune – Added `ShowHideToggle` to manage visibility of the authentication token.
<table>
<tr>
<td><img src="https://github.com/user-attachments/assets/a241a40c-a167-4006-b065-475f260449d8" alt="Image 1" width="300"/></td>
<td><img src="https://github.com/user-attachments/assets/e5bce2e9-795d-422d-a …

Add Show/Hide Toggle for Sensitive Input Fields in Node Connection Configurations

---

stores/LSPStore.ts
views/Receive.tsx

- Fixed the stale error message still being present during new invoice creation
- This was done by modifying the `reset()` action in the LSPStore, by introducing a param that allows fine-grained control of either just resetting the error or the complete states in the Store
PFA The Screen Recording of the issue here (Before)
- https://zeusln.slack.com/archives/C06U4KXR8GK/p1743180461821719
PFA the recording after the fix (Notice the stale error is no longer being carried to the next screen)
https://github.com/user-attachments/assets/790f81ed-825b-4e21-b1d9-41f2ffdff844
I have tested this PR on the following platforms (please specify OS version and …

UI/UX improvements for Receive view

---

backends/CLNRest.ts
backends/LND.ts

Backends: allow override of default timeout #2887
Changes Made:
Updated CLNREST and LND  in backends to include an optional timeout parameter in the request for allow override of default timeout

Backends: allow override of default timeout #2887

---

utils/handleAnything.ts

Fixes: https://github.com/ZeusLN/zeus/issues/2986

bip353: join multiline txt without whitespace

---

components/CollapsedQR.tsx
views/NodeInfo.tsx

In case there are multiple URIs, the margins didn't make sense...
|Before|After|
|-|-|
|![grafik](https://github.com/user-attachments/assets/eaab2099-6401-44ba-a556-48289120ec32)|![grafik](https://github.com/user-attachments/assets/56cf2db9-7d53-41ec-bab4-4697374adff3)|

Node Info View: minor layout fix

---

views/ContactQR.tsx

Relates to issue: [**ZEUS-2980**](https://github.com/ZeusLN/zeus/issues/2980)
This PR updates the UI, to use icons (copy/share) for contact QR

fix: Icons in Contact QR

---

locales/en.json
package.json
stores/SettingsStore.ts
stores/SwapStore.ts
views/Swaps/Settings.tsx

Relates to issue: [**ZEUS-2983**](https://github.com/ZeusLN/zeus/issues/2983)
This PR allow users to use Pro, when using the Boltz.exchange instance.

feat: Boltz.exchange Pro mode

---

backends/CLNRest.ts
backends/EmbeddedLND.ts
backends/LND.ts
backends/LightningNodeConnect.ts
backends/LndHub.ts
backends/NostrWalletConnect.ts
package.json
stores/InvoicesStore.ts
utils/BackendUtils.ts
views/Receive.tsx
views/Settings/InvoicesSettings.tsx

Relates to issue: [**ZEUS-1698**](https://github.com/ZeusLN/zeus/issues/1698)
This PR adds taproot on-chain addresses for CLN-rest.

feat: CLNRest taproot addresses

---

views/Order.tsx

Originally reported on [Nostr](https://nostr.band/note1mm7pe2x227dpxm3k49zmxd6730f2r25pkperqp5geexlp4qs5mzq5h5wqv) by Fern 
note1mm7pe2x227dpxm3k49zmxd6730f2r25pkperqp5geexlp4qs5mzq5h5wqv

fix: Item pricing in Square POS mode

---

backends/LND.ts
backends/LightningNodeConnect.ts

Issue raised on telegram https://t.me/zeusLN/96699
We have fixed the precision error we were getting while setting up the inbound fee rate

fix: LND: precision bug for inbound fee rate

---

views/LnurlPay/LnurlPay.tsx
views/LnurlPay/Metadata.tsx
views/LnurlPay/Success.tsx

Relates to issue: [**ZEUS-3017**](https://github.com/ZeusLN/zeus/issues/3017)

feat: toggle hint icon

---

views/Send.tsx
views/Wallet/BalancePane.tsx

This fixes a regression of https://github.com/ZeusLN/zeus/pull/3037
|before|after|
|-|-|
|![grafik](https://github.com/user-attachments/assets/cf443250-7796-4d20-bdfe-60aeca2342a4)|![grafik](https://github.com/user-attachments/assets/ab812218-d232-4643-86fb-8f507ca10fb6)|
|![grafik](https://github.com/user-attachments/assets/3c254cbb-1caf-4836-808c-5ab7481c7eb0)|![grafik](https://github.com/user-attachments/assets/3947ee86-74f9-4eca-8a03-343b02a3178c)|
* verify that …

design: Fix regression PR #3037

---

components/WalletHeader.tsx

Relates to issue: [**ZEUS-1625**](https://github.com/ZeusLN/zeus/issues/1625)

ZEUS-1625: fix: improved clipboard button behavior

---

views/Cashu/Mint.tsx

Some content, including the contact info of a mint, was getting stuck at the bottom and not showing properly. This was mostly because of the use of **absolute** in the `bottom` class. 

fix: hiding content on Mint view

---

views/Cashu/ReceiveEcash.tsx
views/Order.tsx
views/Receive.tsx

- Decreases the receipt font by 33% from 12px to 8px for itemized lines
- Adds the line 'Powered by ZEUS' + logo at the bottom of the receipt
- Fixes a bug where printing from the payment success screen was broken

POS receipt enhancements + fixes

---

backends/LND.ts
backends/LightningNodeConnect.ts

fix: handling empty inbound fee rate

---

components/HopPicker.tsx
components/Modals/AlertModal.tsx
components/Modals/AndroidNfcModal.tsx
components/Modals/ExternalLinkModal.tsx
components/Modals/InfoModal.tsx
utils/ThemeUtils.ts
views/Receive.tsx
views/Settings/CustodialWalletWarning.tsx
views/Settings/InvoicesSettings.tsx
views/Wallet/KeypadPane.tsx

Relates to issue: **ZEUS- #3063

enhancement: added support for model background in themeColor

---

views/Cashu/ReceiveEcash.tsx

- Refactors the Cashu receive code to remove unused listeners.
- Fixes UX where received Ecash payments weren't processed when users were backed out of the receive view. Users would then have to either pull up the invoice under `Activity` or reload the app to process the invoice and correctly display their ecash balance.

refactor: fix listeners on Receive Ecash view

---

views/Swaps/SwapDetails.tsx

Relates to issue: [**ZEUS-3100**](https://github.com/ZeusLN/zeus/issues/3100)
This PR addresses two issues we've found so far with refunds, when user is making a submarine swaps (chain -> LN)
1) False positive state for refunds. User fails to make payment to the on-chain address. Swap state results in `invoice.failedToPay | invoice expired`. The user doesn't have a lockupTransaction return from `/transaction` because they haven't made the on-chain tx, and the endpoint returns `{"error":""no coins were locked up yet"}`.
In this case the refund button should be hidden, as there are no locked up funds to be refunded. This is fixed with changes on line 769.
2) User successfully makes on-chain payment, but the service is unable to pay their invoice. Swap state results in `invoice.failedToPay | …

ZEUS-3100: swaps refund edge case

---

components/CollapsedQR.tsx
locales/en.json
views/Cashu/CashuToken.tsx
views/PSBT.tsx
views/TxHex.tsx

Relates to issue: [**ZEUS-3097**](https://github.com/ZeusLN/zeus/issues/3097)

feat: Dynamic Cashu QRs

---

stores/LightningAddressStore.ts
views/LightningAddress/ZeusPayPlusPerksList.tsx

feat: ZEUS Pay+: get perks from service

---

components/WalletHeader.tsx
stores/ChannelsStore.ts
views/Channels/ChannelsPane.tsx

This PR leverages our saved node data in the channels store to pull aliases, if they are not defined on the peer itself. Additionally, the Peers count in the header is updated to reflect the filter results.
Before
|List view example|Filter example|
|-|-|
|<img width="1206" height="2622" alt="Simulator Screenshot - iPhone 16 Pro - 2025-07-29 at 20 37 58" src="https://github.com/user-attachments/assets/388f695c-93da-487f-bbf9-8e265ed3e933" />|<img width="1206" height="2622" alt="Simulator Screenshot - iPhone 16 Pro - 2025-07-29 at 20 38 02" src="https://github.com/user-attachments/assets/4a79f379-4e5a-45e7-85d9-b16221fbc3fe" />|
After
|List view example|Filter example|
|-|-|
|<img width="1206" height="2622" alt="Simulator Screenshot - iPhone 16 Pro - 2025-07-29 at 20 37 06" …

enhancement: Peers: leverage stored aliases

---

components/LayerBalances/LightningSwipeableRow.tsx
components/LayerBalances/PaymentMethodList.tsx
utils/handleAnything.ts
views/ChoosePaymentMethod.tsx

Relates to issue: [**ZEUS-3200**](https://github.com/ZeusLN/zeus/issues/3200)
test address: `leo@liongrass.hk`

ZEUS-3200: feat: support hybrid Lightning addresses (BIP-353/BOLT-12 + LNURL-pay)

---

components/Channels/ChannelsFilter.tsx
stores/ChannelsStore.ts
views/Channels/ChannelsPane.tsx

As discussed in: [**ZEUS-3183**](https://github.com/ZeusLN/zeus/pull/3183#issuecomment-3140705494)

fix(channelsPane): conditional filtering 

---

stores/CashuStore.ts
stores/InvoicesStore.ts
stores/NostrWalletConnectStore.ts
views/Receive.tsx
views/Swaps/Refund.tsx
views/Swaps/index.tsx

Relates to issue: [ZEUS-3095](https://github.com/ZeusLN/zeus/issues/3095)

[nwc-service] fix: rename expiry to expirySeconds to resolve type error

---

backends/CLNRest.ts
backends/EmbeddedLND.ts
backends/LND.ts
backends/LightningNodeConnect.ts
backends/LndHub.ts
backends/NostrWalletConnect.ts
stores/BalanceStore.ts
utils/BackendUtils.ts

Relates to issue: [**ZEUS-3270**](https://github.com/ZeusLN/zeus/issues/3270)

ZEUS-3270: fix: errant on-chain balance calls to LNDHub

---

views/Settings/SelectCurrency.tsx

enhancement: Select Currency: disable autocorrect in search bar

---

App.tsx

**Issue:** When opening the app with an intent containing both on-chain addresses and lightning invoices, users get stuck on the Choose Payment Method view and cannot proceed with payment processing. It mostly happens when the app is opened from the fully closed state.

fix: bug: deep link `Choose Payment Method` loop

---

components/LayerBalances/EcashSwipeableRow.tsx
components/LayerBalances/LightningSwipeableRow.tsx
components/LayerBalances/PaymentMethodList.tsx
utils/handleAnything.ts
views/ChoosePaymentMethod.tsx

Relates to issue: [ZEUS-3253](https://github.com/ZeusLN/zeus/issues/3253)

feat: enable LNURL-w redemption to Cashu wallet
